[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.4", features = ["derive"] }
derive_builder = "0.20.0"
itertools = "0.13.0"
log = "0.4.21"
serde = "1.0.203"
serde_with = "3.8.1"
