use std::fmt::{Debug, Formatter};
use std::hash::{Hash, Hasher};
use crate::message_types::MessageType;
use crate::types::{Event, EventType, TimeMode};
use crate::types::{BacklightMode, FileType};

#[derive(Clone)]
pub struct Field {
    pub name: String,
    pub translate_enum: fn(&Field, &u8) -> String,
}

impl Hash for Field {
    fn hash<H: Hasher>(&self, state: &mut H) {
        self.name.hash(state);
    }
}

impl PartialEq for Field {
    fn eq(&self, other: &Self) -> bool {
        self.name == other.name
    }
}

impl Eq for Field {}

impl Debug for Field {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        if !self.name.eq("Unknown") {
           return f.debug_set()
                .entry(&self.name)
                .finish();
        }
        f.write_str("")
    }
}

impl Field {
    const fn from(name: String) -> Self {
        Field::from_with_converter(name, |_, value| -> String {
            format!("Cannot translate {}", value)
        })
    }
    const fn from_with_converter(
        name: String,
        translate_enum: fn(&Field, &u8) -> String,
    ) -> Self {
        Field {
            name,
            translate_enum,
        }
    }

    pub fn resolve(message_type: &MessageType, i: u8) -> Field {
        // sorted by Profile.xlsx/Messages
        match (message_type.number, i) {
            // file_id (0)
            (0, 0) => Field::from_with_converter("Type".to_string(), |_, value| -> String {
                FileType::resolve(value).to_string()
            }),
            (0, 1) => Field::from("Manufacturer".to_string()),
            (0, 2) => Field::from("Product".to_string()),
            (0, 3) => Field::from("Serial number".to_string()),
            (0, 4) => Field::from("Time created".to_string()),
            (0, 5) => Field::from("Number".to_string()),
            (0, 8) => Field::from("Product name".to_string()),


            // file creator (49)
            (49, 0) => Field::from("Software version".to_string()),
            (49, 1) => Field::from("Hardware version".to_string()),
            // timestamp_correlation (162)
            (162, 253) => Field::from("timestamp".to_string()),
            (162, 0) => Field::from("fractional_timestamp".to_string()),
            (162, 1) => Field::from("system_timestamp".to_string()),
            (162, 2) => Field::from("fractional_system_timestamp".to_string()),
            (162, 3) => Field::from("local_timestamp".to_string()),
            (162, 4) => Field::from("timestamp_ms".to_string()),
            (162, 5) => Field::from("system_timestamp_ms".to_string()),
            // software (35)
            (35, 254) => Field::from("message_index".to_string()),
            (35, 3) => Field::from("version".to_string()),
            (35, 5) => Field::from("part_number".to_string()),
            // slave device (106)
            (106, 0) => Field::from("manufacturer".to_string()),
            (106, 1) => Field::from("product".to_string()),
            // capabilities (1)
            (1, 0) => Field::from("Languages".to_string()),
            (1, 1) => Field::from("Sports".to_string()),
            (1, 21) => Field::from("Workouts supported".to_string()),
            (1, 23) => Field::from("Connectivity supported".to_string()),
            // file capabilities (37)
            (37, 254) => Field::from("message_index".to_string()),
            (37, 0) => Field::from("type".to_string()),
            (37, 1) => Field::from("flags".to_string()),
            (37, 2) => Field::from("directory".to_string()),
            (37, 3) => Field::from("max_count".to_string()),
            (37, 4) => Field::from("max_size".to_string()),
            // message capabilities (38)
            (38, 254) => Field::from("message_index".to_string()),
            (38, 0) => Field::from("file".to_string()),
            (38, 1) => Field::from("mesg_num".to_string()),
            (38, 2) => Field::from("count_type".to_string()),
            (38, 3) => Field::from("count".to_string()),
            // field capabilities (39)
            (39, 254) => Field::from("message_index".to_string()),
            (39, 0) => Field::from("file".to_string()),
            (39, 1) => Field::from("mesg_num".to_string()),
            (39, 2) => Field::from("field_num".to_string()),
            (39, 3) => Field::from("count".to_string()),
            // device settings (2)
            (2, 0) => Field::from("Active time zone".to_string()),
            (2, 1) => Field::from("UTC offset".to_string()),
            (2, 2) => Field::from("Time offset".to_string()),
            (2, 4) => Field::from_with_converter("Time mode".to_string(), |_, value| -> String {
                TimeMode::resolve(value).to_string()
            }),
            (2, 5) => Field::from("Time zone offset".to_string()),
            (2, 12) => Field::from_with_converter("Backlight mode".to_string(), |_, value| -> String {
                BacklightMode::resolve(value).to_string()
            }),
            (2, 36) => Field::from("Activity tracker enabled".to_string()),
            (2, 39) => Field::from("Clock time".to_string()),
            (2, 40) => Field::from("Pages enabled".to_string()),
            (2, 46) => Field::from("Move alert enabled".to_string()),
            (2, 47) => Field::from("Date mode".to_string()),
            (2, 55) => Field::from("Display orientation".to_string()),
            (2, 56) => Field::from("Mounting side".to_string()),
            (2, 57) => Field::from("Default page".to_string()),
            (2, 58) => Field::from("Autosync min. steps".to_string()),
            (2, 59) => Field::from("Autosync max. steps".to_string()),
            (2, 80) => Field::from("Lactate threshold autodetect enabled".to_string()),
            (2, 86) => Field::from("BLE auto upload enabled".to_string()),
            (2, 89) => Field::from("Auto sync frequency".to_string()),
            (2, 90) => Field::from("Auto activity detect".to_string()),
            (2, 94) => Field::from("Number of screens".to_string()),
            (2, 95) => Field::from("Smart notification display orientation".to_string()),
            (2, 134) => Field::from("Tap interface".to_string()),
            (2, 174) => Field::from("Tap sensitivity".to_string()),
            // user profile (3)
            (3, 254) => Field::from("message_index".to_string()),
            (3, 0) => Field::from("friendly_name".to_string()),
            (3, 1) => Field::from("gender".to_string()),
            (3, 2) => Field::from("age".to_string()),
            (3, 3) => Field::from("height".to_string()),
            (3, 4) => Field::from("weight".to_string()),
            (3, 5) => Field::from("language".to_string()),
            (3, 6) => Field::from("elev_setting".to_string()),
            (3, 7) => Field::from("weight_setting".to_string()),
            (3, 8) => Field::from("resting_heart_rate".to_string()),
            (3, 9) => Field::from("default_max_running_heart_rate".to_string()),
            (3, 10) => Field::from("default_max_biking_heart_rate".to_string()),
            (3, 11) => Field::from("default_max_heart_rate".to_string()),
            (3, 12) => Field::from("hr_setting".to_string()),
            (3, 13) => Field::from("speed_setting".to_string()),
            (3, 14) => Field::from("dist_setting".to_string()),
            (3, 16) => Field::from("power_setting".to_string()),
            (3, 17) => Field::from("activity_class".to_string()),
            (3, 18) => Field::from("position_setting".to_string()),
            (3, 21) => Field::from("temperature_setting".to_string()),
            (3, 22) => Field::from("local_id".to_string()),
            (3, 23) => Field::from("global_id".to_string()),
            (3, 28) => Field::from("wake_time".to_string()),
            (3, 29) => Field::from("sleep_time".to_string()),
            (3, 30) => Field::from("height_setting".to_string()),
            (3, 31) => Field::from("user_running_step_length".to_string()),
            (3, 32) => Field::from("user_walking_step_length".to_string()),
            (3, 47) => Field::from("depth_setting".to_string()),
            (3, 49) => Field::from("dive_count".to_string()),
            // hrm profile (4)
            (4, 254) => Field::from("message_index".to_string()),
            (4, 0) => Field::from("enabled".to_string()),
            (4, 1) => Field::from("hrm_ant_id".to_string()),
            (4, 2) => Field::from("log_hrv".to_string()),
            (4, 3) => Field::from("hrm_ant_id_trans_type".to_string()),
            // sdm profile (5)
            (5, 254) => Field::from("message_index".to_string()),
            (5, 0) => Field::from("enabled".to_string()),
            (5, 1) => Field::from("sdm_ant_id".to_string()),
            (5, 2) => Field::from("sdm_cal_factor".to_string()),
            (5, 3) => Field::from("odometer".to_string()),
            (5, 4) => Field::from("speed_source".to_string()),
            (5, 5) => Field::from("sdm_ant_id_trans_type".to_string()),
            (5, 7) => Field::from("odometer_rollover".to_string()),
            // bike profile (6)
            (6, 254) => Field::from("message_index".to_string()),
            (6, 0) => Field::from("name".to_string()),
            (6, 1) => Field::from("sport".to_string()),
            (6, 2) => Field::from("sub_sport".to_string()),
            (6, 3) => Field::from("odometer".to_string()),
            (6, 4) => Field::from("bike_spd_ant_id".to_string()),
            (6, 5) => Field::from("bike_cad_ant_id".to_string()),
            (6, 6) => Field::from("bike_spdcad_ant_id".to_string()),
            (6, 7) => Field::from("bike_power_ant_id".to_string()),
            (6, 8) => Field::from("custom_wheelsize".to_string()),
            (6, 9) => Field::from("auto_wheelsize".to_string()),
            (6, 10) => Field::from("bike_weight".to_string()),
            (6, 11) => Field::from("power_cal_factor".to_string()),
            (6, 12) => Field::from("auto_wheel_cal".to_string()),
            (6, 13) => Field::from("auto_power_zero".to_string()),
            (6, 14) => Field::from("id".to_string()),
            (6, 15) => Field::from("spd_enabled".to_string()),
            (6, 16) => Field::from("cad_enabled".to_string()),
            (6, 17) => Field::from("spdcad_enabled".to_string()),
            (6, 18) => Field::from("power_enabled".to_string()),
            (6, 19) => Field::from("crank_length".to_string()),
            (6, 20) => Field::from("enabled".to_string()),
            (6, 21) => Field::from("bike_spd_ant_id_trans_type".to_string()),
            (6, 22) => Field::from("bike_cad_ant_id_trans_type".to_string()),
            (6, 23) => Field::from("bike_spdcad_ant_id_trans_type".to_string()),
            (6, 24) => Field::from("bike_power_ant_id_trans_type".to_string()),
            (6, 37) => Field::from("odometer_rollover".to_string()),
            (6, 38) => Field::from("front_gear_num".to_string()),
            (6, 39) => Field::from("front_gear".to_string()),
            (6, 40) => Field::from("rear_gear_num".to_string()),
            (6, 41) => Field::from("rear_gear".to_string()),
            (6, 44) => Field::from("shimano_di2_enabled".to_string()),
            // connectivity (127)
            (127, 0) => Field::from("bluetooth_enabled".to_string()),
            (127, 1) => Field::from("bluetooth_le_enabled".to_string()),
            (127, 2) => Field::from("ant_enabled".to_string()),
            (127, 3) => Field::from("name".to_string()),
            (127, 4) => Field::from("live_tracking_enabled".to_string()),
            (127, 5) => Field::from("weather_conditions_enabled".to_string()),
            (127, 6) => Field::from("weather_alerts_enabled".to_string()),
            (127, 7) => Field::from("auto_activity_upload_enabled".to_string()),
            (127, 8) => Field::from("course_download_enabled".to_string()),
            (127, 9) => Field::from("workout_download_enabled".to_string()),
            (127, 10) => Field::from("gps_ephemeris_download_enabled".to_string()),
            (127, 11) => Field::from("incident_detection_enabled".to_string()),
            (127, 12) => Field::from("grouptrack_enabled".to_string()),
            // watchface settings (159)
            (159, 254) => Field::from("message_index".to_string()),
            (159, 0) => Field::from("mode".to_string()),
            (159, 1) => Field::from("layout".to_string()),
            // ohr settings (188)
            (188, 253) => Field::from("timestamp".to_string()),
            (188, 0) => Field::from("enabled".to_string()),
            // time in zone (216)
            (216, 253) => Field::from("timestamp".to_string()),
            (216, 0) => Field::from("reference_mesg".to_string()),
            (216, 1) => Field::from("reference_index".to_string()),
            (216, 2) => Field::from("time_in_hr_zone".to_string()),
            (216, 3) => Field::from("time_in_speed_zone".to_string()),
            (216, 4) => Field::from("time_in_cadence_zone".to_string()),
            (216, 5) => Field::from("time_in_power_zone".to_string()),
            (216, 6) => Field::from("hr_zone_high_boundary".to_string()),
            (216, 7) => Field::from("speed_zone_high_boundary".to_string()),
            (216, 8) => Field::from("cadence_zone_high_bondary".to_string()),
            (216, 9) => Field::from("power_zone_high_boundary".to_string()),
            (216, 10) => Field::from("hr_calc_type".to_string()),
            (216, 11) => Field::from("max_heart_rate".to_string()),
            (216, 12) => Field::from("resting_heart_rate".to_string()),
            (216, 13) => Field::from("threshold_heart_rate".to_string()),
            (216, 14) => Field::from("pwr_calc_type".to_string()),
            (216, 15) => Field::from("functional_threshold_power".to_string()),
            // <start sport settings file> todo incomplete
            // zones target (7)
            (7, 1) => Field::from("max_heart_rate".to_string()),
            (7, 2) => Field::from("threshold_heart_rate".to_string()),
            (7, 3) => Field::from("functional_threshold_power".to_string()),
            (7, 5) => Field::from("hr_calc_type".to_string()),
            (7, 7) => Field::from("pwr_calc_type".to_string()),
            // sport (12)
            (12, 0) => Field::from("Sport".to_string()),
            (12, 1) => Field::from("Sub-sport".to_string()),
            (12, 3) => Field::from("Sport name".to_string()),
            // <end sport settings file>
            // <start totals file messages>
            // totals (33)
            (33, 254) => Field::from("Totals message index".to_string()),
            (33, 253) => Field::from("Totals timestamp".to_string()),
            (33, 0) => Field::from("Totals timer time".to_string()),
            (33, 1) => Field::from("Totals distance".to_string()),
            (33, 2) => Field::from("Totals calories".to_string()),
            (33, 3) => Field::from("Totals sport".to_string()),
            (33, 4) => Field::from("Totals elapsed time".to_string()),
            (33, 5) => Field::from("Totals sessions".to_string()),
            (33, 6) => Field::from("Totals active time".to_string()),
            (33, 9) => Field::from("Totals sport".to_string()),
            // <end totals file messages>
            // <start activity file messages>
            // activity (34)
            (34, 253) => Field::from("Activity timestamp".to_string()),
            (34, 0) => Field::from("Activity total timer time".to_string()),
            (34, 1) => Field::from("Activity number of session".to_string()),
            (34, 2) => Field::from_with_converter("Activity type".to_string(), |_, value| -> String {
                match value {
                    0 => { "manual sport".to_string() }
                    1 => { "automatic sport".to_string() }
                    &_ => { "Unknown activity".to_string() }
                }
            }),
            (34, 3) => Field::from_with_converter("Activity event".to_string(), |_, value: &u8| -> String {
                Event::resolve(&value).to_string()
            }),
            (34, 4) => Field::from_with_converter("Activity event type".to_string(), |_, value: &u8| -> String {
                EventType::resolve(&value).to_string()
            }),
            (34, 5) => Field::from("Activity local timestamp".to_string()),
            (34, 6) => Field::from("Activity event group".to_string()),
            // session (18)
            (18, 254) => Field::from("message_index".to_string()),
            (18, 253) => Field::from("timestamp".to_string()),
            (18, 0) => Field::from("event".to_string()),
            (18, 1) => Field::from("event_type".to_string()),
            (18, 2) => Field::from("start_time".to_string()),
            (18, 3) => Field::from("start_position_lat".to_string()),
            (18, 4) => Field::from("start_position_long".to_string()),
            (18, 5) => Field::from("sport".to_string()),
            (18, 6) => Field::from("sub_sport".to_string()),
            (18, 7) => Field::from("total_elapsed_time".to_string()),
            (18, 8) => Field::from("total_timer_time".to_string()),
            (18, 9) => Field::from("total_distance".to_string()),
            (18, 10) => Field::from("total_cycles".to_string()),
            (18, 11) => Field::from("total_calories".to_string()),
            (18, 13) => Field::from("total_fat_calories".to_string()),
            (18, 14) => Field::from("avg_speed".to_string()),
            (18, 15) => Field::from("max_speed".to_string()),
            (18, 16) => Field::from("avg_heart_rate".to_string()),
            (18, 17) => Field::from("max_heart_rate".to_string()),
            (18, 18) => Field::from("avg_cadence".to_string()),
            (18, 19) => Field::from("max_cadence".to_string()),
            (18, 20) => Field::from("avg_power".to_string()),
            (18, 21) => Field::from("max_power".to_string()),
            (18, 22) => Field::from("total_ascent".to_string()),
            (18, 23) => Field::from("total_descent".to_string()),
            (18, 24) => Field::from("total_training_effect".to_string()),
            (18, 25) => Field::from("first_lap_index".to_string()),
            (18, 26) => Field::from("num_laps".to_string()),
            (18, 27) => Field::from("event_group".to_string()),
            (18, 28) => Field::from("trigger".to_string()),
            (18, 29) => Field::from("nec_lat".to_string()),
            (18, 30) => Field::from("nec_long".to_string()),
            (18, 31) => Field::from("swc_lat".to_string()),
            (18, 32) => Field::from("swc_long".to_string()),
            (18, 33) => Field::from("num_lengths".to_string()),
            (18, 34) => Field::from("normalized_power".to_string()),
            (18, 35) => Field::from("training_stress_score".to_string()),
            (18, 36) => Field::from("intensity_factor".to_string()),
            (18, 37) => Field::from("left_right_balance".to_string()),
            (18, 38) => Field::from("end_position_lat".to_string()),
            (18, 39) => Field::from("end_position_long".to_string()),
            (18, 41) => Field::from("avg_stroke_count".to_string()),
            (18, 42) => Field::from("avg_stroke_distance".to_string()),
            (18, 43) => Field::from("swim_stroke".to_string()),
            (18, 44) => Field::from("pool_length".to_string()),
            (18, 45) => Field::from("threshold_power".to_string()),
            (18, 46) => Field::from("pool_length_unit".to_string()),
            (18, 47) => Field::from("num_active_lengths".to_string()),
            (18, 48) => Field::from("total_work".to_string()),
            (18, 49) => Field::from("avg_altitude".to_string()),
            (18, 50) => Field::from("max_altitude".to_string()),
            (18, 51) => Field::from("gps_accuracy".to_string()),
            (18, 52) => Field::from("avg_grade".to_string()),
            (18, 53) => Field::from("avg_pos_grade".to_string()),
            (18, 54) => Field::from("avg_neg_grade".to_string()),
            (18, 55) => Field::from("max_pos_grade".to_string()),
            (18, 56) => Field::from("max_neg_grade".to_string()),
            (18, 57) => Field::from("avg_temperature".to_string()),
            (18, 58) => Field::from("max_temperature".to_string()),
            (18, 59) => Field::from("total_moving_time".to_string()),
            (18, 60) => Field::from("avg_pos_vertical_speed".to_string()),
            (18, 61) => Field::from("avg_neg_vertical_speed".to_string()),
            (18, 62) => Field::from("max_pos_vertical_speed".to_string()),
            (18, 63) => Field::from("max_neg_vertical_speed".to_string()),
            (18, 64) => Field::from("min_heart_rate".to_string()),
            (18, 65) => Field::from("time_in_hr_zone".to_string()),
            (18, 66) => Field::from("time_in_speed_zone".to_string()),
            (18, 67) => Field::from("time_in_cadence_zone".to_string()),
            (18, 68) => Field::from("time_in_power_zone".to_string()),
            (18, 69) => Field::from("avg_lap_time".to_string()),
            (18, 70) => Field::from("best_lap_index".to_string()),
            (18, 71) => Field::from("min_altitude".to_string()),
            (18, 82) => Field::from("player_score".to_string()),
            (18, 83) => Field::from("opponent_score".to_string()),
            (18, 84) => Field::from("opponent_name".to_string()),
            (18, 85) => Field::from("stroke_count".to_string()),
            (18, 86) => Field::from("zone_count".to_string()),
            (18, 87) => Field::from("max_ball_speed".to_string()),
            (18, 88) => Field::from("avg_ball_speed".to_string()),
            (18, 89) => Field::from("avg_vertical_oscillation".to_string()),
            (18, 90) => Field::from("avg_stance_time_percent".to_string()),
            (18, 91) => Field::from("avg_stance_time".to_string()),
            (18, 92) => Field::from("avg_fractional_cadence".to_string()),
            (18, 93) => Field::from("max_fractional_cadence".to_string()),
            (18, 94) => Field::from("total_fractional_cycles".to_string()),
            (18, 95) => Field::from("avg_total_hemoglobin_conc".to_string()),
            (18, 96) => Field::from("min_total_hemoglobin_conc".to_string()),
            (18, 97) => Field::from("max_total_hemoglobin_conc".to_string()),
            (18, 98) => Field::from("avg_saturated_hemoglobin_percent".to_string()),
            (18, 99) => Field::from("min_saturated_hemoglobin_percent".to_string()),
            (18, 100) => Field::from("max_saturated_hemoglobin_percent".to_string()),
            (18, 101) => Field::from("avg_left_torque_effectiveness".to_string()),
            (18, 102) => Field::from("avg_right_torque_effectiveness".to_string()),
            (18, 103) => Field::from("avg_left_pedal_smoothness".to_string()),
            (18, 104) => Field::from("avg_right_pedal_smoothness".to_string()),
            (18, 105) => Field::from("avg_combined_pedal_smoothness".to_string()),
            (18, 110) => Field::from("sport_profile_name".to_string()),
            (18, 111) => Field::from("sport_index".to_string()),
            (18, 112) => Field::from("time_standing".to_string()),
            (18, 113) => Field::from("stand_count".to_string()),
            (18, 114) => Field::from("avg_left_pco".to_string()),
            (18, 115) => Field::from("avg_right_pco".to_string()),
            (18, 116) => Field::from("avg_left_power_phase".to_string()),
            (18, 117) => Field::from("avg_left_power_phase_peak".to_string()),
            (18, 118) => Field::from("avg_right_power_phase".to_string()),
            (18, 119) => Field::from("avg_right_power_phase_peak".to_string()),
            (18, 120) => Field::from("avg_power_position".to_string()),
            (18, 121) => Field::from("max_power_position".to_string()),
            (18, 122) => Field::from("avg_cadence_position".to_string()),
            (18, 123) => Field::from("max_cadence_position".to_string()),
            (18, 124) => Field::from("enhanced_avg_speed".to_string()),
            (18, 125) => Field::from("enhanced_max_speed".to_string()),
            (18, 126) => Field::from("enhanced_avg_altitude".to_string()),
            (18, 127) => Field::from("enhanced_min_altitude".to_string()),
            (18, 128) => Field::from("enhanced_max_altitude".to_string()),
            (18, 129) => Field::from("avg_lev_motor_power".to_string()),
            (18, 130) => Field::from("max_lev_motor_power".to_string()),
            (18, 131) => Field::from("lev_battery_consumption".to_string()),
            (18, 132) => Field::from("avg_vertical_ratio".to_string()),
            (18, 133) => Field::from("avg_stance_time_balance".to_string()),
            (18, 134) => Field::from("avg_step_length".to_string()),
            (18, 137) => Field::from("total_anaerobic_training_effect".to_string()),
            (18, 139) => Field::from("avg_vam".to_string()),
            (18, 140) => Field::from("avg_depth".to_string()),
            (18, 141) => Field::from("max_depth".to_string()),
            (18, 142) => Field::from("surface_interval".to_string()),
            (18, 143) => Field::from("start_cns".to_string()),
            (18, 144) => Field::from("end_cns".to_string()),
            (18, 145) => Field::from("start_n2".to_string()),
            (18, 146) => Field::from("end_n2".to_string()),
            (18, 147) => Field::from("avg_respiration_rate".to_string()),
            (18, 148) => Field::from("max_respiration_rate".to_string()),
            (18, 149) => Field::from("min_respiration_rate".to_string()),
            (18, 150) => Field::from("min_temperature".to_string()),
            (18, 155) => Field::from("o2_toxicity".to_string()),
            (18, 156) => Field::from("dive_number".to_string()),
            (18, 168) => Field::from("training_load_peak".to_string()),
            (18, 169) => Field::from("enhanced_avg_respiration_rate".to_string()),
            (18, 170) => Field::from("enhanced_max_respiration_rate".to_string()),
            (18, 180) => Field::from("enhanced_min_respiration_rate".to_string()),
            (18, 181) => Field::from("total_grit".to_string()),
            (18, 182) => Field::from("total_flow".to_string()),
            (18, 183) => Field::from("jump_count".to_string()),
            (18, 186) => Field::from("avg_grit".to_string()),
            (18, 187) => Field::from("avg_flow".to_string()),
            (18, 194) => Field::from("avg_spo2".to_string()),
            (18, 195) => Field::from("avg_stress".to_string()),
            (18, 197) => Field::from("sdrr_hrv".to_string()),
            (18, 198) => Field::from("rmssd_hrv".to_string()),
            (18, 199) => Field::from("total_fractional_ascent".to_string()),
            (18, 200) => Field::from("total_fractional_descent".to_string()),
            (18, 208) => Field::from("avg_core_temperature".to_string()),
            (18, 209) => Field::from("min_core_temperature".to_string()),
            (18, 210) => Field::from("max_core_temperature".to_string()),
            // lap (19)
            (10, 254) => Field::from("message_index".to_string()),
            (10, 253) => Field::from("timestamp".to_string()),
            (10, 0) => Field::from("event".to_string()),
            (10, 1) => Field::from("event_type".to_string()),
            (10, 2) => Field::from("start_time".to_string()),
            (10, 3) => Field::from("start_position_lat".to_string()),
            (10, 4) => Field::from("start_position_long".to_string()),
            (10, 5) => Field::from("end_position_lat".to_string()),
            (10, 6) => Field::from("end_position_long".to_string()),
            (10, 7) => Field::from("total_elapsed_time".to_string()),
            (10, 8) => Field::from("total_timer_time".to_string()),
            (10, 9) => Field::from("total_distance".to_string()),
            (10, 10) => Field::from("total_cycles".to_string()),
            (10, 11) => Field::from("total_calories".to_string()),
            (10, 12) => Field::from("total_fat_calories".to_string()),
            (10, 13) => Field::from("avg_speed".to_string()),
            (10, 14) => Field::from("max_speed".to_string()),
            (10, 15) => Field::from("avg_heart_rate".to_string()),
            (10, 16) => Field::from("max_heart_rate".to_string()),
            (10, 17) => Field::from("avg_cadence".to_string()),
            (10, 18) => Field::from("max_cadence".to_string()),
            (10, 19) => Field::from("avg_power".to_string()),
            (10, 20) => Field::from("max_power".to_string()),
            (10, 21) => Field::from("total_ascent".to_string()),
            (10, 22) => Field::from("total_descent".to_string()),
            (10, 23) => Field::from("intensity".to_string()),
            (10, 24) => Field::from("lap_trigger".to_string()),
            (10, 25) => Field::from("sport".to_string()),
            (10, 26) => Field::from("event_group".to_string()),
            (10, 32) => Field::from("num_lengths".to_string()),
            (10, 33) => Field::from("normalized_power".to_string()),
            (10, 34) => Field::from("left_right_balance".to_string()),
            (10, 35) => Field::from("first_length_index".to_string()),
            (10, 37) => Field::from("avg_stroke_distance".to_string()),
            (10, 38) => Field::from("swim_stroke".to_string()),
            (10, 39) => Field::from("sub_sport".to_string()),
            (10, 40) => Field::from("num_active_lengths".to_string()),
            (10, 41) => Field::from("total_work".to_string()),
            (10, 42) => Field::from("avg_altitude".to_string()),
            (10, 43) => Field::from("max_altitude".to_string()),
            (10, 44) => Field::from("gps_accuracy".to_string()),
            (10, 45) => Field::from("avg_grade".to_string()),
            (10, 46) => Field::from("avg_pos_grade".to_string()),
            (10, 47) => Field::from("avg_neg_grade".to_string()),
            (10, 48) => Field::from("max_pos_grade".to_string()),
            (10, 49) => Field::from("max_neg_grade".to_string()),
            (10, 50) => Field::from("avg_temperature".to_string()),
            (10, 51) => Field::from("max_temperature".to_string()),
            (10, 52) => Field::from("total_moving_time".to_string()),
            (10, 53) => Field::from("avg_pos_vertical_speed".to_string()),
            (10, 54) => Field::from("avg_neg_vertical_speed".to_string()),
            (10, 55) => Field::from("max_pos_vertical_speed".to_string()),
            (10, 56) => Field::from("max_neg_vertical_speed".to_string()),
            (10, 57) => Field::from("time_in_hr_zone".to_string()),
            (10, 58) => Field::from("time_in_speed_zone".to_string()),
            (10, 59) => Field::from("time_in_cadence_zone".to_string()),
            (10, 60) => Field::from("time_in_power_zone".to_string()),
            (10, 61) => Field::from("repetition_num".to_string()),
            (10, 62) => Field::from("min_altitude".to_string()),
            (10, 63) => Field::from("min_heart_rate".to_string()),
            (10, 71) => Field::from("wkt_step_index".to_string()),
            (10, 74) => Field::from("opponent_score".to_string()),
            (10, 75) => Field::from("stroke_count".to_string()),
            (10, 76) => Field::from("zone_count".to_string()),
            (10, 77) => Field::from("avg_vertical_oscillation".to_string()),
            (10, 78) => Field::from("avg_stance_time_percent".to_string()),
            (10, 79) => Field::from("avg_stance_time".to_string()),
            (10, 80) => Field::from("avg_fractional_cadence".to_string()),
            (10, 81) => Field::from("max_fractional_cadence".to_string()),
            (10, 82) => Field::from("total_fractional_cycles".to_string()),
            (10, 83) => Field::from("player_score".to_string()),
            (10, 84) => Field::from("avg_total_hemoglobin_conc".to_string()),
            (10, 85) => Field::from("min_total_hemoglobin_conc".to_string()),
            (10, 86) => Field::from("max_total_hemoglobin_conc".to_string()),
            (10, 87) => Field::from("avg_saturated_hemoglobin_percent".to_string()),
            (10, 88) => Field::from("min_saturated_hemoglobin_percent".to_string()),
            (10, 89) => Field::from("max_saturated_hemoglobin_percent".to_string()),
            (10, 91) => Field::from("avg_left_torque_effectiveness".to_string()),
            (10, 92) => Field::from("avg_right_torque_effectiveness".to_string()),
            (10, 93) => Field::from("avg_left_pedal_smoothness".to_string()),
            (10, 94) => Field::from("avg_right_pedal_smoothness".to_string()),
            (10, 95) => Field::from("avg_combined_pedal_smoothness".to_string()),
            (10, 98) => Field::from("time_standing".to_string()),
            (10, 99) => Field::from("stand_count".to_string()),
            (10, 100) => Field::from("avg_left_pco".to_string()),
            (10, 101) => Field::from("avg_right_pco".to_string()),
            (10, 102) => Field::from("avg_left_power_phase".to_string()),
            (10, 103) => Field::from("avg_left_power_phase_peak".to_string()),
            (10, 104) => Field::from("avg_right_power_phase".to_string()),
            (10, 105) => Field::from("avg_right_power_phase_peak".to_string()),
            (10, 106) => Field::from("avg_power_position".to_string()),
            (10, 107) => Field::from("max_power_position".to_string()),
            (10, 108) => Field::from("avg_cadence_position".to_string()),
            (10, 109) => Field::from("max_cadence_position".to_string()),
            (10, 110) => Field::from("enhanced_avg_speed".to_string()),
            (10, 111) => Field::from("enhanced_max_speed".to_string()),
            (10, 112) => Field::from("enhanced_avg_altitude".to_string()),
            (10, 113) => Field::from("enhanced_min_altitude".to_string()),
            (10, 114) => Field::from("enhanced_max_altitude".to_string()),
            (10, 115) => Field::from("avg_lev_motor_power".to_string()),
            (10, 116) => Field::from("max_lev_motor_power".to_string()),
            (10, 117) => Field::from("lev_battery_consumption".to_string()),
            (10, 118) => Field::from("avg_vertical_ratio".to_string()),
            (10, 119) => Field::from("avg_stance_time_balance".to_string()),
            (10, 120) => Field::from("avg_step_length".to_string()),
            (10, 121) => Field::from("avg_vam".to_string()),
            (10, 122) => Field::from("avg_depth".to_string()),
            (10, 123) => Field::from("max_depth".to_string()),
            (10, 124) => Field::from("min_temperature".to_string()),
            (10, 136) => Field::from("enhanced_avg_respiration_rate".to_string()),
            (10, 137) => Field::from("enhanced_max_respiration_rate".to_string()),
            (10, 147) => Field::from("avg_respiration_rate".to_string()),
            (10, 148) => Field::from("max_respiration_rate".to_string()),
            (10, 149) => Field::from("total_grit".to_string()),
            (10, 150) => Field::from("total_flow".to_string()),
            (10, 151) => Field::from("jump_count".to_string()),
            (10, 153) => Field::from("avg_grit".to_string()),
            (10, 154) => Field::from("avg_flow".to_string()),
            (10, 156) => Field::from("total_fractional_ascent".to_string()),
            (10, 157) => Field::from("total_fractional_descent".to_string()),
            (10, 158) => Field::from("avg_core_temperature".to_string()),
            (10, 159) => Field::from("min_core_temperature".to_string()),
            (10, 160) => Field::from("max_core_temperature".to_string()),
            // length (101)
            (101, 254) => Field::from("message_index".to_string()),
            (101, 253) => Field::from("timestamp".to_string()),
            (101, 0) => Field::from("event".to_string()),
            (101, 1) => Field::from("event_type".to_string()),
            (101, 2) => Field::from("start_time".to_string()),
            (101, 3) => Field::from("total_elapsed_time".to_string()),
            (101, 4) => Field::from("total_timer_time".to_string()),
            (101, 5) => Field::from("total_strokes".to_string()),
            (101, 6) => Field::from("avg_speed".to_string()),
            (101, 7) => Field::from("swim_stroke".to_string()),
            (101, 9) => Field::from("avg_swimming_cadence".to_string()),
            (101, 10) => Field::from("event_group".to_string()),
            (101, 11) => Field::from("total_calories".to_string()),
            (101, 12) => Field::from("length_type".to_string()),
            (101, 18) => Field::from("player_score".to_string()),
            (101, 19) => Field::from("opponent_score".to_string()),
            (101, 20) => Field::from("stroke_count".to_string()),
            (101, 21) => Field::from("zone_count".to_string()),
            (101, 22) => Field::from("enhanced_avg_respiration_rate".to_string()),
            (101, 23) => Field::from("enhanced_max_respiration_rate".to_string()),
            (101, 24) => Field::from("avg_respiration_rate".to_string()),
            (101, 25) => Field::from("max_respiration_rate".to_string()),
            // record (20)
            (20, 0) => Field::from("Position latitude".to_string()), // semicircles / 11930465
            (20, 1) => Field::from("Position longitude".to_string()), // semicircles / 11930465
            (20, 2) => Field::from("Altitude".to_string()),
            (20, 3) => Field::from("Heart rate".to_string()),
            (20, 4) => Field::from("CADENCE".to_string()),
            (20, 5) => Field::from("Distance".to_string()),
            (20, 6) => Field::from("SPEED".to_string()),
            (20, 7) => Field::from("POWER".to_string()),
            (20, 8) => Field::from("COMPRESSED_SPEED_DISTANCE".to_string()),
            (20, 9) => Field::from("GRADE".to_string()),
            (20, 10) => Field::from("RESISTANCE".to_string()),
            (20, 11) => Field::from("TIME_FROM_COURSE".to_string()),
            (20, 12) => Field::from("CYCLE_LENGTH".to_string()),
            (20, 13) => Field::from("Temperature".to_string()),
            (20, 17) => Field::from("SPEED_1S".to_string()),
            (20, 18) => Field::from("CYCLES".to_string()),
            (20, 19) => Field::from("TOTAL_CYCLES".to_string()),
            (20, 28) => Field::from("COMPRESSED_ACCUMULATED_POWER".to_string()),
            (20, 29) => Field::from("ACCUMULATED_POWER".to_string()),
            (20, 30) => Field::from("LEFT_RIGHT_BALANCE".to_string()),
            (20, 31) => Field::from("GPS_ACCURACY".to_string()),
            (20, 32) => Field::from("VERTICAL_SPEED".to_string()),
            (20, 33) => Field::from("CALORIES".to_string()),
            (20, 39) => Field::from("VERTICAL_OSCILLATION".to_string()),
            (20, 40) => Field::from("STANCE_TIME_PERCENT".to_string()),
            (20, 41) => Field::from("STANCE_TIME".to_string()),
            (20, 42) => Field::from("ACTIVITY_TYPE".to_string()),
            (20, 43) => Field::from("LEFT_TORQUE_EFFECTIVENESS".to_string()),
            (20, 44) => Field::from("RIGHT_TORQUE_EFFECTIVENESS".to_string()),
            (20, 45) => Field::from("LEFT_PEDAL_SMOOTHNESS".to_string()),
            (20, 46) => Field::from("RIGHT_PEDAL_SMOOTHNESS".to_string()),
            (20, 47) => Field::from("COMBINED_PEDAL_SMOOTHNESS".to_string()),
            (20, 48) => Field::from("TIME128".to_string()),
            (20, 49) => Field::from("STROKE_TYPE".to_string()),
            (20, 50) => Field::from("ZONE".to_string()),
            (20, 51) => Field::from("BALL_SPEED".to_string()),
            (20, 52) => Field::from("CADENCE256".to_string()),
            (20, 53) => Field::from("FRACTIONAL_CADENCE".to_string()),
            (20, 54) => Field::from("TOTAL_HEMOGLOBIN_CONC".to_string()),
            (20, 55) => Field::from("TOTAL_HEMOGLOBIN_CONC_MIN".to_string()),
            (20, 56) => Field::from("TOTAL_HEMOGLOBIN_CONC_MAX".to_string()),
            (20, 57) => Field::from("SATURATED_HEMOGLOBIN_PERCENT".to_string()),
            (20, 58) => Field::from("SATURATED_HEMOGLOBIN_PERCENT_MIN".to_string()),
            (20, 59) => Field::from("SATURATED_HEMOGLOBIN_PERCENT_MAX".to_string()),
            (20, 62) => Field::from("DEVICE_INDEX".to_string()),
            (20, 67) => Field::from("LEFT_PCO".to_string()),
            (20, 68) => Field::from("RIGHT_PCO".to_string()),
            (20, 69) => Field::from("LEFT_POWER_PHASE".to_string()),
            (20, 70) => Field::from("LEFT_POWER_PHASE_PEAK".to_string()),
            (20, 71) => Field::from("RIGHT_POWER_PHASE".to_string()),
            (20, 20) => Field::from("RIGHT_POWER_PHASE_PEAK".to_string()),
            (20, 73) => Field::from("ENHANCED_SPEED".to_string()),
            (20, 78) => Field::from("ENHANCED_ALTITUDE".to_string()),
            (20, 81) => Field::from("BATTERY_SOC".to_string()),
            (20, 82) => Field::from("MOTOR_POWER".to_string()),
            (20, 83) => Field::from("VERTICAL_RATIO".to_string()),
            (20, 84) => Field::from("STANCE_TIME_BALANCE".to_string()),
            (20, 85) => Field::from("STEP_LENGTH".to_string()),
            (20, 87) => Field::from("CYCLE_LENGTH16".to_string()),
            (20, 91) => Field::from("ABSOLUTE_PRESSURE".to_string()),
            (20, 92) => Field::from("DEPTH".to_string()),
            (20, 93) => Field::from("NEXT_STOP_DEPTH".to_string()),
            (20, 94) => Field::from("NEXT_STOP_TIME".to_string()),
            (20, 95) => Field::from("TIME_TO_SURFACE".to_string()),
            (20, 96) => Field::from("NDL_TIME".to_string()),
            (20, 97) => Field::from("CNS_LOAD".to_string()),
            (20, 98) => Field::from("N2_LOAD".to_string()),
            (20, 99) => Field::from("RESPIRATION_RATE".to_string()),
            (20, 108) => Field::from("ENHANCED_RESPIRATION_RATE".to_string()),
            (20, 114) => Field::from("GRIT".to_string()),
            (20, 115) => Field::from("FLOW".to_string()),
            (20, 116) => Field::from("CURRENT_STRESS".to_string()),
            (20, 117) => Field::from("EBIKE_TRAVEL_RANGE".to_string()),
            (20, 118) => Field::from("EBIKE_BATTERY_LEVEL".to_string()),
            (20, 119) => Field::from("EBIKE_ASSIST_MODE".to_string()),
            (20, 120) => Field::from("EBIKE_ASSIST_LEVEL_PERCENT".to_string()),
            (20, 123) => Field::from("AIR_TIME_REMAINING".to_string()),
            (20, 124) => Field::from("PRESSURE_SAC".to_string()),
            (20, 125) => Field::from("VOLUME_SAC".to_string()),
            (20, 126) => Field::from("RMV".to_string()),
            (20, 127) => Field::from("ASCENT_RATE".to_string()),
            (20, 129) => Field::from("PO2".to_string()),
            (20, 139) => Field::from("CORE_TEMPERATURE".to_string()),
            (20, 253) => Field::from("Timestamp".to_string()),
            // event (21)
            (21, 253) => Field::from("timestamp".to_string()),
            (21, 0) => Field::from_with_converter("event".to_string(), |_, value: &u8| -> String {
                Event::resolve(&value).to_string()
            }),
            (21, 1) => Field::from_with_converter("event_type".to_string(), |_, value: &u8| -> String {
                EventType::resolve(&value).to_string()
            }),
            (21, 2) => Field::from("data16".to_string()),
            (21, 3) => Field::from("data".to_string()),
            (21, 4) => Field::from("event_group".to_string()),
            (21, 7) => Field::from("score".to_string()),
            (21, 8) => Field::from("opponent_score".to_string()),
            (21, 9) => Field::from("front_gear_num".to_string()),
            (21, 10) => Field::from("front_gear".to_string()),
            (21, 11) => Field::from("rear_gear_num".to_string()),
            (21, 12) => Field::from("rear_gear".to_string()),
            (21, 13) => Field::from("device_index".to_string()),
            (21, 14) => Field::from("activity_type".to_string()),
            (21, 15) => Field::from("start_timestamp".to_string()),
            (21, 21) => Field::from("radar_threat_level_max".to_string()),
            (21, 22) => Field::from("radar_threat_count".to_string()),
            (21, 23) => Field::from("radar_threat_avg_approach_speed".to_string()),
            (21, 24) => Field::from("radar_threat_max_approach_speed".to_string()),
            // device info (23)
            (23, 253) => Field::from("Device info timestamp".to_string()),
            (23, 0) => Field::from("device_index".to_string()),
            (23, 1) => Field::from("device_type".to_string()),
            (23, 2) => Field::from("manufacturer".to_string()),
            (23, 3) => Field::from("serial_number".to_string()),
            (23, 4) => Field::from("product".to_string()),
            (23, 5) => Field::from("software_version".to_string()),
            (23, 6) => Field::from("hardware_version".to_string()),
            (23, 7) => Field::from("cum_operating_time".to_string()),
            (23, 10) => Field::from("battery_voltage".to_string()),
            (23, 11) => Field::from("battery_status".to_string()),
            (23, 18) => Field::from("sensor_position".to_string()),
            (23, 19) => Field::from("descriptor".to_string()),
            (23, 20) => Field::from("ant_transmission_type".to_string()),
            (23, 21) => Field::from("ant_device_number".to_string()),
            (23, 22) => Field::from("ant_network".to_string()),
            (23, 25) => Field::from("source_type".to_string()),
            (23, 27) => Field::from("product_name".to_string()),
            (23, 32) => Field::from("battery_level".to_string()),
            // device aux battery info (375)
            (375, 253) => Field::from("timestamp".to_string()),
            (375, 0) => Field::from("device_index".to_string()),
            (375, 1) => Field::from("battery_voltage".to_string()),
            (375, 2) => Field::from("battery_status".to_string()),
            (375, 3) => Field::from("battery_identifier".to_string()),
            // training file (72)
            (72, 253) => Field::from("Training file timestamp".to_string()),
            (72, 0) => Field::from("File Type".to_string()),
            (72, 1) => Field::from("Manufacturer".to_string()),
            (72, 2) => Field::from("Product".to_string()),
            (72, 3) => Field::from("Serial number".to_string()),
            (72, 4) => Field::from("Time created".to_string()),
            // weather conditions (128)
            (128, 253) => Field::from("timestamp".to_string()),
            (128, 0) => Field::from("weather_report".to_string()),
            (128, 1) => Field::from("temperature".to_string()),
            (128, 2) => Field::from("condition".to_string()),
            (128, 3) => Field::from("wind_direction".to_string()),
            (128, 4) => Field::from("wind_speed".to_string()),
            (128, 5) => Field::from("precipitation_probability".to_string()),
            (128, 6) => Field::from("temperature_feels_like".to_string()),
            (128, 7) => Field::from("relative_humidity".to_string()),
            (128, 8) => Field::from("location".to_string()),
            (128, 9) => Field::from("observed_at_time".to_string()),
            (128, 10) => Field::from("observed_location_lat".to_string()),
            (128, 11) => Field::from("observed_location_long".to_string()),
            (128, 12) => Field::from("day_of_week".to_string()),
            (128, 13) => Field::from("high_temperature".to_string()),
            (128, 14) => Field::from("low_temperature".to_string()),
            // weather alert (129)
            (129, 253) => Field::from("timestamp".to_string()),
            (129, 0) => Field::from("report_id".to_string()),
            (129, 1) => Field::from("issue_time".to_string()),
            (129, 2) => Field::from("expire_time".to_string()),
            (129, 3) => Field::from("severity".to_string()),
            (129, 4) => Field::from("type".to_string()),
            // gps metadata (160)
            (160, 253) => Field::from("timestamp".to_string()),
            (160, 0) => Field::from("timestamp_ms".to_string()),
            (160, 1) => Field::from("position_lat".to_string()),
            (160, 2) => Field::from("position_long".to_string()),
            (160, 3) => Field::from("enhanced_altitude".to_string()),
            (160, 4) => Field::from("enhanced_speed".to_string()),
            (160, 5) => Field::from("heading".to_string()),
            (160, 6) => Field::from("utc_timestamp".to_string()),
            (160, 7) => Field::from("velocity".to_string()),
            // camera event (161)
            (161, 0) => Field::from("timestamp_ms".to_string()),
            (161, 1) => Field::from("camera_event_type".to_string()),
            (161, 2) => Field::from("camera_file_uuid".to_string()),
            // gyroscope data (164)
            (164, 0) => Field::from("timestamp_ms".to_string()),
            (164, 1) => Field::from("sample_time_offset".to_string()),
            (164, 2) => Field::from("gyro_x".to_string()),
            (164, 3) => Field::from("gyro_y".to_string()),
            (164, 4) => Field::from("gyro_z".to_string()),
            (164, 5) => Field::from("calibrated_gyro_x".to_string()),
            (164, 6) => Field::from("calibrated_gyro_y".to_string()),
            (164, 7) => Field::from("calibrated_gyro_z".to_string()),
            // accelerometer data (165)
            (165, 0) => Field::from("timestamp_ms".to_string()),
            (165, 1) => Field::from("sample_time_offset".to_string()),
            (165, 2) => Field::from("accel_x".to_string()),
            (165, 3) => Field::from("accel_y".to_string()),
            (165, 4) => Field::from("accel_z".to_string()),
            (165, 5) => Field::from("calibrated_accel_x".to_string()),
            (165, 6) => Field::from("calibrated_accel_y".to_string()),
            (165, 7) => Field::from("calibrated_accel_z".to_string()),
            (165, 8) => Field::from("compressed_calibrated_accel_x".to_string()),
            (165, 9) => Field::from("compressed_calibrated_accel_y".to_string()),
            (165, 10) => Field::from("compressed_calibrated_accel_z".to_string()),
            // magnetometer data (208)
            (208, 253) => Field::from("timestamp".to_string()),
            (208, 0) => Field::from("timestamp_ms".to_string()),
            (208, 1) => Field::from("sample_time_offset".to_string()),
            (208, 2) => Field::from("mag_x".to_string()),
            (208, 3) => Field::from("mag_y".to_string()),
            (208, 4) => Field::from("mag_z".to_string()),
            (208, 5) => Field::from("calibrated_mag_x".to_string()),
            (208, 6) => Field::from("calibrated_mag_y".to_string()),
            (208, 7) => Field::from("calibrated_mag_z".to_string()),
            // barometer data (209)
            (209, 253) => Field::from("timestamp".to_string()),
            (209, 0) => Field::from("timestamp_ms".to_string()),
            (209, 1) => Field::from("sample_time_offset".to_string()),
            (209, 2) => Field::from("baro_pres".to_string()),
            // three d sensor calibration (167)
            (167, 253) => Field::from("timestamp".to_string()),
            (167, 0) => Field::from("sensor_type".to_string()),
            (167, 1) => Field::from("calibration_factor".to_string()),
            (167, 2) => Field::from("calibration_divisor".to_string()),
            (167, 3) => Field::from("level_shift".to_string()),
            (167, 4) => Field::from("offset_cal".to_string()),
            (167, 5) => Field::from("orientation_matrix".to_string()),
            // one d sensor calibration (210)
            (210, 253) => Field::from("timestamp".to_string()),
            (210, 0) => Field::from("sensor_type".to_string()),
            (210, 1) => Field::from("calibration_factor".to_string()),
            (210, 2) => Field::from("calibration_divisor".to_string()),
            (210, 3) => Field::from("level_shift".to_string()),
            (210, 4) => Field::from("offset_cal".to_string()),
            // video frame (169)
            (169, 253) => Field::from("timestamp".to_string()),
            (169, 0) => Field::from("timestamp_ms".to_string()),
            (169, 1) => Field::from("frame_number".to_string()),
            // obd II data (174)
            (174, 253) => Field::from("timestamp".to_string()),
            (174, 0) => Field::from("timestamp_ms".to_string()),
            (174, 1) => Field::from("time_offset".to_string()),
            (174, 2) => Field::from("pid".to_string()),
            (174, 3) => Field::from("raw_data".to_string()),
            (174, 4) => Field::from("pid_data_size".to_string()),
            (174, 5) => Field::from("system_time".to_string()),
            (174, 6) => Field::from("start_timestamp".to_string()),
            (174, 7) => Field::from("start_timestamp_ms".to_string()),
            // nmea sequence (177)
            (177, 253) => Field::from("timestamp".to_string()),
            (177, 0) => Field::from("timestamp_ms".to_string()),
            (177, 1) => Field::from("sentence".to_string()),
            // aviation attitude (178)
            (178, 253) => Field::from("timestamp".to_string()),
            (178, 0) => Field::from("timestamp_ms".to_string()),
            (178, 1) => Field::from("system_time".to_string()),
            (178, 2) => Field::from("pitch".to_string()),
            (178, 3) => Field::from("roll".to_string()),
            (178, 4) => Field::from("accel_lateral".to_string()),
            (178, 5) => Field::from("accel_normal".to_string()),
            (178, 6) => Field::from("turn_rate".to_string()),
            (178, 7) => Field::from("stage".to_string()),
            (178, 8) => Field::from("attitude_stage_complete".to_string()),
            (178, 9) => Field::from("track".to_string()),
            (178, 10) => Field::from("validity".to_string()),
            // video (184)
            (184, 0) => Field::from("url".to_string()),
            (184, 1) => Field::from("hosting_provider".to_string()),
            (184, 2) => Field::from("duration".to_string()),
            // video title (185)
            (185, 254) => Field::from("message_index".to_string()),
            (185, 0) => Field::from("message_count".to_string()),
            (185, 1) => Field::from("text".to_string()),
            // video description (186)
            (186, 254) => Field::from("message_index".to_string()),
            (186, 0) => Field::from("message_count".to_string()),
            (186, 1) => Field::from("text".to_string()),
            // video clip (187)
            (187, 0) => Field::from("clip_number".to_string()),
            (187, 1) => Field::from("start_timestamp".to_string()),
            (187, 2) => Field::from("start_timestamp_ms".to_string()),
            (187, 3) => Field::from("end_timestamp".to_string()),
            (187, 4) => Field::from("end_timestamp_ms".to_string()),
            (187, 6) => Field::from("clip_start".to_string()),
            (187, 7) => Field::from("clip_end".to_string()),
            // set (225)
            (225, 254) => Field::from("timestamp".to_string()),
            (225, 0) => Field::from("duration".to_string()),
            (225, 3) => Field::from("repetitions".to_string()),
            (225, 4) => Field::from("weight".to_string()),
            (225, 5) => Field::from("set_type".to_string()),
            (225, 6) => Field::from("start_time".to_string()),
            (225, 7) => Field::from("category".to_string()),
            (225, 8) => Field::from("category_subtype".to_string()),
            (225, 9) => Field::from("weight_display_unit".to_string()),
            (225, 10) => Field::from("message_index".to_string()),
            (225, 11) => Field::from("wkt_step_index".to_string()),
            // jump (285)
            (285, 253) => Field::from("timestamp".to_string()),
            (285, 0) => Field::from("distance".to_string()),
            (285, 1) => Field::from("height".to_string()),
            (285, 2) => Field::from("rotations".to_string()),
            (285, 3) => Field::from("hang_time".to_string()),
            (285, 4) => Field::from("score".to_string()),
            (285, 5) => Field::from("position_lat".to_string()),
            (285, 6) => Field::from("position_long".to_string()),
            (285, 7) => Field::from("speed".to_string()),
            (285, 8) => Field::from("enhanced_speed".to_string()),
            // split (312)
            (312, 254) => Field::from("message_index".to_string()),
            (312, 0) => Field::from("split_type".to_string()),
            (312, 1) => Field::from("total_elapsed_time".to_string()),
            (312, 2) => Field::from("total_timer_time".to_string()),
            (312, 3) => Field::from("total_distance".to_string()),
            (312, 4) => Field::from("avg_speed".to_string()),
            (312, 9) => Field::from("start_time".to_string()),
            (312, 13) => Field::from("total_ascent".to_string()),
            (312, 14) => Field::from("total_descent".to_string()),
            (312, 21) => Field::from("start_position_lat".to_string()),
            (312, 22) => Field::from("start_position_long".to_string()),
            (312, 23) => Field::from("end_position_lat".to_string()),
            (312, 24) => Field::from("end_position_long".to_string()),
            (312, 25) => Field::from("max_speed".to_string()),
            (312, 26) => Field::from("avg_vert_speed".to_string()),
            (312, 27) => Field::from("end_time".to_string()),
            (312, 28) => Field::from("total_calories".to_string()),
            (312, 74) => Field::from("start_elevation".to_string()),
            (312, 110) => Field::from("total_moving_time".to_string()),
            // split summary (313)
            (313, 254) => Field::from("message_index".to_string()),
            (313, 0) => Field::from("split_type".to_string()),
            (313, 3) => Field::from("num_splits".to_string()),
            (313, 4) => Field::from("total_timer_time".to_string()),
            (313, 5) => Field::from("total_distance".to_string()),
            (313, 6) => Field::from("avg_speed".to_string()),
            (313, 7) => Field::from("max_speed".to_string()),
            (313, 8) => Field::from("total_ascent".to_string()),
            (313, 9) => Field::from("total_descent".to_string()),
            (313, 10) => Field::from("avg_heart_rate".to_string()),
            (313, 11) => Field::from("max_heart_rate".to_string()),
            (313, 12) => Field::from("avg_vert_speed".to_string()),
            (313, 13) => Field::from("total_calories".to_string()),
            (313, 77) => Field::from("total_moving_time".to_string()),
            // climb pro (317)
            (317, 253) => Field::from("timestamp".to_string()),
            (317, 0) => Field::from("position_lat".to_string()),
            (317, 1) => Field::from("position_long".to_string()),
            (317, 2) => Field::from("climb_pro_event".to_string()),
            (317, 3) => Field::from("climb_number".to_string()),
            (317, 4) => Field::from("climb_category".to_string()),
            (317, 5) => Field::from("current_dist".to_string()),
            // <end activity file messages>
            // audio undocumented (147)
            (147, 2) => Field::from("Audio device".to_string()),
            _ => Field::from("Unknown".to_string()),
        }
    }
}
