use crate::message_types::MessageType;
use crate::types::{Event, EventType, TimeMode};
use crate::types::{BacklightMode, FileType, Sport};

pub struct Field {
    pub name: &'static str,
    pub translate_enum: fn(&Field, &u8) -> String,
}

impl Field {
    const fn from(name: &'static str) -> Self {
        Field::from_with_converter(name, |_, value| -> String {
            format!("Cannot translate {}", value)
        })
    }
    const fn from_with_converter(
        name: &'static str,
        translate_enum: fn(&Field, &u8) -> String,
    ) -> Self {
        Field {
            name,
            translate_enum,
        }
    }

    pub fn resolve(message_type: &MessageType, i: u8) -> Field {
        // sorted by Profile.xlsx/Messages
        match (message_type.number, i) {
            // file_id (0)
            (0, 0) => Field::from_with_converter("Type", |_, value| -> String {
                FileType::resolve(value).to_string()
            }),
            (0, 1) => Field::from("Manufacturer"),
            (0, 2) => Field::from("Product"),
            (0, 3) => Field::from("Serial number"),
            (0, 4) => Field::from("Time created"),
            (0, 5) => Field::from("Number"),
            (0, 8) => Field::from("Product name"),


            // file creator (49)
            (49, 0) => Field::from("Software version"),
            (49, 1) => Field::from("Hardware version"),
            // timestamp_correlation (162)
            (162, 253) => Field::from("timestamp"),
            (162, 0) => Field::from("fractional_timestamp"),
            (162, 1) => Field::from("system_timestamp"),
            (162, 2) => Field::from("fractional_system_timestamp"),
            (162, 3) => Field::from("local_timestamp"),
            (162, 4) => Field::from("timestamp_ms"),
            (162, 5) => Field::from("system_timestamp_ms"),
            // software (35)
            (35, 254) => Field::from("message_index"),
            (35, 3) => Field::from("version"),
            (35, 5) => Field::from("part_number"),
            // slave device (106)
            (106, 0) => Field::from("manufacturer"),
            (106, 1) => Field::from("product"),
            // capabilities (1)
            (1, 0) => Field::from("Languages"),
            (1, 1) => Field::from("Sports"),
            (1, 21) => Field::from("Workouts supported"),
            (1, 23) => Field::from("Connectivity supported"),
            // file capabilities (37)
            (37, 254) => Field::from("message_index"),
            (37, 0) => Field::from("type"),
            (37, 1) => Field::from("flags"),
            (37, 2) => Field::from("directory"),
            (37, 3) => Field::from("max_count"),
            (37, 4) => Field::from("max_size"),
            // message capabilities (38)
            (38, 254) => Field::from("message_index"),
            (38, 0) => Field::from("file"),
            (38, 1) => Field::from("mesg_num"),
            (38, 2) => Field::from("count_type"),
            (38, 3) => Field::from("count"),
            // field capabilities (39)
            (39, 254) => Field::from("message_index"),
            (39, 0) => Field::from("file"),
            (39, 1) => Field::from("mesg_num"),
            (39, 2) => Field::from("field_num"),
            (39, 3) => Field::from("count"),
            // device settings (2)
            (2, 0) => Field::from("Active time zone"),
            (2, 1) => Field::from("UTC offset"),
            (2, 2) => Field::from("Time offset"),
            (2, 4) => Field::from_with_converter("Time mode", |_, value| -> String {
                TimeMode::resolve(value).to_string()
            }),
            (2, 5) => Field::from("Time zone offset"),
            (2, 12) => Field::from_with_converter("Backlight mode", |_, value| -> String {
                BacklightMode::resolve(value).to_string()
            }),
            (2, 36) => Field::from("Activity tracker enabled"),
            (2, 39) => Field::from("Clock time"),
            (2, 40) => Field::from("Pages enabled"),
            (2, 46) => Field::from("Move alert enabled"),
            (2, 47) => Field::from("Date mode"),
            (2, 55) => Field::from("Display orientation"),
            (2, 56) => Field::from("Mounting side"),
            (2, 57) => Field::from("Default page"),
            (2, 58) => Field::from("Autosync min. steps"),
            (2, 59) => Field::from("Autosync max. steps"),
            (2, 80) => Field::from("Lactate threshold autodetect enabled"),
            (2, 86) => Field::from("BLE auto upload enabled"),
            (2, 89) => Field::from("Auto sync frequency"),
            (2, 90) => Field::from("Auto activity detect"),
            (2, 94) => Field::from("Number of screens"),
            (2, 95) => Field::from("Smart notification display orientation"),
            (2, 134) => Field::from("Tap interface"),
            (2, 174) => Field::from("Tap sensitivity"),
            // user profile (3)
            (3, 254) => Field::from("message_index"),
            (3, 0) => Field::from("friendly_name"),
            (3, 1) => Field::from("gender"),
            (3, 2) => Field::from("age"),
            (3, 3) => Field::from("height"),
            (3, 4) => Field::from("weight"),
            (3, 5) => Field::from("language"),
            (3, 6) => Field::from("elev_setting"),
            (3, 7) => Field::from("weight_setting"),
            (3, 8) => Field::from("resting_heart_rate"),
            (3, 9) => Field::from("default_max_running_heart_rate"),
            (3, 10) => Field::from("default_max_biking_heart_rate"),
            (3, 11) => Field::from("default_max_heart_rate"),
            (3, 12) => Field::from("hr_setting"),
            (3, 13) => Field::from("speed_setting"),
            (3, 14) => Field::from("dist_setting"),
            (3, 16) => Field::from("power_setting"),
            (3, 17) => Field::from("activity_class"),
            (3, 18) => Field::from("position_setting"),
            (3, 21) => Field::from("temperature_setting"),
            (3, 22) => Field::from("local_id"),
            (3, 23) => Field::from("global_id"),
            (3, 28) => Field::from("wake_time"),
            (3, 29) => Field::from("sleep_time"),
            (3, 30) => Field::from("height_setting"),
            (3, 31) => Field::from("user_running_step_length"),
            (3, 32) => Field::from("user_walking_step_length"),
            (3, 47) => Field::from("depth_setting"),
            (3, 49) => Field::from("dive_count"),
            // hrm profile (4)
            (4, 254) => Field::from("message_index"),
            (4, 0) => Field::from("enabled"),
            (4, 1) => Field::from("hrm_ant_id"),
            (4, 2) => Field::from("log_hrv"),
            (4, 3) => Field::from("hrm_ant_id_trans_type"),
            // sdm profile (5)
            (5, 254) => Field::from("message_index"),
            (5, 0) => Field::from("enabled"),
            (5, 1) => Field::from("sdm_ant_id"),
            (5, 2) => Field::from("sdm_cal_factor"),
            (5, 3) => Field::from("odometer"),
            (5, 4) => Field::from("speed_source"),
            (5, 5) => Field::from("sdm_ant_id_trans_type"),
            (5, 7) => Field::from("odometer_rollover"),
            // bike profile (6)
            (6, 254) => Field::from("message_index"),
            (6, 0) => Field::from("name"),
            (6, 1) => Field::from("sport"),
            (6, 2) => Field::from("sub_sport"),
            (6, 3) => Field::from("odometer"),
            (6, 4) => Field::from("bike_spd_ant_id"),
            (6, 5) => Field::from("bike_cad_ant_id"),
            (6, 6) => Field::from("bike_spdcad_ant_id"),
            (6, 7) => Field::from("bike_power_ant_id"),
            (6, 8) => Field::from("custom_wheelsize"),
            (6, 9) => Field::from("auto_wheelsize"),
            (6, 10) => Field::from("bike_weight"),
            (6, 11) => Field::from("power_cal_factor"),
            (6, 12) => Field::from("auto_wheel_cal"),
            (6, 13) => Field::from("auto_power_zero"),
            (6, 14) => Field::from("id"),
            (6, 15) => Field::from("spd_enabled"),
            (6, 16) => Field::from("cad_enabled"),
            (6, 17) => Field::from("spdcad_enabled"),
            (6, 18) => Field::from("power_enabled"),
            (6, 19) => Field::from("crank_length"),
            (6, 20) => Field::from("enabled"),
            (6, 21) => Field::from("bike_spd_ant_id_trans_type"),
            (6, 22) => Field::from("bike_cad_ant_id_trans_type"),
            (6, 23) => Field::from("bike_spdcad_ant_id_trans_type"),
            (6, 24) => Field::from("bike_power_ant_id_trans_type"),
            (6, 37) => Field::from("odometer_rollover"),
            (6, 38) => Field::from("front_gear_num"),
            (6, 39) => Field::from("front_gear"),
            (6, 40) => Field::from("rear_gear_num"),
            (6, 41) => Field::from("rear_gear"),
            (6, 44) => Field::from("shimano_di2_enabled"),
            // connectivity (127)
            (127, 0) => Field::from("bluetooth_enabled"),
            (127, 1) => Field::from("bluetooth_le_enabled"),
            (127, 2) => Field::from("ant_enabled"),
            (127, 3) => Field::from("name"),
            (127, 4) => Field::from("live_tracking_enabled"),
            (127, 5) => Field::from("weather_conditions_enabled"),
            (127, 6) => Field::from("weather_alerts_enabled"),
            (127, 7) => Field::from("auto_activity_upload_enabled"),
            (127, 8) => Field::from("course_download_enabled"),
            (127, 9) => Field::from("workout_download_enabled"),
            (127, 10) => Field::from("gps_ephemeris_download_enabled"),
            (127, 11) => Field::from("incident_detection_enabled"),
            (127, 12) => Field::from("grouptrack_enabled"),
            // watchface settings (159)
            (159, 254) => Field::from("message_index"),
            (159, 0) => Field::from("mode"),
            (159, 1) => Field::from("layout"),
            // ohr settings (188)
            (188, 253) => Field::from("timestamp"),
            (188, 0) => Field::from("enabled"),
            // time in zone (216)
            (216, 253) => Field::from("timestamp"),
            (216, 0) => Field::from("reference_mesg"),
            (216, 1) => Field::from("reference_index"),
            (216, 2) => Field::from("time_in_hr_zone"),
            (216, 3) => Field::from("time_in_speed_zone"),
            (216, 4) => Field::from("time_in_cadence_zone"),
            (216, 5) => Field::from("time_in_power_zone"),
            (216, 6) => Field::from("hr_zone_high_boundary"),
            (216, 7) => Field::from("speed_zone_high_boundary"),
            (216, 8) => Field::from("cadence_zone_high_bondary"),
            (216, 9) => Field::from("power_zone_high_boundary"),
            (216, 10) => Field::from("hr_calc_type"),
            (216, 11) => Field::from("max_heart_rate"),
            (216, 12) => Field::from("resting_heart_rate"),
            (216, 13) => Field::from("threshold_heart_rate"),
            (216, 14) => Field::from("pwr_calc_type"),
            (216, 15) => Field::from("functional_threshold_power"),
            // <start sport settings file> todo incomplete
            // zones target (7)
            (7, 1) => Field::from("max_heart_rate"),
            (7, 2) => Field::from("threshold_heart_rate"),
            (7, 3) => Field::from("functional_threshold_power"),
            (7, 5) => Field::from("hr_calc_type"),
            (7, 7) => Field::from("pwr_calc_type"),
            // sport (12)
            (12, 0) => Field::from("Sport"),
            (12, 1) => Field::from("Sub-sport"),
            (12, 3) => Field::from("Sport name"),
            // <end sport settings file>
            // <start totals file messages>
            // totals (33)
            (33, 254) => Field::from("Totals message index"),
            (33, 253) => Field::from("Totals timestamp"),
            (33, 0) => Field::from("Totals timer time"),
            (33, 1) => Field::from("Totals distance"),
            (33, 2) => Field::from("Totals calories"),
            (33, 3) => Field::from("Totals sport"),
            (33, 4) => Field::from("Totals elapsed time"),
            (33, 5) => Field::from("Totals sessions"),
            (33, 6) => Field::from("Totals active time"),
            (33, 9) => Field::from("Totals sport"),
            // <end totals file messages>
            // <start activity file messages>
            // activity (34)
            (34, 253) => Field::from("Activity timestamp"),
            (34, 0) => Field::from("Activity total timer time"),
            (34, 1) => Field::from("Activity number of session"),
            (34, 2) => Field::from_with_converter("Activity type", |_, value| -> String {
                match value {
                    0 => { "manual sport".to_string() }
                    1 => { "automatic sport".to_string() }
                    &_ => { "Unknown activity".to_string() }
                }
            }),
            (34, 3) => Field::from_with_converter("Activity event", |_, value: &u8| -> String {
                Event::resolve(&value).to_string()
            }),
            (34, 4) => Field::from_with_converter("Activity event type", |_, value: &u8| -> String {
                EventType::resolve(&value).to_string()
            }),
            (34, 5) => Field::from("Activity local timestamp"),
            (34, 6) => Field::from("Activity event group"),
            // session (18)
            (18, 254) => Field::from("message_index"),
            (18, 253) => Field::from("timestamp"),
            (18, 0) => Field::from("event"),
            (18, 1) => Field::from("event_type"),
            (18, 2) => Field::from("start_time"),
            (18, 3) => Field::from("start_position_lat"),
            (18, 4) => Field::from("start_position_long"),
            (18, 5) => Field::from("sport"),
            (18, 6) => Field::from("sub_sport"),
            (18, 7) => Field::from("total_elapsed_time"),
            (18, 8) => Field::from("total_timer_time"),
            (18, 9) => Field::from("total_distance"),
            (18, 10) => Field::from("total_cycles"),
            (18, 11) => Field::from("total_calories"),
            (18, 13) => Field::from("total_fat_calories"),
            (18, 14) => Field::from("avg_speed"),
            (18, 15) => Field::from("max_speed"),
            (18, 16) => Field::from("avg_heart_rate"),
            (18, 17) => Field::from("max_heart_rate"),
            (18, 18) => Field::from("avg_cadence"),
            (18, 19) => Field::from("max_cadence"),
            (18, 20) => Field::from("avg_power"),
            (18, 21) => Field::from("max_power"),
            (18, 22) => Field::from("total_ascent"),
            (18, 23) => Field::from("total_descent"),
            (18, 24) => Field::from("total_training_effect"),
            (18, 25) => Field::from("first_lap_index"),
            (18, 26) => Field::from("num_laps"),
            (18, 27) => Field::from("event_group"),
            (18, 28) => Field::from("trigger"),
            (18, 29) => Field::from("nec_lat"),
            (18, 30) => Field::from("nec_long"),
            (18, 31) => Field::from("swc_lat"),
            (18, 32) => Field::from("swc_long"),
            (18, 33) => Field::from("num_lengths"),
            (18, 34) => Field::from("normalized_power"),
            (18, 35) => Field::from("training_stress_score"),
            (18, 36) => Field::from("intensity_factor"),
            (18, 37) => Field::from("left_right_balance"),
            (18, 38) => Field::from("end_position_lat"),
            (18, 39) => Field::from("end_position_long"),
            (18, 41) => Field::from("avg_stroke_count"),
            (18, 42) => Field::from("avg_stroke_distance"),
            (18, 43) => Field::from("swim_stroke"),
            (18, 44) => Field::from("pool_length"),
            (18, 45) => Field::from("threshold_power"),
            (18, 46) => Field::from("pool_length_unit"),
            (18, 47) => Field::from("num_active_lengths"),
            (18, 48) => Field::from("total_work"),
            (18, 49) => Field::from("avg_altitude"),
            (18, 50) => Field::from("max_altitude"),
            (18, 51) => Field::from("gps_accuracy"),
            (18, 52) => Field::from("avg_grade"),
            (18, 53) => Field::from("avg_pos_grade"),
            (18, 54) => Field::from("avg_neg_grade"),
            (18, 55) => Field::from("max_pos_grade"),
            (18, 56) => Field::from("max_neg_grade"),
            (18, 57) => Field::from("avg_temperature"),
            (18, 58) => Field::from("max_temperature"),
            (18, 59) => Field::from("total_moving_time"),
            (18, 60) => Field::from("avg_pos_vertical_speed"),
            (18, 61) => Field::from("avg_neg_vertical_speed"),
            (18, 62) => Field::from("max_pos_vertical_speed"),
            (18, 63) => Field::from("max_neg_vertical_speed"),
            (18, 64) => Field::from("min_heart_rate"),
            (18, 65) => Field::from("time_in_hr_zone"),
            (18, 66) => Field::from("time_in_speed_zone"),
            (18, 67) => Field::from("time_in_cadence_zone"),
            (18, 68) => Field::from("time_in_power_zone"),
            (18, 69) => Field::from("avg_lap_time"),
            (18, 70) => Field::from("best_lap_index"),
            (18, 71) => Field::from("min_altitude"),
            (18, 82) => Field::from("player_score"),
            (18, 83) => Field::from("opponent_score"),
            (18, 84) => Field::from("opponent_name"),
            (18, 85) => Field::from("stroke_count"),
            (18, 86) => Field::from("zone_count"),
            (18, 87) => Field::from("max_ball_speed"),
            (18, 88) => Field::from("avg_ball_speed"),
            (18, 89) => Field::from("avg_vertical_oscillation"),
            (18, 90) => Field::from("avg_stance_time_percent"),
            (18, 91) => Field::from("avg_stance_time"),
            (18, 92) => Field::from("avg_fractional_cadence"),
            (18, 93) => Field::from("max_fractional_cadence"),
            (18, 94) => Field::from("total_fractional_cycles"),
            (18, 95) => Field::from("avg_total_hemoglobin_conc"),
            (18, 96) => Field::from("min_total_hemoglobin_conc"),
            (18, 97) => Field::from("max_total_hemoglobin_conc"),
            (18, 98) => Field::from("avg_saturated_hemoglobin_percent"),
            (18, 99) => Field::from("min_saturated_hemoglobin_percent"),
            (18, 100) => Field::from("max_saturated_hemoglobin_percent"),
            (18, 101) => Field::from("avg_left_torque_effectiveness"),
            (18, 102) => Field::from("avg_right_torque_effectiveness"),
            (18, 103) => Field::from("avg_left_pedal_smoothness"),
            (18, 104) => Field::from("avg_right_pedal_smoothness"),
            (18, 105) => Field::from("avg_combined_pedal_smoothness"),
            (18, 110) => Field::from("sport_profile_name"),
            (18, 111) => Field::from("sport_index"),
            (18, 112) => Field::from("time_standing"),
            (18, 113) => Field::from("stand_count"),
            (18, 114) => Field::from("avg_left_pco"),
            (18, 115) => Field::from("avg_right_pco"),
            (18, 116) => Field::from("avg_left_power_phase"),
            (18, 117) => Field::from("avg_left_power_phase_peak"),
            (18, 118) => Field::from("avg_right_power_phase"),
            (18, 119) => Field::from("avg_right_power_phase_peak"),
            (18, 120) => Field::from("avg_power_position"),
            (18, 121) => Field::from("max_power_position"),
            (18, 122) => Field::from("avg_cadence_position"),
            (18, 123) => Field::from("max_cadence_position"),
            (18, 124) => Field::from("enhanced_avg_speed"),
            (18, 125) => Field::from("enhanced_max_speed"),
            (18, 126) => Field::from("enhanced_avg_altitude"),
            (18, 127) => Field::from("enhanced_min_altitude"),
            (18, 128) => Field::from("enhanced_max_altitude"),
            (18, 129) => Field::from("avg_lev_motor_power"),
            (18, 130) => Field::from("max_lev_motor_power"),
            (18, 131) => Field::from("lev_battery_consumption"),
            (18, 132) => Field::from("avg_vertical_ratio"),
            (18, 133) => Field::from("avg_stance_time_balance"),
            (18, 134) => Field::from("avg_step_length"),
            (18, 137) => Field::from("total_anaerobic_training_effect"),
            (18, 139) => Field::from("avg_vam"),
            (18, 140) => Field::from("avg_depth"),
            (18, 141) => Field::from("max_depth"),
            (18, 142) => Field::from("surface_interval"),
            (18, 143) => Field::from("start_cns"),
            (18, 144) => Field::from("end_cns"),
            (18, 145) => Field::from("start_n2"),
            (18, 146) => Field::from("end_n2"),
            (18, 147) => Field::from("avg_respiration_rate"),
            (18, 148) => Field::from("max_respiration_rate"),
            (18, 149) => Field::from("min_respiration_rate"),
            (18, 150) => Field::from("min_temperature"),
            (18, 155) => Field::from("o2_toxicity"),
            (18, 156) => Field::from("dive_number"),
            (18, 168) => Field::from("training_load_peak"),
            (18, 169) => Field::from("enhanced_avg_respiration_rate"),
            (18, 170) => Field::from("enhanced_max_respiration_rate"),
            (18, 180) => Field::from("enhanced_min_respiration_rate"),
            (18, 181) => Field::from("total_grit"),
            (18, 182) => Field::from("total_flow"),
            (18, 183) => Field::from("jump_count"),
            (18, 186) => Field::from("avg_grit"),
            (18, 187) => Field::from("avg_flow"),
            (18, 194) => Field::from("avg_spo2"),
            (18, 195) => Field::from("avg_stress"),
            (18, 197) => Field::from("sdrr_hrv"),
            (18, 198) => Field::from("rmssd_hrv"),
            (18, 199) => Field::from("total_fractional_ascent"),
            (18, 200) => Field::from("total_fractional_descent"),
            (18, 208) => Field::from("avg_core_temperature"),
            (18, 209) => Field::from("min_core_temperature"),
            (18, 210) => Field::from("max_core_temperature"),
            // lap (19)
            (10, 254) => Field::from("message_index"),
            (10, 253) => Field::from("timestamp"),
            (10, 0) => Field::from("event"),
            (10, 1) => Field::from("event_type"),
            (10, 2) => Field::from("start_time"),
            (10, 3) => Field::from("start_position_lat"),
            (10, 4) => Field::from("start_position_long"),
            (10, 5) => Field::from("end_position_lat"),
            (10, 6) => Field::from("end_position_long"),
            (10, 7) => Field::from("total_elapsed_time"),
            (10, 8) => Field::from("total_timer_time"),
            (10, 9) => Field::from("total_distance"),
            (10, 10) => Field::from("total_cycles"),
            (10, 11) => Field::from("total_calories"),
            (10, 12) => Field::from("total_fat_calories"),
            (10, 13) => Field::from("avg_speed"),
            (10, 14) => Field::from("max_speed"),
            (10, 15) => Field::from("avg_heart_rate"),
            (10, 16) => Field::from("max_heart_rate"),
            (10, 17) => Field::from("avg_cadence"),
            (10, 18) => Field::from("max_cadence"),
            (10, 19) => Field::from("avg_power"),
            (10, 20) => Field::from("max_power"),
            (10, 21) => Field::from("total_ascent"),
            (10, 22) => Field::from("total_descent"),
            (10, 23) => Field::from("intensity"),
            (10, 24) => Field::from("lap_trigger"),
            (10, 25) => Field::from("sport"),
            (10, 26) => Field::from("event_group"),
            (10, 32) => Field::from("num_lengths"),
            (10, 33) => Field::from("normalized_power"),
            (10, 34) => Field::from("left_right_balance"),
            (10, 35) => Field::from("first_length_index"),
            (10, 37) => Field::from("avg_stroke_distance"),
            (10, 38) => Field::from("swim_stroke"),
            (10, 39) => Field::from("sub_sport"),
            (10, 40) => Field::from("num_active_lengths"),
            (10, 41) => Field::from("total_work"),
            (10, 42) => Field::from("avg_altitude"),
            (10, 43) => Field::from("max_altitude"),
            (10, 44) => Field::from("gps_accuracy"),
            (10, 45) => Field::from("avg_grade"),
            (10, 46) => Field::from("avg_pos_grade"),
            (10, 47) => Field::from("avg_neg_grade"),
            (10, 48) => Field::from("max_pos_grade"),
            (10, 49) => Field::from("max_neg_grade"),
            (10, 50) => Field::from("avg_temperature"),
            (10, 51) => Field::from("max_temperature"),
            (10, 52) => Field::from("total_moving_time"),
            (10, 53) => Field::from("avg_pos_vertical_speed"),
            (10, 54) => Field::from("avg_neg_vertical_speed"),
            (10, 55) => Field::from("max_pos_vertical_speed"),
            (10, 56) => Field::from("max_neg_vertical_speed"),
            (10, 57) => Field::from("time_in_hr_zone"),
            (10, 58) => Field::from("time_in_speed_zone"),
            (10, 59) => Field::from("time_in_cadence_zone"),
            (10, 60) => Field::from("time_in_power_zone"),
            (10, 61) => Field::from("repetition_num"),
            (10, 62) => Field::from("min_altitude"),
            (10, 63) => Field::from("min_heart_rate"),
            (10, 71) => Field::from("wkt_step_index"),
            (10, 74) => Field::from("opponent_score"),
            (10, 75) => Field::from("stroke_count"),
            (10, 76) => Field::from("zone_count"),
            (10, 77) => Field::from("avg_vertical_oscillation"),
            (10, 78) => Field::from("avg_stance_time_percent"),
            (10, 79) => Field::from("avg_stance_time"),
            (10, 80) => Field::from("avg_fractional_cadence"),
            (10, 81) => Field::from("max_fractional_cadence"),
            (10, 82) => Field::from("total_fractional_cycles"),
            (10, 83) => Field::from("player_score"),
            (10, 84) => Field::from("avg_total_hemoglobin_conc"),
            (10, 85) => Field::from("min_total_hemoglobin_conc"),
            (10, 86) => Field::from("max_total_hemoglobin_conc"),
            (10, 87) => Field::from("avg_saturated_hemoglobin_percent"),
            (10, 88) => Field::from("min_saturated_hemoglobin_percent"),
            (10, 89) => Field::from("max_saturated_hemoglobin_percent"),
            (10, 91) => Field::from("avg_left_torque_effectiveness"),
            (10, 92) => Field::from("avg_right_torque_effectiveness"),
            (10, 93) => Field::from("avg_left_pedal_smoothness"),
            (10, 94) => Field::from("avg_right_pedal_smoothness"),
            (10, 95) => Field::from("avg_combined_pedal_smoothness"),
            (10, 98) => Field::from("time_standing"),
            (10, 99) => Field::from("stand_count"),
            (10, 100) => Field::from("avg_left_pco"),
            (10, 101) => Field::from("avg_right_pco"),
            (10, 102) => Field::from("avg_left_power_phase"),
            (10, 103) => Field::from("avg_left_power_phase_peak"),
            (10, 104) => Field::from("avg_right_power_phase"),
            (10, 105) => Field::from("avg_right_power_phase_peak"),
            (10, 106) => Field::from("avg_power_position"),
            (10, 107) => Field::from("max_power_position"),
            (10, 108) => Field::from("avg_cadence_position"),
            (10, 109) => Field::from("max_cadence_position"),
            (10, 110) => Field::from("enhanced_avg_speed"),
            (10, 111) => Field::from("enhanced_max_speed"),
            (10, 112) => Field::from("enhanced_avg_altitude"),
            (10, 113) => Field::from("enhanced_min_altitude"),
            (10, 114) => Field::from("enhanced_max_altitude"),
            (10, 115) => Field::from("avg_lev_motor_power"),
            (10, 116) => Field::from("max_lev_motor_power"),
            (10, 117) => Field::from("lev_battery_consumption"),
            (10, 118) => Field::from("avg_vertical_ratio"),
            (10, 119) => Field::from("avg_stance_time_balance"),
            (10, 120) => Field::from("avg_step_length"),
            (10, 121) => Field::from("avg_vam"),
            (10, 122) => Field::from("avg_depth"),
            (10, 123) => Field::from("max_depth"),
            (10, 124) => Field::from("min_temperature"),
            (10, 136) => Field::from("enhanced_avg_respiration_rate"),
            (10, 137) => Field::from("enhanced_max_respiration_rate"),
            (10, 147) => Field::from("avg_respiration_rate"),
            (10, 148) => Field::from("max_respiration_rate"),
            (10, 149) => Field::from("total_grit"),
            (10, 150) => Field::from("total_flow"),
            (10, 151) => Field::from("jump_count"),
            (10, 153) => Field::from("avg_grit"),
            (10, 154) => Field::from("avg_flow"),
            (10, 156) => Field::from("total_fractional_ascent"),
            (10, 157) => Field::from("total_fractional_descent"),
            (10, 158) => Field::from("avg_core_temperature"),
            (10, 159) => Field::from("min_core_temperature"),
            (10, 160) => Field::from("max_core_temperature"),
            // length (101)
            (101, 254) => Field::from("message_index"),
            (101, 253) => Field::from("timestamp"),
            (101, 0) => Field::from("event"),
            (101, 1) => Field::from("event_type"),
            (101, 2) => Field::from("start_time"),
            (101, 3) => Field::from("total_elapsed_time"),
            (101, 4) => Field::from("total_timer_time"),
            (101, 5) => Field::from("total_strokes"),
            (101, 6) => Field::from("avg_speed"),
            (101, 7) => Field::from("swim_stroke"),
            (101, 9) => Field::from("avg_swimming_cadence"),
            (101, 10) => Field::from("event_group"),
            (101, 11) => Field::from("total_calories"),
            (101, 12) => Field::from("length_type"),
            (101, 18) => Field::from("player_score"),
            (101, 19) => Field::from("opponent_score"),
            (101, 20) => Field::from("stroke_count"),
            (101, 21) => Field::from("zone_count"),
            (101, 22) => Field::from("enhanced_avg_respiration_rate"),
            (101, 23) => Field::from("enhanced_max_respiration_rate"),
            (101, 24) => Field::from("avg_respiration_rate"),
            (101, 25) => Field::from("max_respiration_rate"),
            // record (20)
            (20, 0) => Field::from("Position latitude"), // semicircles / 11930465
            (20, 1) => Field::from("Position longitude"), // semicircles / 11930465
            (20, 2) => Field::from("Altitude"),
            (20, 3) => Field::from("Heart rate"),
            (20, 4) => Field::from("CADENCE"),
            (20, 5) => Field::from("Distance"),
            (20, 6) => Field::from("SPEED"),
            (20, 7) => Field::from("POWER"),
            (20, 8) => Field::from("COMPRESSED_SPEED_DISTANCE"),
            (20, 9) => Field::from("GRADE"),
            (20, 10) => Field::from("RESISTANCE"),
            (20, 11) => Field::from("TIME_FROM_COURSE"),
            (20, 12) => Field::from("CYCLE_LENGTH"),
            (20, 13) => Field::from("Temperature"),
            (20, 17) => Field::from("SPEED_1S"),
            (20, 18) => Field::from("CYCLES"),
            (20, 19) => Field::from("TOTAL_CYCLES"),
            (20, 28) => Field::from("COMPRESSED_ACCUMULATED_POWER"),
            (20, 29) => Field::from("ACCUMULATED_POWER"),
            (20, 30) => Field::from("LEFT_RIGHT_BALANCE"),
            (20, 31) => Field::from("GPS_ACCURACY"),
            (20, 32) => Field::from("VERTICAL_SPEED"),
            (20, 33) => Field::from("CALORIES"),
            (20, 39) => Field::from("VERTICAL_OSCILLATION"),
            (20, 40) => Field::from("STANCE_TIME_PERCENT"),
            (20, 41) => Field::from("STANCE_TIME"),
            (20, 42) => Field::from("ACTIVITY_TYPE"),
            (20, 43) => Field::from("LEFT_TORQUE_EFFECTIVENESS"),
            (20, 44) => Field::from("RIGHT_TORQUE_EFFECTIVENESS"),
            (20, 45) => Field::from("LEFT_PEDAL_SMOOTHNESS"),
            (20, 46) => Field::from("RIGHT_PEDAL_SMOOTHNESS"),
            (20, 47) => Field::from("COMBINED_PEDAL_SMOOTHNESS"),
            (20, 48) => Field::from("TIME128"),
            (20, 49) => Field::from("STROKE_TYPE"),
            (20, 50) => Field::from("ZONE"),
            (20, 51) => Field::from("BALL_SPEED"),
            (20, 52) => Field::from("CADENCE256"),
            (20, 53) => Field::from("FRACTIONAL_CADENCE"),
            (20, 54) => Field::from("TOTAL_HEMOGLOBIN_CONC"),
            (20, 55) => Field::from("TOTAL_HEMOGLOBIN_CONC_MIN"),
            (20, 56) => Field::from("TOTAL_HEMOGLOBIN_CONC_MAX"),
            (20, 57) => Field::from("SATURATED_HEMOGLOBIN_PERCENT"),
            (20, 58) => Field::from("SATURATED_HEMOGLOBIN_PERCENT_MIN"),
            (20, 59) => Field::from("SATURATED_HEMOGLOBIN_PERCENT_MAX"),
            (20, 62) => Field::from("DEVICE_INDEX"),
            (20, 67) => Field::from("LEFT_PCO"),
            (20, 68) => Field::from("RIGHT_PCO"),
            (20, 69) => Field::from("LEFT_POWER_PHASE"),
            (20, 70) => Field::from("LEFT_POWER_PHASE_PEAK"),
            (20, 71) => Field::from("RIGHT_POWER_PHASE"),
            (20, 20) => Field::from("RIGHT_POWER_PHASE_PEAK"),
            (20, 73) => Field::from("ENHANCED_SPEED"),
            (20, 78) => Field::from("ENHANCED_ALTITUDE"),
            (20, 81) => Field::from("BATTERY_SOC"),
            (20, 82) => Field::from("MOTOR_POWER"),
            (20, 83) => Field::from("VERTICAL_RATIO"),
            (20, 84) => Field::from("STANCE_TIME_BALANCE"),
            (20, 85) => Field::from("STEP_LENGTH"),
            (20, 87) => Field::from("CYCLE_LENGTH16"),
            (20, 91) => Field::from("ABSOLUTE_PRESSURE"),
            (20, 92) => Field::from("DEPTH"),
            (20, 93) => Field::from("NEXT_STOP_DEPTH"),
            (20, 94) => Field::from("NEXT_STOP_TIME"),
            (20, 95) => Field::from("TIME_TO_SURFACE"),
            (20, 96) => Field::from("NDL_TIME"),
            (20, 97) => Field::from("CNS_LOAD"),
            (20, 98) => Field::from("N2_LOAD"),
            (20, 99) => Field::from("RESPIRATION_RATE"),
            (20, 108) => Field::from("ENHANCED_RESPIRATION_RATE"),
            (20, 114) => Field::from("GRIT"),
            (20, 115) => Field::from("FLOW"),
            (20, 116) => Field::from("CURRENT_STRESS"),
            (20, 117) => Field::from("EBIKE_TRAVEL_RANGE"),
            (20, 118) => Field::from("EBIKE_BATTERY_LEVEL"),
            (20, 119) => Field::from("EBIKE_ASSIST_MODE"),
            (20, 120) => Field::from("EBIKE_ASSIST_LEVEL_PERCENT"),
            (20, 123) => Field::from("AIR_TIME_REMAINING"),
            (20, 124) => Field::from("PRESSURE_SAC"),
            (20, 125) => Field::from("VOLUME_SAC"),
            (20, 126) => Field::from("RMV"),
            (20, 127) => Field::from("ASCENT_RATE"),
            (20, 129) => Field::from("PO2"),
            (20, 139) => Field::from("CORE_TEMPERATURE"),
            (20, 253) => Field::from("Timestamp"),
            // event (21)
            (21, 253) => Field::from("timestamp"),
            (21, 0) => Field::from_with_converter("event", |_, value: &u8| -> String {
                Event::resolve(&value).to_string()
            }),
            (21, 1) => Field::from_with_converter("event_type", |_, value: &u8| -> String {
                EventType::resolve(&value).to_string()
            }),
            (21, 2) => Field::from("data16"),
            (21, 3) => Field::from("data"),
            (21, 4) => Field::from("event_group"),
            (21, 7) => Field::from("score"),
            (21, 8) => Field::from("opponent_score"),
            (21, 9) => Field::from("front_gear_num"),
            (21, 10) => Field::from("front_gear"),
            (21, 11) => Field::from("rear_gear_num"),
            (21, 12) => Field::from("rear_gear"),
            (21, 13) => Field::from("device_index"),
            (21, 14) => Field::from("activity_type"),
            (21, 15) => Field::from("start_timestamp"),
            (21, 21) => Field::from("radar_threat_level_max"),
            (21, 22) => Field::from("radar_threat_count"),
            (21, 23) => Field::from("radar_threat_avg_approach_speed"),
            (21, 24) => Field::from("radar_threat_max_approach_speed"),
            // device info (23)
            (23, 253) => Field::from("Device info timestamp"),
            (23, 0) => Field::from("device_index"),
            (23, 1) => Field::from("device_type"),
            (23, 2) => Field::from("manufacturer"),
            (23, 3) => Field::from("serial_number"),
            (23, 4) => Field::from("product"),
            (23, 5) => Field::from("software_version"),
            (23, 6) => Field::from("hardware_version"),
            (23, 7) => Field::from("cum_operating_time"),
            (23, 10) => Field::from("battery_voltage"),
            (23, 11) => Field::from("battery_status"),
            (23, 18) => Field::from("sensor_position"),
            (23, 19) => Field::from("descriptor"),
            (23, 20) => Field::from("ant_transmission_type"),
            (23, 21) => Field::from("ant_device_number"),
            (23, 22) => Field::from("ant_network"),
            (23, 25) => Field::from("source_type"),
            (23, 27) => Field::from("product_name"),
            (23, 32) => Field::from("battery_level"),
            // device aux battery info (375)
            (375, 253) => Field::from("timestamp"),
            (375, 0) => Field::from("device_index"),
            (375, 1) => Field::from("battery_voltage"),
            (375, 2) => Field::from("battery_status"),
            (375, 3) => Field::from("battery_identifier"),
            // training file (72)
            (72, 253) => Field::from("Training file timestamp"),
            (72, 0) => Field::from("File Type"),
            (72, 1) => Field::from("Manufacturer"),
            (72, 2) => Field::from("Product"),
            (72, 3) => Field::from("Serial number"),
            (72, 4) => Field::from("Time created"),
            // weather conditions (128)
            (128, 253) => Field::from("timestamp"),
            (128, 0) => Field::from("weather_report"),
            (128, 1) => Field::from("temperature"),
            (128, 2) => Field::from("condition"),
            (128, 3) => Field::from("wind_direction"),
            (128, 4) => Field::from("wind_speed"),
            (128, 5) => Field::from("precipitation_probability"),
            (128, 6) => Field::from("temperature_feels_like"),
            (128, 7) => Field::from("relative_humidity"),
            (128, 8) => Field::from("location"),
            (128, 9) => Field::from("observed_at_time"),
            (128, 10) => Field::from("observed_location_lat"),
            (128, 11) => Field::from("observed_location_long"),
            (128, 12) => Field::from("day_of_week"),
            (128, 13) => Field::from("high_temperature"),
            (128, 14) => Field::from("low_temperature"),
            // weather alert (129)
            (129, 253) => Field::from("timestamp"),
            (129, 0) => Field::from("report_id"),
            (129, 1) => Field::from("issue_time"),
            (129, 2) => Field::from("expire_time"),
            (129, 3) => Field::from("severity"),
            (129, 4) => Field::from("type"),
            // gps metadata (160)
            (160, 253) => Field::from("timestamp"),
            (160, 0) => Field::from("timestamp_ms"),
            (160, 1) => Field::from("position_lat"),
            (160, 2) => Field::from("position_long"),
            (160, 3) => Field::from("enhanced_altitude"),
            (160, 4) => Field::from("enhanced_speed"),
            (160, 5) => Field::from("heading"),
            (160, 6) => Field::from("utc_timestamp"),
            (160, 7) => Field::from("velocity"),
            // camera event (161)
            (161, 0) => Field::from("timestamp_ms"),
            (161, 1) => Field::from("camera_event_type"),
            (161, 2) => Field::from("camera_file_uuid"),
            // gyroscope data (164)
            (164, 0) => Field::from("timestamp_ms"),
            (164, 1) => Field::from("sample_time_offset"),
            (164, 2) => Field::from("gyro_x"),
            (164, 3) => Field::from("gyro_y"),
            (164, 4) => Field::from("gyro_z"),
            (164, 5) => Field::from("calibrated_gyro_x"),
            (164, 6) => Field::from("calibrated_gyro_y"),
            (164, 7) => Field::from("calibrated_gyro_z"),
            // accelerometer data (165)
            (165, 0) => Field::from("timestamp_ms"),
            (165, 1) => Field::from("sample_time_offset"),
            (165, 2) => Field::from("accel_x"),
            (165, 3) => Field::from("accel_y"),
            (165, 4) => Field::from("accel_z"),
            (165, 5) => Field::from("calibrated_accel_x"),
            (165, 6) => Field::from("calibrated_accel_y"),
            (165, 7) => Field::from("calibrated_accel_z"),
            (165, 8) => Field::from("compressed_calibrated_accel_x"),
            (165, 9) => Field::from("compressed_calibrated_accel_y"),
            (165, 10) => Field::from("compressed_calibrated_accel_z"),
            // magnetometer data (208)
            (208, 253) => Field::from("timestamp"),
            (208, 0) => Field::from("timestamp_ms"),
            (208, 1) => Field::from("sample_time_offset"),
            (208, 2) => Field::from("mag_x"),
            (208, 3) => Field::from("mag_y"),
            (208, 4) => Field::from("mag_z"),
            (208, 5) => Field::from("calibrated_mag_x"),
            (208, 6) => Field::from("calibrated_mag_y"),
            (208, 7) => Field::from("calibrated_mag_z"),
            // barometer data (209)
            (209, 253) => Field::from("timestamp"),
            (209, 0) => Field::from("timestamp_ms"),
            (209, 1) => Field::from("sample_time_offset"),
            (209, 2) => Field::from("baro_pres"),
            // three d sensor calibration (167)
            (167, 253) => Field::from("timestamp"),
            (167, 0) => Field::from("sensor_type"),
            (167, 1) => Field::from("calibration_factor"),
            (167, 2) => Field::from("calibration_divisor"),
            (167, 3) => Field::from("level_shift"),
            (167, 4) => Field::from("offset_cal"),
            (167, 5) => Field::from("orientation_matrix"),
            // one d sensor calibration (210)
            (210, 253) => Field::from("timestamp"),
            (210, 0) => Field::from("sensor_type"),
            (210, 1) => Field::from("calibration_factor"),
            (210, 2) => Field::from("calibration_divisor"),
            (210, 3) => Field::from("level_shift"),
            (210, 4) => Field::from("offset_cal"),
            // video frame (169)
            (169, 253) => Field::from("timestamp"),
            (169, 0) => Field::from("timestamp_ms"),
            (169, 1) => Field::from("frame_number"),
            // obd II data (174)
            (174, 253) => Field::from("timestamp"),
            (174, 0) => Field::from("timestamp_ms"),
            (174, 1) => Field::from("time_offset"),
            (174, 2) => Field::from("pid"),
            (174, 3) => Field::from("raw_data"),
            (174, 4) => Field::from("pid_data_size"),
            (174, 5) => Field::from("system_time"),
            (174, 6) => Field::from("start_timestamp"),
            (174, 7) => Field::from("start_timestamp_ms"),
            // nmea sequence (177)
            (177, 253) => Field::from("timestamp"),
            (177, 0) => Field::from("timestamp_ms"),
            (177, 1) => Field::from("sentence"),
            // aviation attitude (178)
            (178, 253) => Field::from("timestamp"),
            (178, 0) => Field::from("timestamp_ms"),
            (178, 1) => Field::from("system_time"),
            (178, 2) => Field::from("pitch"),
            (178, 3) => Field::from("roll"),
            (178, 4) => Field::from("accel_lateral"),
            (178, 5) => Field::from("accel_normal"),
            (178, 6) => Field::from("turn_rate"),
            (178, 7) => Field::from("stage"),
            (178, 8) => Field::from("attitude_stage_complete"),
            (178, 9) => Field::from("track"),
            (178, 10) => Field::from("validity"),
            // video (184)
            (184, 0) => Field::from("url"),
            (184, 1) => Field::from("hosting_provider"),
            (184, 2) => Field::from("duration"),
            // video title (185)
            (185, 254) => Field::from("message_index"),
            (185, 0) => Field::from("message_count"),
            (185, 1) => Field::from("text"),
            // video description (186)
            (186, 254) => Field::from("message_index"),
            (186, 0) => Field::from("message_count"),
            (186, 1) => Field::from("text"),
            // video clip (187)
            (187, 0) => Field::from("clip_number"),
            (187, 1) => Field::from("start_timestamp"),
            (187, 2) => Field::from("start_timestamp_ms"),
            (187, 3) => Field::from("end_timestamp"),
            (187, 4) => Field::from("end_timestamp_ms"),
            (187, 6) => Field::from("clip_start"),
            (187, 7) => Field::from("clip_end"),
            // set (225)
            (225, 254) => Field::from("timestamp"),
            (225, 0) => Field::from("duration"),
            (225, 3) => Field::from("repetitions"),
            (225, 4) => Field::from("weight"),
            (225, 5) => Field::from("set_type"),
            (225, 6) => Field::from("start_time"),
            (225, 7) => Field::from("category"),
            (225, 8) => Field::from("category_subtype"),
            (225, 9) => Field::from("weight_display_unit"),
            (225, 10) => Field::from("message_index"),
            (225, 11) => Field::from("wkt_step_index"),
            // jump (285)
            (285, 253) => Field::from("timestamp"),
            (285, 0) => Field::from("distance"),
            (285, 1) => Field::from("height"),
            (285, 2) => Field::from("rotations"),
            (285, 3) => Field::from("hang_time"),
            (285, 4) => Field::from("score"),
            (285, 5) => Field::from("position_lat"),
            (285, 6) => Field::from("position_long"),
            (285, 7) => Field::from("speed"),
            (285, 8) => Field::from("enhanced_speed"),
            // split (312)
            (312, 254) => Field::from("message_index"),
            (312, 0) => Field::from("split_type"),
            (312, 1) => Field::from("total_elapsed_time"),
            (312, 2) => Field::from("total_timer_time"),
            (312, 3) => Field::from("total_distance"),
            (312, 4) => Field::from("avg_speed"),
            (312, 9) => Field::from("start_time"),
            (312, 13) => Field::from("total_ascent"),
            (312, 14) => Field::from("total_descent"),
            (312, 21) => Field::from("start_position_lat"),
            (312, 22) => Field::from("start_position_long"),
            (312, 23) => Field::from("end_position_lat"),
            (312, 24) => Field::from("end_position_long"),
            (312, 25) => Field::from("max_speed"),
            (312, 26) => Field::from("avg_vert_speed"),
            (312, 27) => Field::from("end_time"),
            (312, 28) => Field::from("total_calories"),
            (312, 74) => Field::from("start_elevation"),
            (312, 110) => Field::from("total_moving_time"),
            // split summary (313)
            (313, 254) => Field::from("message_index"),
            (313, 0) => Field::from("split_type"),
            (313, 3) => Field::from("num_splits"),
            (313, 4) => Field::from("total_timer_time"),
            (313, 5) => Field::from("total_distance"),
            (313, 6) => Field::from("avg_speed"),
            (313, 7) => Field::from("max_speed"),
            (313, 8) => Field::from("total_ascent"),
            (313, 9) => Field::from("total_descent"),
            (313, 10) => Field::from("avg_heart_rate"),
            (313, 11) => Field::from("max_heart_rate"),
            (313, 12) => Field::from("avg_vert_speed"),
            (313, 13) => Field::from("total_calories"),
            (313, 77) => Field::from("total_moving_time"),
            // climb pro (317)
            (317, 253) => Field::from("timestamp"),
            (317, 0) => Field::from("position_lat"),
            (317, 1) => Field::from("position_long"),
            (317, 2) => Field::from("climb_pro_event"),
            (317, 3) => Field::from("climb_number"),
            (317, 4) => Field::from("climb_category"),
            (317, 5) => Field::from("current_dist"),
            // <end activity file messages>
            // audio undocumented (147)
            (147, 2) => Field::from("Audio device"),
            _ => Field::from("Unknown"),
        }
    }
}
