use std::fmt;
use std::fmt::{Display, Formatter};
crate::key_value_enum! {
	pub enum File { 
		Device = 1,
		Settings = 2,
		Sport = 3,
		Activity = 4,
		Workout = 5,
		Course = 6,
		Schedules = 7,
		Weight = 9,
		Totals = 10,
		Goals = 11,
		BloodPressure = 14,
		MonitoringA = 15,
		ActivitySummary = 20,
		MonitoringDaily = 28,
		MonitoringB = 32,
		Segment = 34,
		SegmentList = 35,
		ExdConfiguration = 40,
		MfgRangeMin = 0xF7,
		MfgRangeMax = 0xFE,
	}
}
crate::key_value_enum! {
	pub enum MesgNum { 
		FileId = 0,
		Capabilities = 1,
		DeviceSettings = 2,
		UserProfile = 3,
		HrmProfile = 4,
		SdmProfile = 5,
		BikeProfile = 6,
		ZonesTarget = 7,
		HrZone = 8,
		PowerZone = 9,
		MetZone = 10,
		Sport = 12,
		Goal = 15,
		Session = 18,
		Lap = 19,
		Record = 20,
		Event = 21,
		DeviceInfo = 23,
		Workout = 26,
		WorkoutStep = 27,
		Schedule = 28,
		WeightScale = 30,
		Course = 31,
		CoursePoint = 32,
		Totals = 33,
		Activity = 34,
		Software = 35,
		FileCapabilities = 37,
		MesgCapabilities = 38,
		FieldCapabilities = 39,
		FileCreator = 49,
		BloodPressure = 51,
		SpeedZone = 53,
		Monitoring = 55,
		TrainingFile = 72,
		Hrv = 78,
		AntRx = 80,
		AntTx = 81,
		AntChannelId = 82,
		Length = 101,
		MonitoringInfo = 103,
		Pad = 105,
		SlaveDevice = 106,
		Connectivity = 127,
		WeatherConditions = 128,
		WeatherAlert = 129,
		CadenceZone = 131,
		Hr = 132,
		SegmentLap = 142,
		MemoGlob = 145,
		SegmentId = 148,
		SegmentLeaderboardEntry = 149,
		SegmentPoint = 150,
		SegmentFile = 151,
		WorkoutSession = 158,
		WatchfaceSettings = 159,
		GpsMetadata = 160,
		CameraEvent = 161,
		TimestampCorrelation = 162,
		GyroscopeData = 164,
		AccelerometerData = 165,
		ThreeDSensorCalibration = 167,
		VideoFrame = 169,
		ObdiiData = 174,
		NmeaSentence = 177,
		AviationAttitude = 178,
		Video = 184,
		VideoTitle = 185,
		VideoDescription = 186,
		VideoClip = 187,
		OhrSettings = 188,
		ExdScreenConfiguration = 200,
		ExdDataFieldConfiguration = 201,
		ExdDataConceptConfiguration = 202,
		FieldDescription = 206,
		DeveloperDataId = 207,
		MagnetometerData = 208,
		BarometerData = 209,
		OneDSensorCalibration = 210,
		MonitoringHrData = 211,
		TimeInZone = 216,
		Set = 225,
		StressLevel = 227,
		MaxMetData = 229,
		DiveSettings = 258,
		DiveGas = 259,
		DiveAlarm = 262,
		ExerciseTitle = 264,
		DiveSummary = 268,
		SpotwoData = 269,
		SleepLevel = 275,
		Jump = 285,
		AadAccelFeatures = 289,
		BeatIntervals = 290,
		RespirationRate = 297,
		HsaAccelerometerData = 302,
		HsaStepData = 304,
		HsaSpotwoData = 305,
		HsaStressData = 306,
		HsaRespirationData = 307,
		HsaHeartRateData = 308,
		Split = 312,
		SplitSummary = 313,
		HsaBodyBatteryData = 314,
		HsaEvent = 315,
		ClimbPro = 317,
		TankUpdate = 319,
		TankSummary = 323,
		SleepAssessment = 346,
		HrvStatusSummary = 370,
		HrvValue = 371,
		RawBbi = 372,
		DeviceAuxBatteryInfo = 375,
		HsaGyroscopeData = 376,
		ChronoShotSession = 387,
		ChronoShotData = 388,
		HsaConfigurationData = 389,
		DiveApneaAlarm = 393,
		HsaWristTemperatureData = 409,
		MfgRangeMin = 0xFF00,
		MfgRangeMax = 0xFFFE,
	}
}
crate::key_value_enum! {
	pub enum Checksum { 
		Clear = 0,
		Ok = 1,
	}
}
crate::key_value_enum! {
	pub enum FileFlags { 
		Read = 0x02,
		Write = 0x04,
		Erase = 0x08,
	}
}
crate::key_value_enum! {
	pub enum MesgCount { 
		NumPerFile = 0,
		MaxPerFile = 1,
		MaxPerFileType = 2,
	}
}
crate::key_value_enum! {
	pub enum DateTime { 
		Min = 0x10000000,
	}
}
crate::key_value_enum! {
	pub enum LocalDateTime { 
		Min = 0x10000000,
	}
}
crate::key_value_enum! {
	pub enum MessageIndex { 
		Selected = 0x8000,
		Reserved = 0x7000,
		Mask = 0x0FFF,
	}
}
crate::key_value_enum! {
	pub enum DeviceIndex { 
		Creator = 0,
	}
}
crate::key_value_enum! {
	pub enum Gender { 
		Female = 0,
		Male = 1,
	}
}
crate::key_value_enum! {
	pub enum Language { 
		English = 0,
		French = 1,
		Italian = 2,
		German = 3,
		Spanish = 4,
		Croatian = 5,
		Czech = 6,
		Danish = 7,
		Dutch = 8,
		Finnish = 9,
		Greek = 10,
		Hungarian = 11,
		Norwegian = 12,
		Polish = 13,
		Portuguese = 14,
		Slovakian = 15,
		Slovenian = 16,
		Swedish = 17,
		Russian = 18,
		Turkish = 19,
		Latvian = 20,
		Ukrainian = 21,
		Arabic = 22,
		Farsi = 23,
		Bulgarian = 24,
		Romanian = 25,
		Chinese = 26,
		Japanese = 27,
		Korean = 28,
		Taiwanese = 29,
		Thai = 30,
		Hebrew = 31,
		BrazilianPortuguese = 32,
		Indonesian = 33,
		Malaysian = 34,
		Vietnamese = 35,
		Burmese = 36,
		Mongolian = 37,
		Custom = 254,
	}
}
crate::key_value_enum! {
	pub enum LanguageBits0 { 
		English = 0x01,
		French = 0x02,
		Italian = 0x04,
		German = 0x08,
		Spanish = 0x10,
		Croatian = 0x20,
		Czech = 0x40,
		Danish = 0x80,
	}
}
crate::key_value_enum! {
	pub enum LanguageBitsOne { 
		Dutch = 0x01,
		Finnish = 0x02,
		Greek = 0x04,
		Hungarian = 0x08,
		Norwegian = 0x10,
		Polish = 0x20,
		Portuguese = 0x40,
		Slovakian = 0x80,
	}
}
crate::key_value_enum! {
	pub enum LanguageBitsTwo { 
		Slovenian = 0x01,
		Swedish = 0x02,
		Russian = 0x04,
		Turkish = 0x08,
		Latvian = 0x10,
		Ukrainian = 0x20,
		Arabic = 0x40,
		Farsi = 0x80,
	}
}
crate::key_value_enum! {
	pub enum LanguageBitsThree { 
		Bulgarian = 0x01,
		Romanian = 0x02,
		Chinese = 0x04,
		Japanese = 0x08,
		Korean = 0x10,
		Taiwanese = 0x20,
		Thai = 0x40,
		Hebrew = 0x80,
	}
}
crate::key_value_enum! {
	pub enum LanguageBitsFour { 
		BrazilianPortuguese = 0x01,
		Indonesian = 0x02,
		Malaysian = 0x04,
		Vietnamese = 0x08,
		Burmese = 0x10,
		Mongolian = 0x20,
	}
}
crate::key_value_enum! {
	pub enum TimeZone { 
		Almaty = 0,
		Bangkok = 1,
		Bombay = 2,
		Brasilia = 3,
		Cairo = 4,
		CapeVerdeIs = 5,
		Darwin = 6,
		Eniwetok = 7,
		Fiji = 8,
		HongKong = 9,
		Islamabad = 10,
		Kabul = 11,
		Magadan = 12,
		MidAtlantic = 13,
		Moscow = 14,
		Muscat = 15,
		Newfoundland = 16,
		Samoa = 17,
		Sydney = 18,
		Tehran = 19,
		Tokyo = 20,
		UsAlaska = 21,
		UsAtlantic = 22,
		UsCentral = 23,
		UsEastern = 24,
		UsHawaii = 25,
		UsMountain = 26,
		UsPacific = 27,
		Other = 28,
		Auckland = 29,
		Kathmandu = 30,
		EuropeWesternWet = 31,
		EuropeCentralCet = 32,
		EuropeEasternEet = 33,
		Jakarta = 34,
		Perth = 35,
		Adelaide = 36,
		Brisbane = 37,
		Tasmania = 38,
		Iceland = 39,
		Amsterdam = 40,
		Athens = 41,
		Barcelona = 42,
		Berlin = 43,
		Brussels = 44,
		Budapest = 45,
		Copenhagen = 46,
		Dublin = 47,
		Helsinki = 48,
		Lisbon = 49,
		London = 50,
		Madrid = 51,
		Munich = 52,
		Oslo = 53,
		Paris = 54,
		Prague = 55,
		Reykjavik = 56,
		Rome = 57,
		Stockholm = 58,
		Vienna = 59,
		Warsaw = 60,
		Zurich = 61,
		Quebec = 62,
		Ontario = 63,
		Manitoba = 64,
		Saskatchewan = 65,
		Alberta = 66,
		BritishColumbia = 67,
		Boise = 68,
		Boston = 69,
		Chicago = 70,
		Dallas = 71,
		Denver = 72,
		KansasCity = 73,
		LasVegas = 74,
		LosAngeles = 75,
		Miami = 76,
		Minneapolis = 77,
		NewYork = 78,
		NewOrleans = 79,
		Phoenix = 80,
		SantaFe = 81,
		Seattle = 82,
		WashingtonDc = 83,
		UsArizona = 84,
		Chita = 85,
		Ekaterinburg = 86,
		Irkutsk = 87,
		Kaliningrad = 88,
		Krasnoyarsk = 89,
		Novosibirsk = 90,
		PetropavlovskKamchatskiy = 91,
		Samara = 92,
		Vladivostok = 93,
		MexicoCentral = 94,
		MexicoMountain = 95,
		MexicoPacific = 96,
		CapeTown = 97,
		Winkhoek = 98,
		Lagos = 99,
		Riyahd = 100,
		Venezuela = 101,
		AustraliaLh = 102,
		Santiago = 103,
		Manual = 253,
		Automatic = 254,
	}
}
crate::key_value_enum! {
	pub enum DisplayMeasure { 
		Metric = 0,
		Statute = 1,
		Nautical = 2,
	}
}
crate::key_value_enum! {
	pub enum DisplayHeart { 
		Bpm = 0,
		Max = 1,
		Reserve = 2,
	}
}
crate::key_value_enum! {
	pub enum DisplayPower { 
		Watts = 0,
		PercentFtp = 1,
	}
}
crate::key_value_enum! {
	pub enum DisplayPosition { 
		Degree = 0,
		DegreeMinute = 1,
		DegreeMinuteSecond = 2,
		AustrianGrid = 3,
		BritishGrid = 4,
		DutchGrid = 5,
		HungarianGrid = 6,
		FinnishGrid = 7,
		GermanGrid = 8,
		IcelandicGrid = 9,
		IndonesianEquatorial = 10,
		IndonesianIrian = 11,
		IndonesianSouthern = 12,
		IndiaZone0 = 13,
		IndiaZoneIa = 14,
		IndiaZoneIb = 15,
		IndiaZoneIia = 16,
		IndiaZoneIib = 17,
		IndiaZoneIiia = 18,
		IndiaZoneIiib = 19,
		IndiaZoneIva = 20,
		IndiaZoneIvb = 21,
		IrishTransverse = 22,
		IrishGrid = 23,
		Loran = 24,
		MaidenheadGrid = 25,
		MgrsGrid = 26,
		NewZealandGrid = 27,
		NewZealandTransverse = 28,
		QatarGrid = 29,
		ModifiedSwedishGrid = 30,
		SwedishGrid = 31,
		SouthAfricanGrid = 32,
		SwissGrid = 33,
		TaiwanGrid = 34,
		UnitedStatesGrid = 35,
		UtmUpsGrid = 36,
		WestMalayan = 37,
		BorneoRso = 38,
		EstonianGrid = 39,
		LatvianGrid = 40,
		SwedishRefNinenineGrid = 41,
	}
}
crate::key_value_enum! {
	pub enum Switch { 
		Off = 0,
		On = 1,
		Auto = 2,
	}
}
crate::key_value_enum! {
	pub enum Sport { 
		Generic = 0,
		Running = 1,
		Cycling = 2,
		Transition = 3,
		FitnessEquipment = 4,
		Swimming = 5,
		Basketball = 6,
		Soccer = 7,
		Tennis = 8,
		AmericanFootball = 9,
		Training = 10,
		Walking = 11,
		CrossCountrySkiing = 12,
		AlpineSkiing = 13,
		Snowboarding = 14,
		Rowing = 15,
		Mountaineering = 16,
		Hiking = 17,
		Multisport = 18,
		Paddling = 19,
		Flying = 20,
		EBiking = 21,
		Motorcycling = 22,
		Boating = 23,
		Driving = 24,
		Golf = 25,
		HangGliding = 26,
		HorsebackRiding = 27,
		Hunting = 28,
		Fishing = 29,
		InlineSkating = 30,
		RockClimbing = 31,
		Sailing = 32,
		IceSkating = 33,
		SkyDiving = 34,
		Snowshoeing = 35,
		Snowmobiling = 36,
		StandUpPaddleboarding = 37,
		Surfing = 38,
		Wakeboarding = 39,
		WaterSkiing = 40,
		Kayaking = 41,
		Rafting = 42,
		Windsurfing = 43,
		Kitesurfing = 44,
		Tactical = 45,
		Jumpmaster = 46,
		Boxing = 47,
		FloorClimbing = 48,
		Baseball = 49,
		Diving = 53,
		Hiit = 62,
		Racket = 64,
		WheelchairPushWalk = 65,
		WheelchairPushRun = 66,
		Meditation = 67,
		DiscGolf = 69,
		Cricket = 71,
		Rugby = 72,
		Hockey = 73,
		Lacrosse = 74,
		Volleyball = 75,
		WaterTubing = 76,
		Wakesurfing = 77,
		MixedMartialArts = 80,
		Snorkeling = 82,
		Dance = 83,
		JumpRope = 84,
		All = 254,
	}
}
crate::key_value_enum! {
	pub enum SportBits0 { 
		Generic = 0x01,
		Running = 0x02,
		Cycling = 0x04,
		Transition = 0x08,
		FitnessEquipment = 0x10,
		Swimming = 0x20,
		Basketball = 0x40,
		Soccer = 0x80,
	}
}
crate::key_value_enum! {
	pub enum SportBitsOne { 
		Tennis = 0x01,
		AmericanFootball = 0x02,
		Training = 0x04,
		Walking = 0x08,
		CrossCountrySkiing = 0x10,
		AlpineSkiing = 0x20,
		Snowboarding = 0x40,
		Rowing = 0x80,
	}
}
crate::key_value_enum! {
	pub enum SportBitsTwo { 
		Mountaineering = 0x01,
		Hiking = 0x02,
		Multisport = 0x04,
		Paddling = 0x08,
		Flying = 0x10,
		EBiking = 0x20,
		Motorcycling = 0x40,
		Boating = 0x80,
	}
}
crate::key_value_enum! {
	pub enum SportBitsThree { 
		Driving = 0x01,
		Golf = 0x02,
		HangGliding = 0x04,
		HorsebackRiding = 0x08,
		Hunting = 0x10,
		Fishing = 0x20,
		InlineSkating = 0x40,
		RockClimbing = 0x80,
	}
}
crate::key_value_enum! {
	pub enum SportBitsFour { 
		Sailing = 0x01,
		IceSkating = 0x02,
		SkyDiving = 0x04,
		Snowshoeing = 0x08,
		Snowmobiling = 0x10,
		StandUpPaddleboarding = 0x20,
		Surfing = 0x40,
		Wakeboarding = 0x80,
	}
}
crate::key_value_enum! {
	pub enum SportBitsFive { 
		WaterSkiing = 0x01,
		Kayaking = 0x02,
		Rafting = 0x04,
		Windsurfing = 0x08,
		Kitesurfing = 0x10,
		Tactical = 0x20,
		Jumpmaster = 0x40,
		Boxing = 0x80,
	}
}
crate::key_value_enum! {
	pub enum SportBitsSix { 
		FloorClimbing = 0x01,
	}
}
crate::key_value_enum! {
	pub enum SubSport { 
		Generic = 0,
		Treadmill = 1,
		Street = 2,
		Trail = 3,
		Track = 4,
		Spin = 5,
		IndoorCycling = 6,
		Road = 7,
		Mountain = 8,
		Downhill = 9,
		Recumbent = 10,
		Cyclocross = 11,
		HandCycling = 12,
		TrackCycling = 13,
		IndoorRowing = 14,
		Elliptical = 15,
		StairClimbing = 16,
		LapSwimming = 17,
		OpenWater = 18,
		FlexibilityTraining = 19,
		StrengthTraining = 20,
		WarmUp = 21,
		Match = 22,
		Exercise = 23,
		Challenge = 24,
		IndoorSkiing = 25,
		CardioTraining = 26,
		IndoorWalking = 27,
		EBikeFitness = 28,
		Bmx = 29,
		CasualWalking = 30,
		SpeedWalking = 31,
		BikeToRunTransition = 32,
		RunToBikeTransition = 33,
		SwimToBikeTransition = 34,
		Atv = 35,
		Motocross = 36,
		Backcountry = 37,
		Resort = 38,
		RcDrone = 39,
		Wingsuit = 40,
		Whitewater = 41,
		SkateSkiing = 42,
		Yoga = 43,
		Pilates = 44,
		IndoorRunning = 45,
		GravelCycling = 46,
		EBikeMountain = 47,
		Commuting = 48,
		MixedSurface = 49,
		Navigate = 50,
		TrackMe = 51,
		Map = 52,
		SingleGasDiving = 53,
		MultiGasDiving = 54,
		GaugeDiving = 55,
		ApneaDiving = 56,
		ApneaHunting = 57,
		VirtualActivity = 58,
		Obstacle = 59,
		Breathing = 62,
		SailRace = 65,
		Ultra = 67,
		IndoorClimbing = 68,
		Bouldering = 69,
		Hiit = 70,
		Amrap = 73,
		Emom = 74,
		Tabata = 75,
		Pickleball = 84,
		Padel = 85,
		IndoorWheelchairWalk = 86,
		IndoorWheelchairRun = 87,
		IndoorHandCycling = 88,
		Squash = 94,
		Badminton = 95,
		Racquetball = 96,
		TableTennis = 97,
		FlyCanopy = 110,
		FlyParaglide = 111,
		FlyParamotor = 112,
		FlyPressurized = 113,
		FlyNavigate = 114,
		FlyTimer = 115,
		FlyAltimeter = 116,
		FlyWx = 117,
		FlyVfr = 118,
		FlyIfr = 119,
		All = 254,
	}
}
crate::key_value_enum! {
	pub enum SportEvent { 
		Uncategorized = 0,
		Geocaching = 1,
		Fitness = 2,
		Recreation = 3,
		Race = 4,
		SpecialEvent = 5,
		Training = 6,
		Transportation = 7,
		Touring = 8,
	}
}
crate::key_value_enum! {
	pub enum Activity { 
		Manual = 0,
		AutoMultiSport = 1,
	}
}
crate::key_value_enum! {
	pub enum Intensity { 
		Active = 0,
		Rest = 1,
		Warmup = 2,
		Cooldown = 3,
		Recovery = 4,
		Interval = 5,
		Other = 6,
	}
}
crate::key_value_enum! {
	pub enum SessionTrigger { 
		ActivityEnd = 0,
		Manual = 1,
		AutoMultiSport = 2,
		FitnessEquipment = 3,
	}
}
crate::key_value_enum! {
	pub enum AutolapTrigger { 
		Time = 0,
		Distance = 1,
		PositionStart = 2,
		PositionLap = 3,
		PositionWaypoint = 4,
		PositionMarked = 5,
		Off = 6,
	}
}
crate::key_value_enum! {
	pub enum LapTrigger { 
		Manual = 0,
		Time = 1,
		Distance = 2,
		PositionStart = 3,
		PositionLap = 4,
		PositionWaypoint = 5,
		PositionMarked = 6,
		SessionEnd = 7,
		FitnessEquipment = 8,
	}
}
crate::key_value_enum! {
	pub enum TimeMode { 
		Houronetwo = 0,
		Hourtwofour = 1,
		Military = 2,
		HourOnetwoWithSeconds = 3,
		HourTwofourWithSeconds = 4,
		Utc = 5,
	}
}
crate::key_value_enum! {
	pub enum BacklightMode { 
		Off = 0,
		Manual = 1,
		KeyAndMessages = 2,
		AutoBrightness = 3,
		SmartNotifications = 4,
		KeyAndMessagesNight = 5,
		KeyAndMessagesAndSmartNotifications = 6,
	}
}
crate::key_value_enum! {
	pub enum DateMode { 
		DayMonth = 0,
		MonthDay = 1,
	}
}
crate::key_value_enum! {
	pub enum BacklightTimeout { 
		Infinite = 0,
	}
}
crate::key_value_enum! {
	pub enum Event { 
		Timer = 0,
		Workout = 3,
		WorkoutStep = 4,
		PowerDown = 5,
		PowerUp = 6,
		OffCourse = 7,
		Session = 8,
		Lap = 9,
		CoursePoint = 10,
		Battery = 11,
		VirtualPartnerPace = 12,
		HrHighAlert = 13,
		HrLowAlert = 14,
		SpeedHighAlert = 15,
		SpeedLowAlert = 16,
		CadHighAlert = 17,
		CadLowAlert = 18,
		PowerHighAlert = 19,
		PowerLowAlert = 20,
		RecoveryHr = 21,
		BatteryLow = 22,
		TimeDurationAlert = 23,
		DistanceDurationAlert = 24,
		CalorieDurationAlert = 25,
		Activity = 26,
		FitnessEquipment = 27,
		Length = 28,
		UserMarker = 32,
		SportPoint = 33,
		Calibration = 36,
		FrontGearChange = 42,
		RearGearChange = 43,
		RiderPositionChange = 44,
		ElevHighAlert = 45,
		ElevLowAlert = 46,
		CommTimeout = 47,
		AutoActivityDetect = 54,
		DiveAlert = 56,
		DiveGasSwitched = 57,
		TankPressureReserve = 71,
		TankPressureCritical = 72,
		TankLost = 73,
		RadarThreatAlert = 75,
		TankBatteryLow = 76,
		TankPodConnected = 81,
		TankPodDisconnected = 82,
	}
}
crate::key_value_enum! {
	pub enum EventType { 
		Start = 0,
		Stop = 1,
		ConsecutiveDepreciated = 2,
		Marker = 3,
		StopAll = 4,
		BeginDepreciated = 5,
		EndDepreciated = 6,
		EndAllDepreciated = 7,
		StopDisable = 8,
		StopDisableAll = 9,
	}
}
crate::key_value_enum! {
	pub enum TimerTrigger { 
		Manual = 0,
		Auto = 1,
		FitnessEquipment = 2,
	}
}
crate::key_value_enum! {
	pub enum FitnessEquipmentState { 
		Ready = 0,
		InUse = 1,
		Paused = 2,
		Unknown = 3,
	}
}
crate::key_value_enum! {
	pub enum Tone { 
		Off = 0,
		Tone = 1,
		Vibrate = 2,
		ToneAndVibrate = 3,
	}
}
crate::key_value_enum! {
	pub enum Autoscroll { 
		None = 0,
		Slow = 1,
		Medium = 2,
		Fast = 3,
	}
}
crate::key_value_enum! {
	pub enum ActivityClass { 
		Level = 0x7F,
		LevelMax = 100,
		Athlete = 0x80,
	}
}
crate::key_value_enum! {
	pub enum HrZoneCalc { 
		Custom = 0,
		PercentMaxHr = 1,
		PercentHrr = 2,
		PercentLthr = 3,
	}
}
crate::key_value_enum! {
	pub enum PwrZoneCalc { 
		Custom = 0,
		PercentFtp = 1,
	}
}
crate::key_value_enum! {
	pub enum WktStepDuration { 
		Time = 0,
		Distance = 1,
		HrLessThan = 2,
		HrGreaterThan = 3,
		Calories = 4,
		Open = 5,
		RepeatUntilStepsCmplt = 6,
		RepeatUntilTime = 7,
		RepeatUntilDistance = 8,
		RepeatUntilCalories = 9,
		RepeatUntilHrLessThan = 10,
		RepeatUntilHrGreaterThan = 11,
		RepeatUntilPowerLessThan = 12,
		RepeatUntilPowerGreaterThan = 13,
		PowerLessThan = 14,
		PowerGreaterThan = 15,
		TrainingPeaksTss = 16,
		RepeatUntilPowerLastLapLessThan = 17,
		RepeatUntilMaxPowerLastLapLessThan = 18,
		PowerThreesLessThan = 19,
		PowerOne0SLessThan = 20,
		PowerThree0SLessThan = 21,
		PowerThreesGreaterThan = 22,
		PowerOne0SGreaterThan = 23,
		PowerThree0SGreaterThan = 24,
		PowerLapLessThan = 25,
		PowerLapGreaterThan = 26,
		RepeatUntilTrainingPeaksTss = 27,
		RepetitionTime = 28,
		Reps = 29,
		TimeOnly = 31,
	}
}
crate::key_value_enum! {
	pub enum WktStepTarget { 
		Speed = 0,
		HeartRate = 1,
		Open = 2,
		Cadence = 3,
		Power = 4,
		Grade = 5,
		Resistance = 6,
		PowerThrees = 7,
		PowerOne0S = 8,
		PowerThree0S = 9,
		PowerLap = 10,
		SwimStroke = 11,
		SpeedLap = 12,
		HeartRateLap = 13,
	}
}
crate::key_value_enum! {
	pub enum Goal { 
		Time = 0,
		Distance = 1,
		Calories = 2,
		Frequency = 3,
		Steps = 4,
		Ascent = 5,
		ActiveMinutes = 6,
	}
}
crate::key_value_enum! {
	pub enum GoalRecurrence { 
		Off = 0,
		Daily = 1,
		Weekly = 2,
		Monthly = 3,
		Yearly = 4,
		Custom = 5,
	}
}
crate::key_value_enum! {
	pub enum GoalSource { 
		Auto = 0,
		Community = 1,
		User = 2,
	}
}
crate::key_value_enum! {
	pub enum Schedule { 
		Workout = 0,
		Course = 1,
	}
}
crate::key_value_enum! {
	pub enum CoursePoint { 
		Generic = 0,
		Summit = 1,
		Valley = 2,
		Water = 3,
		Food = 4,
		Danger = 5,
		Left = 6,
		Right = 7,
		Straight = 8,
		FirstAid = 9,
		FourthCategory = 10,
		ThirdCategory = 11,
		SecondCategory = 12,
		FirstCategory = 13,
		HorsCategory = 14,
		Sprint = 15,
		LeftFork = 16,
		RightFork = 17,
		MiddleFork = 18,
		SlightLeft = 19,
		SharpLeft = 20,
		SlightRight = 21,
		SharpRight = 22,
		UTurn = 23,
		SegmentStart = 24,
		SegmentEnd = 25,
		Campsite = 27,
		AidStation = 28,
		RestArea = 29,
		GeneralDistance = 30,
		Service = 31,
		EnergyGel = 32,
		SportsDrink = 33,
		MileMarker = 34,
		Checkpoint = 35,
		Shelter = 36,
		MeetingSpot = 37,
		Overlook = 38,
		Toilet = 39,
		Shower = 40,
		Gear = 41,
		SharpCurve = 42,
		SteepIncline = 43,
		Tunnel = 44,
		Bridge = 45,
		Obstacle = 46,
		Crossing = 47,
		Store = 48,
		Transition = 49,
		Navaid = 50,
		Transport = 51,
		Alert = 52,
		Info = 53,
	}
}
crate::key_value_enum! {
	pub enum Manufacturer { 
		Garmin = 1,
		GarminFrfour0FiveAntfs = 2,
		Zephyr = 3,
		Dayton = 4,
		Idt = 5,
		Srm = 6,
		Quarq = 7,
		Ibike = 8,
		Saris = 9,
		SparkHk = 10,
		Tanita = 11,
		Echowell = 12,
		DynastreamOem = 13,
		Nautilus = 14,
		Dynastream = 15,
		Timex = 16,
		Metrigear = 17,
		Xelic = 18,
		Beurer = 19,
		Cardiosport = 20,
		AAndD = 21,
		Hmm = 22,
		Suunto = 23,
		ThitaElektronik = 24,
		Gpulse = 25,
		CleanMobile = 26,
		PedalBrain = 27,
		Peaksware = 28,
		Saxonar = 29,
		LemondFitness = 30,
		Dexcom = 31,
		WahooFitness = 32,
		OctaneFitness = 33,
		Archinoetics = 34,
		TheHurtBox = 35,
		CitizenSystems = 36,
		Magellan = 37,
		Osynce = 38,
		Holux = 39,
		Concepttwo = 40,
		Shimano = 41,
		OneGiantLeap = 42,
		AceSensor = 43,
		BrimBrothers = 44,
		Xplova = 45,
		PerceptionDigital = 46,
		Bfonesystems = 47,
		Pioneer = 48,
		Spantec = 49,
		Metalogics = 50,
		Fouriiiis = 51,
		SeikoEpson = 52,
		SeikoEpsonOem = 53,
		IforPowell = 54,
		MaxwellGuider = 55,
		StarTrac = 56,
		Breakaway = 57,
		AlatechTechnologyLtd = 58,
		MioTechnologyEurope = 59,
		Rotor = 60,
		Geonaute = 61,
		IdBike = 62,
		Specialized = 63,
		Wtek = 64,
		PhysicalEnterprises = 65,
		NorthPoleEngineering = 66,
		Bkool = 67,
		Cateye = 68,
		StagesCycling = 69,
		Sigmasport = 70,
		Tomtom = 71,
		Peripedal = 72,
		Wattbike = 73,
		Moxy = 76,
		Ciclosport = 77,
		Powerbahn = 78,
		AcornProjectsAps = 79,
		Lifebeam = 80,
		Bontrager = 81,
		Wellgo = 82,
		Scosche = 83,
		Magura = 84,
		Woodway = 85,
		Elite = 86,
		NielsenKellerman = 87,
		DkCity = 88,
		Tacx = 89,
		DirectionTechnology = 90,
		Magtonic = 91,
		Onepartcarbon = 92,
		InsideRideTechnologies = 93,
		SoundOfMotion = 94,
		Stryd = 95,
		Icg = 96,
		MiPulse = 97,
		BsxAthletics = 98,
		Look = 99,
		CampagnoloSrl = 100,
		BodyBikeSmart = 101,
		Praxisworks = 102,
		LimitsTechnology = 103,
		TopactionTechnology = 104,
		Cosinuss = 105,
		Fitcare = 106,
		Magene = 107,
		GiantManufacturingCo = 108,
		Tigrasport = 109,
		Salutron = 110,
		Technogym = 111,
		BrytonSensors = 112,
		LatitudeLimited = 113,
		SoaringTechnology = 114,
		Igpsport = 115,
		Thinkrider = 116,
		GopherSport = 117,
		Waterrower = 118,
		Orangetheory = 119,
		Inpeak = 120,
		Kinetic = 121,
		JohnsonHealthTech = 122,
		PolarElectro = 123,
		Seesense = 124,
		NciTechnology = 125,
		Iqsquare = 126,
		Leomo = 127,
		IfitCom = 128,
		CorosByte = 129,
		VersaDesign = 130,
		Chileaf = 131,
		Cycplus = 132,
		GravaaByte = 133,
		Sigeyi = 134,
		Coospo = 135,
		Geoid = 136,
		Bosch = 137,
		Kyto = 138,
		KineticSports = 139,
		DecathlonByte = 140,
		TqSystems = 141,
		TagHeuer = 142,
		KeiserFitness = 143,
		ZwiftByte = 144,
		PorscheEp = 145,
		Blackbird = 146,
		MeilanByte = 147,
		Ezon = 148,
		Laisi = 149,
		Myzone = 150,
		Development = 255,
		Healthandlife = 257,
		Lezyne = 258,
		ScribeLabs = 259,
		Zwift = 260,
		Watteam = 261,
		Recon = 262,
		FaveroElectronics = 263,
		Dynovelo = 264,
		Strava = 265,
		Precor = 266,
		Bryton = 267,
		Sram = 268,
		Navman = 269,
		Cobi = 270,
		Spivi = 271,
		MioMagellan = 272,
		Evesports = 273,
		SensitivusGauge = 274,
		Podoon = 275,
		LifeTimeFitness = 276,
		FalcoEMotors = 277,
		Minoura = 278,
		Cycliq = 279,
		Luxottica = 280,
		TrainerRoad = 281,
		TheSufferfest = 282,
		Fullspeedahead = 283,
		Virtualtraining = 284,
		Feedbacksports = 285,
		Omata = 286,
		Vdo = 287,
		Magneticdays = 288,
		Hammerhead = 289,
		KineticByKurt = 290,
		Shapelog = 291,
		Dabuziduo = 292,
		Jetblack = 293,
		Coros = 294,
		Virtugo = 295,
		Velosense = 296,
		Cycligentinc = 297,
		Trailforks = 298,
		MahleEbikemotion = 299,
		Nurvv = 300,
		Microprogram = 301,
		Zonefivecloud = 302,
		Greenteg = 303,
		YamahaMotors = 304,
		Whoop = 305,
		Gravaa = 306,
		Onelap = 307,
		MonarkExercise = 308,
		Form = 309,
		Decathlon = 310,
		Syncros = 311,
		Heatup = 312,
		Cannondale = 313,
		TrueFitness = 314,
		RgtCycling = 315,
		Vasa = 316,
		RaceRepublic = 317,
		Fazua = 318,
		OrekaTraining = 319,
		Lsec = 320,
		LululemonStudio = 321,
		Shanyue = 322,
		SpinningMda = 323,
		Hilldating = 324,
		AeroSensor = 325,
		Nike = 326,
		Magicshine = 327,
		Ictrainer = 328,
		Actigraphcorp = 5759,
	}
}
crate::key_value_enum! {
	pub enum GarminProduct { 
		Hrmone = 1,
		Axh0One = 2,
		Axb0One = 3,
		Axb0Two = 4,
		Hrmtwoss = 5,
		DsiAlf0Two = 6,
		Hrmthreess = 7,
		HrmRunSingleByteProductId = 8,
		Bsm = 9,
		Bcm = 10,
		Axs0One = 11,
		HrmTriSingleByteProductId = 12,
		HrmfourRunSingleByteProductId = 13,
		FrtwotwofiveSingleByteProductId = 14,
		GenthreeBsmSingleByteProductId = 15,
		GenthreeBcmSingleByteProductId = 16,
		HrmFitSingleByteProductId = 22,
		Ohr = 255,
		Frthree0OneChina = 473,
		Frthree0OneJapan = 474,
		Frthree0OneKorea = 475,
		Frthree0OneTaiwan = 494,
		Frfour0Five = 717,
		Frfive0 = 782,
		Frfour0FiveJapan = 987,
		Frsix0 = 988,
		DsiAlf0One = 1011,
		Frthreeone0Xt = 1018,
		Edgefive00 = 1036,
		Froneone0 = 1124,
		Edgeeight00 = 1169,
		Edgefive00Taiwan = 1199,
		Edgefive00Japan = 1213,
		Chirp = 1253,
		Froneone0Japan = 1274,
		Edgetwo00 = 1325,
		Frnineone0Xt = 1328,
		Edgeeight00Taiwan = 1333,
		Edgeeight00Japan = 1334,
		Alf0Four = 1341,
		Frsixone0 = 1345,
		Frtwoone0Japan = 1360,
		VectorSs = 1380,
		VectorCp = 1381,
		Edgeeight00China = 1386,
		Edgefive00China = 1387,
		ApproachGone0 = 1405,
		Frsixone0Japan = 1410,
		Edgefive00Korea = 1422,
		Frseven0 = 1436,
		Frthreeone0XtFourt = 1446,
		Amx = 1461,
		Frone0 = 1482,
		Edgeeight00Korea = 1497,
		Swim = 1499,
		Frnineone0XtChina = 1537,
		Fenix = 1551,
		Edgetwo00Taiwan = 1555,
		Edgefiveone0 = 1561,
		Edgeeightone0 = 1567,
		Tempe = 1570,
		Frnineone0XtJapan = 1600,
		Frsixtwo0 = 1623,
		Frtwotwo0 = 1632,
		Frnineone0XtKorea = 1664,
		Frone0Japan = 1688,
		Edgeeightone0Japan = 1721,
		VirbElite = 1735,
		EdgeTouring = 1736,
		Edgefiveone0Japan = 1742,
		HrmTri = 1743,
		HrmRun = 1752,
		Frninetwo0Xt = 1765,
		Edgefiveone0Asia = 1821,
		Edgeeightone0China = 1822,
		Edgeeightone0Taiwan = 1823,
		Edgeone000 = 1836,
		VivoFit = 1837,
		VirbRemote = 1853,
		VivoKi = 1885,
		Fronefive = 1903,
		VivoActive = 1907,
		Edgefiveone0Korea = 1918,
		Frsixtwo0Japan = 1928,
		Frsixtwo0China = 1929,
		Frtwotwo0Japan = 1930,
		Frtwotwo0China = 1931,
		ApproachSsix = 1936,
		VivoSmart = 1956,
		Fenixtwo = 1967,
		Epix = 1988,
		Fenixthree = 2050,
		Edgeone000Taiwan = 2052,
		Edgeone000Japan = 2053,
		FronefiveJapan = 2061,
		Edgefivetwo0 = 2067,
		Edgeone000China = 2070,
		Frsixtwo0Russia = 2072,
		Frtwotwo0Russia = 2073,
		VectorS = 2079,
		Edgeone000Korea = 2100,
		Frninetwo0XtTaiwan = 2130,
		Frninetwo0XtChina = 2131,
		Frninetwo0XtJapan = 2132,
		Virbx = 2134,
		VivoSmartApac = 2135,
		EtrexTouch = 2140,
		Edgetwofive = 2147,
		Frtwofive = 2148,
		VivoFittwo = 2150,
		Frtwotwofive = 2153,
		Frsixthree0 = 2156,
		Frtwothree0 = 2157,
		Frseventhreefivext = 2158,
		VivoActiveApac = 2160,
		VectorTwo = 2161,
		VectorTwos = 2162,
		Virbxe = 2172,
		Frsixtwo0Taiwan = 2173,
		Frtwotwo0Taiwan = 2174,
		Truswing = 2175,
		Dtwoairvenu = 2187,
		FenixthreeChina = 2188,
		FenixthreeTwn = 2189,
		VariaHeadlight = 2192,
		VariaTaillightOld = 2193,
		EdgeExploreOne000 = 2204,
		FrtwotwofiveAsia = 2219,
		VariaRadarTaillight = 2225,
		VariaRadarDisplay = 2226,
		Edgetwo0 = 2238,
		Edgefivetwo0Asia = 2260,
		Edgefivetwo0Japan = 2261,
		DtwoBravo = 2262,
		ApproachStwo0 = 2266,
		VivoSmarttwo = 2271,
		Edgeone000Thai = 2274,
		VariaRemote = 2276,
		EdgetwofiveAsia = 2288,
		EdgetwofiveJpn = 2289,
		Edgetwo0Asia = 2290,
		ApproachXfour0 = 2292,
		FenixthreeJapan = 2293,
		VivoSmartEmea = 2294,
		Frsixthree0Asia = 2310,
		Frsixthree0Jpn = 2311,
		Frtwothree0Jpn = 2313,
		HrmfourRun = 2327,
		EpixJapan = 2332,
		VivoActiveHr = 2337,
		VivoSmartGpsHr = 2347,
		VivoSmartHr = 2348,
		VivoSmartHrAsia = 2361,
		VivoSmartGpsHrAsia = 2362,
		VivoMove = 2368,
		VariaTaillight = 2379,
		FrtwothreefiveAsia = 2396,
		FrtwothreefiveJapan = 2397,
		VariaVision = 2398,
		VivoFitthree = 2406,
		FenixthreeKorea = 2407,
		FenixthreeSea = 2408,
		FenixthreeHr = 2413,
		VirbUltraThree0 = 2417,
		IndexSmartScale = 2429,
		Frtwothreefive = 2431,
		FenixthreeChronos = 2432,
		Oregonsevenxx = 2441,
		Rinosevenxx = 2444,
		EpixKorea = 2457,
		FenixthreeHrChn = 2473,
		FenixthreeHrTwn = 2474,
		FenixthreeHrJpn = 2475,
		FenixthreeHrSea = 2476,
		FenixthreeHrKor = 2477,
		Nautix = 2496,
		VivoActiveHrApac = 2497,
		Frthreefive = 2503,
		OregonsevenxxWw = 2512,
		EdgeEighttwo0 = 2530,
		EdgeExploreEighttwo0 = 2531,
		FrseventhreefivextApac = 2533,
		FrseventhreefivextJapan = 2534,
		Fenixfives = 2544,
		DtwoBravoTitanium = 2547,
		VariaUteight00 = 2567,
		RunningDynamicsPod = 2593,
		EdgeEighttwo0China = 2599,
		EdgeEighttwo0Japan = 2600,
		Fenixfivex = 2604,
		VivoFitJr = 2606,
		VivoSmartthree = 2622,
		VivoSport = 2623,
		EdgeEighttwo0Taiwan = 2628,
		EdgeEighttwo0Korea = 2629,
		EdgeEighttwo0Sea = 2630,
		FrthreefiveHebrew = 2650,
		ApproachSsix0 = 2656,
		FrthreefiveApac = 2667,
		FrthreefiveJapan = 2668,
		FenixthreeChronosAsia = 2675,
		VirbThreesix0 = 2687,
		Frninethreefive = 2691,
		Fenixfive = 2697,
		Vivoactivethree = 2700,
		FrtwothreefiveChinaNfc = 2733,
		ForetrexSix0OneSeven0One = 2769,
		VivoMoveHr = 2772,
		EdgeOne0Three0 = 2713,
		FrthreefiveSea = 2727,
		VectorThree = 2787,
		FenixfiveAsia = 2796,
		FenixfivesAsia = 2797,
		FenixfivexAsia = 2798,
		ApproachZeight0 = 2806,
		FrthreefiveKorea = 2814,
		Dtwocharlie = 2819,
		VivoSmartthreeApac = 2831,
		VivoSportApac = 2832,
		FrninethreefiveAsia = 2833,
		Descent = 2859,
		VivoFitfour = 2878,
		Frsixfourfive = 2886,
		Frsixfourfivem = 2888,
		Frthree0 = 2891,
		FenixfivesPlus = 2900,
		EdgeOnethree0 = 2909,
		EdgeOne0Three0Asia = 2924,
		VivosmartFour = 2927,
		VivoMoveHrAsia = 2945,
		ApproachXone0 = 2962,
		Frthree0Asia = 2977,
		VivoactivethreemW = 2988,
		FrsixfourfiveAsia = 3003,
		FrsixfourfivemAsia = 3004,
		EdgeExplore = 3011,
		Gpsmapsixsix = 3028,
		ApproachSone0 = 3049,
		VivoactivethreemL = 3066,
		ApproachGeight0 = 3085,
		EdgeOnethree0Asia = 3092,
		EdgeOne0Three0Bontrager = 3095,
		FenixfivePlus = 3110,
		FenixfivexPlus = 3111,
		EdgeFivetwo0Plus = 3112,
		Frninefourfive = 3113,
		EdgeFivethree0 = 3121,
		EdgeEightthree0 = 3122,
		InstinctEsports = 3126,
		FenixfivesPlusApac = 3134,
		FenixfivexPlusApac = 3135,
		EdgeFivetwo0PlusApac = 3142,
		DescentTone = 3143,
		FrtwothreefivelAsia = 3144,
		FrtwofourfiveAsia = 3145,
		VivoActivethreemApac = 3163,
		GenthreeBsm = 3192,
		GenthreeBcm = 3193,
		VivoSmartfourAsia = 3218,
		VivoactivefourSmall = 3224,
		VivoactivefourLarge = 3225,
		Venu = 3226,
		MarqDriver = 3246,
		MarqAviator = 3247,
		MarqCaptain = 3248,
		MarqCommander = 3249,
		MarqExpedition = 3250,
		MarqAthlete = 3251,
		DescentMktwo = 3258,
		Gpsmapsixsixi = 3284,
		FenixsixSSport = 3287,
		FenixsixS = 3288,
		FenixsixSport = 3289,
		Fenixsix = 3290,
		Fenixsixx = 3291,
		HrmDual = 3299,
		HrmPro = 3300,
		VivoMovethreePremium = 3308,
		ApproachSfour0 = 3314,
		FrtwofourfivemAsia = 3321,
		EdgeFivethree0Apac = 3349,
		EdgeEightthree0Apac = 3350,
		VivoMovethree = 3378,
		VivoActivefourSmallAsia = 3387,
		VivoActivefourLargeAsia = 3388,
		VivoActivefourOledAsia = 3389,
		Swimtwo = 3405,
		MarqDriverAsia = 3420,
		MarqAviatorAsia = 3421,
		VivoMovethreeAsia = 3422,
		FrninefourfiveAsia = 3441,
		VivoActivethreetChn = 3446,
		MarqCaptainAsia = 3448,
		MarqCommanderAsia = 3449,
		MarqExpeditionAsia = 3450,
		MarqAthleteAsia = 3451,
		InstinctSolar = 3466,
		FrfourfiveAsia = 3469,
		VivoactivethreeDaimler = 3473,
		LegacyRey = 3498,
		LegacyDarthVader = 3499,
		LegacyCaptainMarvel = 3500,
		LegacyFirstAvenger = 3501,
		FenixsixsSportAsia = 3512,
		FenixsixsAsia = 3513,
		FenixsixSportAsia = 3514,
		FenixsixAsia = 3515,
		FenixsixxAsia = 3516,
		LegacyCaptainMarvelAsia = 3535,
		LegacyFirstAvengerAsia = 3536,
		LegacyReyAsia = 3537,
		LegacyDarthVaderAsia = 3538,
		DescentMktwos = 3542,
		EdgeOnethree0Plus = 3558,
		EdgeOne0Three0Plus = 3570,
		RallyTwo00 = 3578,
		Frsevenfourfive = 3589,
		Venusq = 3600,
		Lily = 3615,
		MarqAdventurer = 3624,
		Enduro = 3638,
		SwimtwoApac = 3639,
		MarqAdventurerAsia = 3648,
		FrninefourfiveLte = 3652,
		DescentMktwoAsia = 3702,
		Venutwo = 3703,
		Venutwos = 3704,
		VenuDaimlerAsia = 3737,
		MarqGolfer = 3739,
		VenuDaimler = 3740,
		FrsevenfourfiveAsia = 3794,
		VariaRctsevenonefive = 3808,
		LilyAsia = 3809,
		EdgeOne0Three0PlusAsia = 3812,
		EdgeOnethree0PlusAsia = 3813,
		ApproachSonetwo = 3823,
		EnduroAsia = 3872,
		VenusqAsia = 3837,
		EdgeOne0Four0 = 3843,
		MarqGolferAsia = 3850,
		VenutwoPlus = 3851,
		Gnss = 3865,
		Frfivefive = 3869,
		InstinctTwo = 3888,
		Fenixsevens = 3905,
		Fenixseven = 3906,
		Fenixsevenx = 3907,
		FenixsevensApac = 3908,
		FenixsevenApac = 3909,
		FenixsevenxApac = 3910,
		ApproachGonetwo =  3927,
		DescentMktwosAsia = 3930,
		ApproachSfourtwo = 3934,
		EpixGentwo = 3943,
		EpixGentwoApac = 3944,
		VenutwosAsia = 3949,
		VenutwoAsia = 3950,
		FrninefourfiveLteAsia = 3978,
		VivoMoveSport = 3982,
		VivomoveTrend = 3983,
		ApproachSonetwoAsia = 3986,
		FrtwofivefiveMusic = 3990,
		FrtwofivefiveSmallMusic = 3991,
		Frtwofivefive = 3992,
		FrtwofivefiveSmall = 3993,
		ApproachGonetwoAsia =  4001,
		ApproachSfourtwoAsia = 4002,
		DescentGone = 4005,
		VenutwoPlusAsia = 4017,
		Frninefivefive = 4024,
		FrfivefiveAsia = 4033,
		EdgeFivefour0 = 4061,
		EdgeEightfour0 = 4062,
		VivosmartFive = 4063,
		InstinctTwoAsia = 4071,
		MarqGentwo = 4105,
		Venusqtwo = 4115,
		Venusqtwomusic = 4116,
		MarqGentwoAviator = 4124,
		DtwoAirXone0 = 4125,
		HrmProPlus = 4130,
		DescentGoneAsia = 4132,
		Tactixseven = 4135,
		InstinctCrossover = 4155,
		EdgeExploretwo = 4169,
		DescentMkthree = 4222,
		DescentMkthreei = 4223,
		ApproachSseven0 = 4233,
		FrtwosixfiveLarge = 4257,
		FrtwosixfiveSmall = 4258,
		Venuthree = 4260,
		Venuthrees = 4261,
		TacxNeoSmart = 4265,
		TacxNeotwoSmart = 4266,
		TacxNeotwoTSmart = 4267,
		TacxNeoSmartBike = 4268,
		TacxSatoriSmart = 4269,
		TacxFlowSmart = 4270,
		TacxVortexSmart = 4271,
		TacxBushidoSmart = 4272,
		TacxGeniusSmart = 4273,
		TacxFluxFluxSSmart = 4274,
		TacxFluxtwoSmart = 4275,
		TacxMagnum = 4276,
		EdgeOne0Four0Asia = 4305,
		EpixGentwoProFourtwo = 4312,
		EpixGentwoProFourseven = 4313,
		EpixGentwoProFiveone = 4314,
		Frninesixfive = 4315,
		Endurotwo = 4341,
		FenixsevensProSolar = 4374,
		FenixsevenProSolar = 4375,
		FenixsevenxProSolar = 4376,
		Lilytwo = 4380,
		InstinctTwox = 4394,
		Vivoactivefive = 4426,
		DescentTtwo = 4442,
		HrmFit = 4446,
		MarqGentwoCommander = 4472,
		DtwoMachonePro = 4556,
		Sdmfour = 10007,
		EdgeRemote = 10014,
		TacxTrainingAppWin = 20533,
		TacxTrainingAppMac = 20534,
		TacxTrainingAppMacCatalyst = 20565,
		TrainingCenter = 20119,
		TacxTrainingAppAndroid = 30045,
		TacxTrainingAppIos = 30046,
		TacxTrainingAppLegacy = 30047,
		ConnectiqSimulator = 65531,
		AndroidAntplusPlugin = 65532,
		Connect = 65534,
	}
}
crate::key_value_enum! {
	pub enum AntplusDeviceType { 
		Antfs = 1,
		BikePower = 11,
		EnvironmentSensorLegacy = 12,
		MultiSportSpeedDistance = 15,
		Control = 16,
		FitnessEquipment = 17,
		BloodPressure = 18,
		GeocacheNode = 19,
		LightElectricVehicle = 20,
		EnvSensor = 25,
		Racquet = 26,
		ControlHub = 27,
		MuscleOxygen = 31,
		Shifting = 34,
		BikeLightMain = 35,
		BikeLightShared = 36,
		Exd = 38,
		BikeRadar = 40,
		BikeAero = 46,
		WeightScale = 119,
		HeartRate = 120,
		BikeSpeedCadence = 121,
		BikeCadence = 122,
		BikeSpeed = 123,
		StrideSpeedDistance = 124,
	}
}
crate::key_value_enum! {
	pub enum AntNetwork { 
		Public = 0,
		Antplus = 1,
		Antfs = 2,
		Private = 3,
	}
}
crate::key_value_enum! {
	pub enum WorkoutCapabilities { 
		Interval = 0x00000001,
		Custom = 0x00000002,
		FitnessEquipment = 0x00000004,
		Firstbeat = 0x00000008,
		NewLeaf = 0x00000010,
		Tcx = 0x00000020,
		Speed = 0x00000080,
		HeartRate = 0x00000100,
		Distance = 0x00000200,
		Cadence = 0x00000400,
		Power = 0x00000800,
		Grade = 0x00001000,
		Resistance = 0x00002000,
		Protected = 0x00004000,
	}
}
crate::key_value_enum! {
	pub enum BatteryStatus { 
		New = 1,
		Good = 2,
		Ok = 3,
		Low = 4,
		Critical = 5,
		Charging = 6,
		Unknown = 7,
	}
}
crate::key_value_enum! {
	pub enum HrType { 
		Normal = 0,
		Irregular = 1,
	}
}
crate::key_value_enum! {
	pub enum CourseCapabilities { 
		Processed = 0x00000001,
		Valid = 0x00000002,
		Time = 0x00000004,
		Distance = 0x00000008,
		Position = 0x00000010,
		HeartRate = 0x00000020,
		Power = 0x00000040,
		Cadence = 0x00000080,
		Training = 0x00000100,
		Navigation = 0x00000200,
		Bikeway = 0x00000400,
		Aviation = 0x00001000,
	}
}
crate::key_value_enum! {
	pub enum Weight { 
		Calculating = 0xFFFE,
	}
}
crate::key_value_enum! {
	pub enum WorkoutHr { 
		BpmOffset = 100,
	}
}
crate::key_value_enum! {
	pub enum WorkoutPower { 
		WattsOffset = 1000,
	}
}
crate::key_value_enum! {
	pub enum BpStatus { 
		NoError = 0,
		ErrorIncompleteData = 1,
		ErrorNoMeasurement = 2,
		ErrorDataOutOfRange = 3,
		ErrorIrregularHeartRate = 4,
	}
}
crate::key_value_enum! {
	pub enum UserLocalId { 
		LocalMin = 0x0000,
		LocalMax = 0x000F,
		StationaryMin = 0x0010,
		StationaryMax = 0x00FF,
		PortableMin = 0x0100,
		PortableMax = 0xFFFE,
	}
}
crate::key_value_enum! {
	pub enum SwimStroke { 
		Freestyle = 0,
		Backstroke = 1,
		Breaststroke = 2,
		Butterfly = 3,
		Drill = 4,
		Mixed = 5,
		Im = 6,
	}
}
crate::key_value_enum! {
	pub enum ActivityType { 
		Generic = 0,
		Running = 1,
		Cycling = 2,
		Transition = 3,
		FitnessEquipment = 4,
		Swimming = 5,
		Walking = 6,
		Sedentary = 8,
		All = 254,
	}
}
crate::key_value_enum! {
	pub enum ActivitySubtype { 
		Generic = 0,
		Treadmill = 1,
		Street = 2,
		Trail = 3,
		Track = 4,
		Spin = 5,
		IndoorCycling = 6,
		Road = 7,
		Mountain = 8,
		Downhill = 9,
		Recumbent = 10,
		Cyclocross = 11,
		HandCycling = 12,
		TrackCycling = 13,
		IndoorRowing = 14,
		Elliptical = 15,
		StairClimbing = 16,
		LapSwimming = 17,
		OpenWater = 18,
		All = 254,
	}
}
crate::key_value_enum! {
	pub enum ActivityLevel { 
		Low = 0,
		Medium = 1,
		High = 2,
	}
}
crate::key_value_enum! {
	pub enum Side { 
		Right = 0,
		Left = 1,
	}
}
crate::key_value_enum! {
	pub enum LeftRightBalance { 
		Mask = 0x7F,
		Right = 0x80,
	}
}
crate::key_value_enum! {
	pub enum LeftRightBalanceOne00 { 
		Mask = 0x3FFF,
		Right = 0x8000,
	}
}
crate::key_value_enum! {
	pub enum LengthType { 
		Idle = 0,
		Active = 1,
	}
}
crate::key_value_enum! {
	pub enum DayOfWeek { 
		Sunday = 0,
		Monday = 1,
		Tuesday = 2,
		Wednesday = 3,
		Thursday = 4,
		Friday = 5,
		Saturday = 6,
	}
}
crate::key_value_enum! {
	pub enum ConnectivityCapabilities { 
		Bluetooth = 0x00000001,
		BluetoothLe = 0x00000002,
		Ant = 0x00000004,
		ActivityUpload = 0x00000008,
		CourseDownload = 0x00000010,
		WorkoutDownload = 0x00000020,
		LiveTrack = 0x00000040,
		WeatherConditions = 0x00000080,
		WeatherAlerts = 0x00000100,
		GpsEphemerisDownload = 0x00000200,
		ExplicitArchive = 0x00000400,
		SetupIncomplete = 0x00000800,
		ContinueSyncAfterSoftwareUpdate = 0x00001000,
		ConnectIqAppDownload = 0x00002000,
		GolfCourseDownload = 0x00004000,
		DeviceInitiatesSync = 0x00008000,
		ConnectIqWatchAppDownload = 0x00010000,
		ConnectIqWidgetDownload = 0x00020000,
		ConnectIqWatchFaceDownload = 0x00040000,
		ConnectIqDataFieldDownload = 0x00080000,
		ConnectIqAppManagment = 0x00100000,
		SwingSensor = 0x00200000,
		SwingSensorRemote = 0x00400000,
		IncidentDetection = 0x00800000,
		AudioPrompts = 0x01000000,
		WifiVerification = 0x02000000,
		TrueUp = 0x04000000,
		FindMyWatch = 0x08000000,
		RemoteManualSync = 0x10000000,
		LiveTrackAutoStart = 0x20000000,
		LiveTrackMessaging = 0x40000000,
		InstantInput = 0x80000000,
	}
}
crate::key_value_enum! {
	pub enum WeatherReport { 
		Current = 0,
		Forecast = 1,
		DailyForecast = 2,
	}
}
crate::key_value_enum! {
	pub enum WeatherStatus { 
		Clear = 0,
		PartlyCloudy = 1,
		MostlyCloudy = 2,
		Rain = 3,
		Snow = 4,
		Windy = 5,
		Thunderstorms = 6,
		WintryMix = 7,
		Fog = 8,
		Hazy = 11,
		Hail = 12,
		ScatteredShowers = 13,
		ScatteredThunderstorms = 14,
		UnknownPrecipitation = 15,
		LightRain = 16,
		HeavyRain = 17,
		LightSnow = 18,
		HeavySnow = 19,
		LightRainSnow = 20,
		HeavyRainSnow = 21,
		Cloudy = 22,
	}
}
crate::key_value_enum! {
	pub enum WeatherSeverity { 
		Unknown = 0,
		Warning = 1,
		Watch = 2,
		Advisory = 3,
		Statement = 4,
	}
}
crate::key_value_enum! {
	pub enum WeatherSevereType { 
		Unspecified = 0,
		Tornado = 1,
		Tsunami = 2,
		Hurricane = 3,
		ExtremeWind = 4,
		Typhoon = 5,
		InlandHurricane = 6,
		HurricaneForceWind = 7,
		Waterspout = 8,
		SevereThunderstorm = 9,
		WreckhouseWinds = 10,
		LesSuetesWind = 11,
		Avalanche = 12,
		FlashFlood = 13,
		TropicalStorm = 14,
		InlandTropicalStorm = 15,
		Blizzard = 16,
		IceStorm = 17,
		FreezingRain = 18,
		DebrisFlow = 19,
		FlashFreeze = 20,
		DustStorm = 21,
		HighWind = 22,
		WinterStorm = 23,
		HeavyFreezingSpray = 24,
		ExtremeCold = 25,
		WindChill = 26,
		ColdWave = 27,
		HeavySnowAlert = 28,
		LakeEffectBlowingSnow = 29,
		SnowSquall = 30,
		LakeEffectSnow = 31,
		WinterWeather = 32,
		Sleet = 33,
		Snowfall = 34,
		SnowAndBlowingSnow = 35,
		BlowingSnow = 36,
		SnowAlert = 37,
		ArcticOutflow = 38,
		FreezingDrizzle = 39,
		Storm = 40,
		StormSurge = 41,
		Rainfall = 42,
		ArealFlood = 43,
		CoastalFlood = 44,
		LakeshoreFlood = 45,
		ExcessiveHeat = 46,
		Heat = 47,
		Weather = 48,
		HighHeatAndHumidity = 49,
		HumidexAndHealth = 50,
		Humidex = 51,
		Gale = 52,
		FreezingSpray = 53,
		SpecialMarine = 54,
		Squall = 55,
		StrongWind = 56,
		LakeWind = 57,
		MarineWeather = 58,
		Wind = 59,
		SmallCraftHazardousSeas = 60,
		HazardousSeas = 61,
		SmallCraft = 62,
		SmallCraftWinds = 63,
		SmallCraftRoughBar = 64,
		HighWaterLevel = 65,
		Ashfall = 66,
		FreezingFog = 67,
		DenseFog = 68,
		DenseSmoke = 69,
		BlowingDust = 70,
		HardFreeze = 71,
		Freeze = 72,
		Frost = 73,
		FireWeather = 74,
		Flood = 75,
		RipTide = 76,
		HighSurf = 77,
		Smog = 78,
		AirQuality = 79,
		BriskWind = 80,
		AirStagnation = 81,
		LowWater = 82,
		Hydrological = 83,
		SpecialWeather = 84,
	}
}
crate::key_value_enum! {
	pub enum TimeIntoDay { 
	}
}
crate::key_value_enum! {
	pub enum LocaltimeIntoDay { 
	}
}
crate::key_value_enum! {
	pub enum StrokeType { 
		NoEvent = 0,
		Other = 1,
		Serve = 2,
		Forehand = 3,
		Backhand = 4,
		Smash = 5,
	}
}
crate::key_value_enum! {
	pub enum BodyLocation { 
		LeftLeg = 0,
		LeftCalf = 1,
		LeftShin = 2,
		LeftHamstring = 3,
		LeftQuad = 4,
		LeftGlute = 5,
		RightLeg = 6,
		RightCalf = 7,
		RightShin = 8,
		RightHamstring = 9,
		RightQuad = 10,
		RightGlute = 11,
		TorsoBack = 12,
		LeftLowerBack = 13,
		LeftUpperBack = 14,
		RightLowerBack = 15,
		RightUpperBack = 16,
		TorsoFront = 17,
		LeftAbdomen = 18,
		LeftChest = 19,
		RightAbdomen = 20,
		RightChest = 21,
		LeftArm = 22,
		LeftShoulder = 23,
		LeftBicep = 24,
		LeftTricep = 25,
		LeftBrachioradialis = 26,
		LeftForearmExtensors = 27,
		RightArm = 28,
		RightShoulder = 29,
		RightBicep = 30,
		RightTricep = 31,
		RightBrachioradialis = 32,
		RightForearmExtensors = 33,
		Neck = 34,
		Throat = 35,
		WaistMidBack = 36,
		WaistFront = 37,
		WaistLeft = 38,
		WaistRight = 39,
	}
}
crate::key_value_enum! {
	pub enum SegmentLapStatus { 
		End = 0,
		Fail = 1,
	}
}
crate::key_value_enum! {
	pub enum SegmentLeaderboardType { 
		Overall = 0,
		PersonalBest = 1,
		Connections = 2,
		Group = 3,
		Challenger = 4,
		Kom = 5,
		Qom = 6,
		Pr = 7,
		Goal = 8,
		Rival = 9,
		ClubLeader = 10,
	}
}
crate::key_value_enum! {
	pub enum SegmentDeleteStatus { 
		DoNotDelete = 0,
		DeleteOne = 1,
		DeleteAll = 2,
	}
}
crate::key_value_enum! {
	pub enum SegmentSelectionType { 
		Starred = 0,
		Suggested = 1,
	}
}
crate::key_value_enum! {
	pub enum SourceType { 
		Ant = 0,
		Antplus = 1,
		Bluetooth = 2,
		BluetoothLowEnergy = 3,
		Wifi = 4,
		Local = 5,
	}
}
crate::key_value_enum! {
	pub enum LocalDeviceType { 
		Gps = 0,
		Glonass = 1,
		GpsGlonass = 2,
		Accelerometer = 3,
		Barometer = 4,
		Temperature = 5,
		Whr = 10,
		SensorHub = 12,
	}
}
crate::key_value_enum! {
	pub enum BleDeviceType { 
		ConnectedGps = 0,
		HeartRate = 1,
		BikePower = 2,
		BikeSpeedCadence = 3,
		BikeSpeed = 4,
		BikeCadence = 5,
		Footpod = 6,
		BikeTrainer = 7,
	}
}
crate::key_value_enum! {
	pub enum AntChannelId { 
		AntExtendedDeviceNumberUpperNibble = 0xF0000000,
		AntTransmissionTypeLowerNibble = 0x0F000000,
		AntDeviceType = 0x00FF0000,
		AntDeviceNumber = 0x0000FFFF,
	}
}
crate::key_value_enum! {
	pub enum DisplayOrientation { 
		Auto = 0,
		Portrait = 1,
		Landscape = 2,
		PortraitFlipped = 3,
		LandscapeFlipped = 4,
	}
}
crate::key_value_enum! {
	pub enum WorkoutEquipment { 
		None = 0,
		SwimFins = 1,
		SwimKickboard = 2,
		SwimPaddles = 3,
		SwimPullBuoy = 4,
		SwimSnorkel = 5,
	}
}
crate::key_value_enum! {
	pub enum WatchfaceMode { 
		Digital = 0,
		Analog = 1,
		ConnectIq = 2,
		Disabled = 3,
	}
}
crate::key_value_enum! {
	pub enum DigitalWatchfaceLayout { 
		Traditional = 0,
		Modern = 1,
		Bold = 2,
	}
}
crate::key_value_enum! {
	pub enum AnalogWatchfaceLayout { 
		Minimal = 0,
		Traditional = 1,
		Modern = 2,
	}
}
crate::key_value_enum! {
	pub enum RiderPositionType { 
		Seated = 0,
		Standing = 1,
		TransitionToSeated = 2,
		TransitionToStanding = 3,
	}
}
crate::key_value_enum! {
	pub enum PowerPhaseType { 
		PowerPhaseStartAngle = 0,
		PowerPhaseEndAngle = 1,
		PowerPhaseArcLength = 2,
		PowerPhaseCenter = 3,
	}
}
crate::key_value_enum! {
	pub enum CameraEventType { 
		VideoStart = 0,
		VideoSplit = 1,
		VideoEnd = 2,
		PhotoTaken = 3,
		VideoSecondStreamStart = 4,
		VideoSecondStreamSplit = 5,
		VideoSecondStreamEnd = 6,
		VideoSplitStart = 7,
		VideoSecondStreamSplitStart = 8,
		VideoPause = 11,
		VideoSecondStreamPause = 12,
		VideoResume = 13,
		VideoSecondStreamResume = 14,
	}
}
crate::key_value_enum! {
	pub enum SensorType { 
		Accelerometer = 0,
		Gyroscope = 1,
		Compass = 2,
		Barometer = 3,
	}
}
crate::key_value_enum! {
	pub enum BikeLightNetworkConfigType { 
		Auto = 0,
		Individual = 4,
		HighVisibility = 5,
		Trail = 6,
	}
}
crate::key_value_enum! {
	pub enum CommTimeoutType { 
		WildcardPairingTimeout = 0,
		PairingTimeout = 1,
		ConnectionLost = 2,
		ConnectionTimeout = 3,
	}
}
crate::key_value_enum! {
	pub enum CameraOrientationType { 
		CameraOrientation0 = 0,
		CameraOrientationNine0 = 1,
		CameraOrientationOneeight0 = 2,
		CameraOrientationTwoseven0 = 3,
	}
}
crate::key_value_enum! {
	pub enum AttitudeStage { 
		Failed = 0,
		Aligning = 1,
		Degraded = 2,
		Valid = 3,
	}
}
crate::key_value_enum! {
	pub enum AttitudeValidity { 
		TrackAngleHeadingValid = 0x0001,
		PitchValid = 0x0002,
		RollValid = 0x0004,
		LateralBodyAccelValid = 0x0008,
		NormalBodyAccelValid = 0x0010,
		TurnRateValid = 0x0020,
		HwFail = 0x0040,
		MagInvalid = 0x0080,
		NoGps = 0x0100,
		GpsInvalid = 0x0200,
		SolutionCoasting = 0x0400,
		TrueTrackAngle = 0x0800,
		MagneticHeading = 0x1000,
	}
}
crate::key_value_enum! {
	pub enum AutoSyncFrequency { 
		Never = 0,
		Occasionally = 1,
		Frequent = 2,
		OnceADay = 3,
		Remote = 4,
	}
}
crate::key_value_enum! {
	pub enum ExdLayout { 
		FullScreen = 0,
		HalfVertical = 1,
		HalfHorizontal = 2,
		HalfVerticalRightSplit = 3,
		HalfHorizontalBottomSplit = 4,
		FullQuarterSplit = 5,
		HalfVerticalLeftSplit = 6,
		HalfHorizontalTopSplit = 7,
		Dynamic = 8,
	}
}
crate::key_value_enum! {
	pub enum ExdDisplayType { 
		Numerical = 0,
		Simple = 1,
		Graph = 2,
		Bar = 3,
		CircleGraph = 4,
		VirtualPartner = 5,
		Balance = 6,
		StringList = 7,
		String = 8,
		SimpleDynamicIcon = 9,
		Gauge = 10,
	}
}
crate::key_value_enum! {
	pub enum ExdDataUnits { 
		NoUnits = 0,
		Laps = 1,
		MilesPerHour = 2,
		KilometersPerHour = 3,
		FeetPerHour = 4,
		MetersPerHour = 5,
		DegreesCelsius = 6,
		DegreesFarenheit = 7,
		Zone = 8,
		Gear = 9,
		Rpm = 10,
		Bpm = 11,
		Degrees = 12,
		Millimeters = 13,
		Meters = 14,
		Kilometers = 15,
		Feet = 16,
		Yards = 17,
		Kilofeet = 18,
		Miles = 19,
		Time = 20,
		EnumTurnType = 21,
		Percent = 22,
		Watts = 23,
		WattsPerKilogram = 24,
		EnumBatteryStatus = 25,
		EnumBikeLightBeamAngleMode = 26,
		EnumBikeLightBatteryStatus = 27,
		EnumBikeLightNetworkConfigType = 28,
		Lights = 29,
		Seconds = 30,
		Minutes = 31,
		Hours = 32,
		Calories = 33,
		Kilojoules = 34,
		Milliseconds = 35,
		SecondPerMile = 36,
		SecondPerKilometer = 37,
		Centimeter = 38,
		EnumCoursePoint = 39,
		Bradians = 40,
		EnumSport = 41,
		InchesHg = 42,
		MmHg = 43,
		Mbars = 44,
		HectoPascals = 45,
		FeetPerMin = 46,
		MetersPerMin = 47,
		MetersPerSec = 48,
		EightCardinal = 49,
	}
}
crate::key_value_enum! {
	pub enum ExdQualifiers { 
		NoQualifier = 0,
		Instantaneous = 1,
		Average = 2,
		Lap = 3,
		Maximum = 4,
		MaximumAverage = 5,
		MaximumLap = 6,
		LastLap = 7,
		AverageLap = 8,
		ToDestination = 9,
		ToGo = 10,
		ToNext = 11,
		NextCoursePoint = 12,
		Total = 13,
		ThreeSecondAverage = 14,
		TenSecondAverage = 15,
		ThirtySecondAverage = 16,
		PercentMaximum = 17,
		PercentMaximumAverage = 18,
		LapPercentMaximum = 19,
		Elapsed = 20,
		Sunrise = 21,
		Sunset = 22,
		ComparedToVirtualPartner = 23,
		MaximumTwofourh = 24,
		MinimumTwofourh = 25,
		Minimum = 26,
		First = 27,
		Second = 28,
		Third = 29,
		Shifter = 30,
		LastSport = 31,
		Moving = 32,
		Stopped = 33,
		EstimatedTotal = 34,
		ZoneNine = 242,
		ZoneEight = 243,
		ZoneSeven = 244,
		ZoneSix = 245,
		ZoneFive = 246,
		ZoneFour = 247,
		ZoneThree = 248,
		ZoneTwo = 249,
		ZoneOne = 250,
	}
}
crate::key_value_enum! {
	pub enum ExdDescriptors { 
		BikeLightBatteryStatus = 0,
		BeamAngleStatus = 1,
		BateryLevel = 2,
		LightNetworkMode = 3,
		NumberLightsConnected = 4,
		Cadence = 5,
		Distance = 6,
		EstimatedTimeOfArrival = 7,
		Heading = 8,
		Time = 9,
		BatteryLevel = 10,
		TrainerResistance = 11,
		TrainerTargetPower = 12,
		TimeSeated = 13,
		TimeStanding = 14,
		Elevation = 15,
		Grade = 16,
		Ascent = 17,
		Descent = 18,
		VerticalSpeed = 19,
		DitwoBatteryLevel = 20,
		FrontGear = 21,
		RearGear = 22,
		GearRatio = 23,
		HeartRate = 24,
		HeartRateZone = 25,
		TimeInHeartRateZone = 26,
		HeartRateReserve = 27,
		Calories = 28,
		GpsAccuracy = 29,
		GpsSignalStrength = 30,
		Temperature = 31,
		TimeOfDay = 32,
		Balance = 33,
		PedalSmoothness = 34,
		Power = 35,
		FunctionalThresholdPower = 36,
		IntensityFactor = 37,
		Work = 38,
		PowerRatio = 39,
		NormalizedPower = 40,
		TrainingStressScore = 41,
		TimeOnZone = 42,
		Speed = 43,
		Laps = 44,
		Reps = 45,
		WorkoutStep = 46,
		CourseDistance = 47,
		NavigationDistance = 48,
		CourseEstimatedTimeOfArrival = 49,
		NavigationEstimatedTimeOfArrival = 50,
		CourseTime = 51,
		NavigationTime = 52,
		CourseHeading = 53,
		NavigationHeading = 54,
		PowerZone = 55,
		TorqueEffectiveness = 56,
		TimerTime = 57,
		PowerWeightRatio = 58,
		LeftPlatformCenterOffset = 59,
		RightPlatformCenterOffset = 60,
		LeftPowerPhaseStartAngle = 61,
		RightPowerPhaseStartAngle = 62,
		LeftPowerPhaseFinishAngle = 63,
		RightPowerPhaseFinishAngle = 64,
		Gears = 65,
		Pace = 66,
		TrainingEffect = 67,
		VerticalOscillation = 68,
		VerticalRatio = 69,
		GroundContactTime = 70,
		LeftGroundContactTimeBalance = 71,
		RightGroundContactTimeBalance = 72,
		StrideLength = 73,
		RunningCadence = 74,
		PerformanceCondition = 75,
		CourseType = 76,
		TimeInPowerZone = 77,
		NavigationTurn = 78,
		CourseLocation = 79,
		NavigationLocation = 80,
		Compass = 81,
		GearCombo = 82,
		MuscleOxygen = 83,
		Icon = 84,
		CompassHeading = 85,
		GpsHeading = 86,
		GpsElevation = 87,
		AnaerobicTrainingEffect = 88,
		Course = 89,
		OffCourse = 90,
		GlideRatio = 91,
		VerticalDistance = 92,
		Vmg = 93,
		AmbientPressure = 94,
		Pressure = 95,
		Vam = 96,
	}
}
crate::key_value_enum! {
	pub enum AutoActivityDetect { 
		None = 0x00000000,
		Running = 0x00000001,
		Cycling = 0x00000002,
		Swimming = 0x00000004,
		Walking = 0x00000008,
		Elliptical = 0x00000020,
		Sedentary = 0x00000400,
	}
}
crate::key_value_enum! {
	pub enum SupportedExdScreenLayouts { 
		FullScreen = 0x00000001,
		HalfVertical = 0x00000002,
		HalfHorizontal = 0x00000004,
		HalfVerticalRightSplit = 0x00000008,
		HalfHorizontalBottomSplit = 0x00000010,
		FullQuarterSplit = 0x00000020,
		HalfVerticalLeftSplit = 0x00000040,
		HalfHorizontalTopSplit = 0x00000080,
	}
}
crate::key_value_enum! {
	pub enum FitBaseType { 
		Enum = 0,
		Sinteight = 1,
		Uinteight = 2,
		Sintonesix = 131,
		Uintonesix = 132,
		Sintthreetwo = 133,
		Uintthreetwo = 134,
		String = 7,
		Floatthreetwo = 136,
		Floatsixfour = 137,
		Uinteightz = 10,
		Uintonesixz = 139,
		Uintthreetwoz = 140,
		Byte = 13,
		Sintsixfour = 142,
		Uintsixfour = 143,
		Uintsixfourz = 144,
	}
}
crate::key_value_enum! {
	pub enum TurnType { 
		ArrivingIdx = 0,
		ArrivingLeftIdx = 1,
		ArrivingRightIdx = 2,
		ArrivingViaIdx = 3,
		ArrivingViaLeftIdx = 4,
		ArrivingViaRightIdx = 5,
		BearKeepLeftIdx = 6,
		BearKeepRightIdx = 7,
		ContinueIdx = 8,
		ExitLeftIdx = 9,
		ExitRightIdx = 10,
		FerryIdx = 11,
		RoundaboutFourfiveIdx = 12,
		RoundaboutNine0Idx = 13,
		RoundaboutOnethreefiveIdx = 14,
		RoundaboutOneeight0Idx = 15,
		RoundaboutTwotwofiveIdx = 16,
		RoundaboutTwoseven0Idx = 17,
		RoundaboutThreeonefiveIdx = 18,
		RoundaboutThreesix0Idx = 19,
		RoundaboutNegFourfiveIdx = 20,
		RoundaboutNegNine0Idx = 21,
		RoundaboutNegOnethreefiveIdx = 22,
		RoundaboutNegOneeight0Idx = 23,
		RoundaboutNegTwotwofiveIdx = 24,
		RoundaboutNegTwoseven0Idx = 25,
		RoundaboutNegThreeonefiveIdx = 26,
		RoundaboutNegThreesix0Idx = 27,
		RoundaboutGenericIdx = 28,
		RoundaboutNegGenericIdx = 29,
		SharpTurnLeftIdx = 30,
		SharpTurnRightIdx = 31,
		TurnLeftIdx = 32,
		TurnRightIdx = 33,
		UturnLeftIdx = 34,
		UturnRightIdx = 35,
		IconInvIdx = 36,
		IconIdxCnt = 37,
	}
}
crate::key_value_enum! {
	pub enum BikeLightBeamAngleMode { 
		Manual = 0,
		Auto = 1,
	}
}
crate::key_value_enum! {
	pub enum FitBaseUnit { 
		Other = 0,
		Kilogram = 1,
		Pound = 2,
	}
}
crate::key_value_enum! {
	pub enum SetType { 
		Rest = 0,
		Active = 1,
	}
}
crate::key_value_enum! {
	pub enum MaxMetCategory { 
		Generic = 0,
		Cycling = 1,
	}
}
crate::key_value_enum! {
	pub enum ExerciseCategory { 
		BenchPress = 0,
		CalfRaise = 1,
		Cardio = 2,
		Carry = 3,
		Chop = 4,
		Core = 5,
		Crunch = 6,
		Curl = 7,
		Deadlift = 8,
		Flye = 9,
		HipRaise = 10,
		HipStability = 11,
		HipSwing = 12,
		Hyperextension = 13,
		LateralRaise = 14,
		LegCurl = 15,
		LegRaise = 16,
		Lunge = 17,
		OlympicLift = 18,
		Plank = 19,
		Plyo = 20,
		PullUp = 21,
		PushUp = 22,
		Row = 23,
		ShoulderPress = 24,
		ShoulderStability = 25,
		Shrug = 26,
		SitUp = 27,
		Squat = 28,
		TotalBody = 29,
		TricepsExtension = 30,
		WarmUp = 31,
		Run = 32,
		Unknown = 65534,
	}
}
crate::key_value_enum! {
	pub enum BenchPressExerciseName { 
		AlternatingDumbbellChestPressOnSwissBall = 0,
		BarbellBenchPress = 1,
		BarbellBoardBenchPress = 2,
		BarbellFloorPress = 3,
		CloseGripBarbellBenchPress = 4,
		DeclineDumbbellBenchPress = 5,
		DumbbellBenchPress = 6,
		DumbbellFloorPress = 7,
		InclineBarbellBenchPress = 8,
		InclineDumbbellBenchPress = 9,
		InclineSmithMachineBenchPress = 10,
		IsometricBarbellBenchPress = 11,
		KettlebellChestPress = 12,
		NeutralGripDumbbellBenchPress = 13,
		NeutralGripDumbbellInclineBenchPress = 14,
		OneArmFloorPress = 15,
		WeightedOneArmFloorPress = 16,
		PartialLockout = 17,
		ReverseGripBarbellBenchPress = 18,
		ReverseGripInclineBenchPress = 19,
		SingleArmCableChestPress = 20,
		SingleArmDumbbellBenchPress = 21,
		SmithMachineBenchPress = 22,
		SwissBallDumbbellChestPress = 23,
		TripleStopBarbellBenchPress = 24,
		WideGripBarbellBenchPress = 25,
		AlternatingDumbbellChestPress = 26,
	}
}
crate::key_value_enum! {
	pub enum CalfRaiseExerciseName { 
		ThreeWayCalfRaise = 0,
		ThreeWayWeightedCalfRaise = 1,
		ThreeWaySingleLegCalfRaise = 2,
		ThreeWayWeightedSingleLegCalfRaise = 3,
		DonkeyCalfRaise = 4,
		WeightedDonkeyCalfRaise = 5,
		SeatedCalfRaise = 6,
		WeightedSeatedCalfRaise = 7,
		SeatedDumbbellToeRaise = 8,
		SingleLegBentKneeCalfRaise = 9,
		WeightedSingleLegBentKneeCalfRaise = 10,
		SingleLegDeclinePushUp = 11,
		SingleLegDonkeyCalfRaise = 12,
		WeightedSingleLegDonkeyCalfRaise = 13,
		SingleLegHipRaiseWithKneeHold = 14,
		SingleLegStandingCalfRaise = 15,
		SingleLegStandingDumbbellCalfRaise = 16,
		StandingBarbellCalfRaise = 17,
		StandingCalfRaise = 18,
		WeightedStandingCalfRaise = 19,
		StandingDumbbellCalfRaise = 20,
	}
}
crate::key_value_enum! {
	pub enum CardioExerciseName { 
		BobAndWeaveCircle = 0,
		WeightedBobAndWeaveCircle = 1,
		CardioCoreCrawl = 2,
		WeightedCardioCoreCrawl = 3,
		DoubleUnder = 4,
		WeightedDoubleUnder = 5,
		JumpRope = 6,
		WeightedJumpRope = 7,
		JumpRopeCrossover = 8,
		WeightedJumpRopeCrossover = 9,
		JumpRopeJog = 10,
		WeightedJumpRopeJog = 11,
		JumpingJacks = 12,
		WeightedJumpingJacks = 13,
		SkiMoguls = 14,
		WeightedSkiMoguls = 15,
		SplitJacks = 16,
		WeightedSplitJacks = 17,
		SquatJacks = 18,
		WeightedSquatJacks = 19,
		TripleUnder = 20,
		WeightedTripleUnder = 21,
	}
}
crate::key_value_enum! {
	pub enum CarryExerciseName { 
		BarHolds = 0,
		FarmersWalk = 1,
		FarmersWalkOnToes = 2,
		HexDumbbellHold = 3,
		OverheadCarry = 4,
	}
}
crate::key_value_enum! {
	pub enum ChopExerciseName { 
		CablePullThrough = 0,
		CableRotationalLift = 1,
		CableWoodchop = 2,
		CrossChopToKnee = 3,
		WeightedCrossChopToKnee = 4,
		DumbbellChop = 5,
		HalfKneelingRotation = 6,
		WeightedHalfKneelingRotation = 7,
		HalfKneelingRotationalChop = 8,
		HalfKneelingRotationalReverseChop = 9,
		HalfKneelingStabilityChop = 10,
		HalfKneelingStabilityReverseChop = 11,
		KneelingRotationalChop = 12,
		KneelingRotationalReverseChop = 13,
		KneelingStabilityChop = 14,
		KneelingWoodchopper = 15,
		MedicineBallWoodChops = 16,
		PowerSquatChops = 17,
		WeightedPowerSquatChops = 18,
		StandingRotationalChop = 19,
		StandingSplitRotationalChop = 20,
		StandingSplitRotationalReverseChop = 21,
		StandingStabilityReverseChop = 22,
	}
}
crate::key_value_enum! {
	pub enum CoreExerciseName { 
		AbsJabs = 0,
		WeightedAbsJabs = 1,
		AlternatingPlateReach = 2,
		BarbellRollout = 3,
		WeightedBarbellRollout = 4,
		BodyBarObliqueTwist = 5,
		CableCorePress = 6,
		CableSideBend = 7,
		SideBend = 8,
		WeightedSideBend = 9,
		CrescentCircle = 10,
		WeightedCrescentCircle = 11,
		CyclingRussianTwist = 12,
		WeightedCyclingRussianTwist = 13,
		ElevatedFeetRussianTwist = 14,
		WeightedElevatedFeetRussianTwist = 15,
		HalfTurkishGetUp = 16,
		KettlebellWindmill = 17,
		KneelingAbWheel = 18,
		WeightedKneelingAbWheel = 19,
		ModifiedFrontLever = 20,
		OpenKneeTucks = 21,
		WeightedOpenKneeTucks = 22,
		SideAbsLegLift = 23,
		WeightedSideAbsLegLift = 24,
		SwissBallJackknife = 25,
		WeightedSwissBallJackknife = 26,
		SwissBallPike = 27,
		WeightedSwissBallPike = 28,
		SwissBallRollout = 29,
		WeightedSwissBallRollout = 30,
		TriangleHipPress = 31,
		WeightedTriangleHipPress = 32,
		TrxSuspendedJackknife = 33,
		WeightedTrxSuspendedJackknife = 34,
		UBoat = 35,
		WeightedUBoat = 36,
		WindmillSwitches = 37,
		WeightedWindmillSwitches = 38,
		AlternatingSlideOut = 39,
		WeightedAlternatingSlideOut = 40,
		GhdBackExtensions = 41,
		WeightedGhdBackExtensions = 42,
		OverheadWalk = 43,
		Inchworm = 44,
		WeightedModifiedFrontLever = 45,
		RussianTwist = 46,
		AbdominalLegRotations = 47,
		ArmAndLegExtensionOnKnees = 48,
		Bicycle = 49,
		BicepCurlWithLegExtension = 50,
		CatCow = 51,
		Corkscrew = 52,
		CrissCross = 53,
		CrissCrossWithBall = 54,
		DoubleLegStretch = 55,
		KneeFolds = 56,
		LowerLift = 57,
		NeckPull = 58,
		PelvicClocks = 59,
		RollOver = 60,
		RollUp = 61,
		Rolling = 62,
		RowingOne = 63,
		RowingTwo = 64,
		Scissors = 65,
		SingleLegCircles = 66,
		SingleLegStretch = 67,
		SnakeTwistOneAndTwo = 68,
		Swan = 69,
		Swimming = 70,
		Teaser = 71,
		TheHundred = 72,
	}
}
crate::key_value_enum! {
	pub enum CrunchExerciseName { 
		BicycleCrunch = 0,
		CableCrunch = 1,
		CircularArmCrunch = 2,
		CrossedArmsCrunch = 3,
		WeightedCrossedArmsCrunch = 4,
		CrossLegReverseCrunch = 5,
		WeightedCrossLegReverseCrunch = 6,
		CrunchChop = 7,
		WeightedCrunchChop = 8,
		DoubleCrunch = 9,
		WeightedDoubleCrunch = 10,
		ElbowToKneeCrunch = 11,
		WeightedElbowToKneeCrunch = 12,
		FlutterKicks = 13,
		WeightedFlutterKicks = 14,
		FoamRollerReverseCrunchOnBench = 15,
		WeightedFoamRollerReverseCrunchOnBench = 16,
		FoamRollerReverseCrunchWithDumbbell = 17,
		FoamRollerReverseCrunchWithMedicineBall = 18,
		FrogPress = 19,
		HangingKneeRaiseObliqueCrunch = 20,
		WeightedHangingKneeRaiseObliqueCrunch = 21,
		HipCrossover = 22,
		WeightedHipCrossover = 23,
		HollowRock = 24,
		WeightedHollowRock = 25,
		InclineReverseCrunch = 26,
		WeightedInclineReverseCrunch = 27,
		KneelingCableCrunch = 28,
		KneelingCrossCrunch = 29,
		WeightedKneelingCrossCrunch = 30,
		KneelingObliqueCableCrunch = 31,
		KneesToElbow = 32,
		LegExtensions = 33,
		WeightedLegExtensions = 34,
		LegLevers = 35,
		McgillCurlUp = 36,
		WeightedMcgillCurlUp = 37,
		ModifiedPilatesRollUpWithBall = 38,
		WeightedModifiedPilatesRollUpWithBall = 39,
		PilatesCrunch = 40,
		WeightedPilatesCrunch = 41,
		PilatesRollUpWithBall = 42,
		WeightedPilatesRollUpWithBall = 43,
		RaisedLegsCrunch = 44,
		WeightedRaisedLegsCrunch = 45,
		ReverseCrunch = 46,
		WeightedReverseCrunch = 47,
		ReverseCrunchOnABench = 48,
		WeightedReverseCrunchOnABench = 49,
		ReverseCurlAndLift = 50,
		WeightedReverseCurlAndLift = 51,
		RotationalLift = 52,
		WeightedRotationalLift = 53,
		SeatedAlternatingReverseCrunch = 54,
		WeightedSeatedAlternatingReverseCrunch = 55,
		SeatedLegU = 56,
		WeightedSeatedLegU = 57,
		SideToSideCrunchAndWeave = 58,
		WeightedSideToSideCrunchAndWeave = 59,
		SingleLegReverseCrunch = 60,
		WeightedSingleLegReverseCrunch = 61,
		SkaterCrunchCross = 62,
		WeightedSkaterCrunchCross = 63,
		StandingCableCrunch = 64,
		StandingSideCrunch = 65,
		StepClimb = 66,
		WeightedStepClimb = 67,
		SwissBallCrunch = 68,
		SwissBallReverseCrunch = 69,
		WeightedSwissBallReverseCrunch = 70,
		SwissBallRussianTwist = 71,
		WeightedSwissBallRussianTwist = 72,
		SwissBallSideCrunch = 73,
		WeightedSwissBallSideCrunch = 74,
		ThoracicCrunchesOnFoamRoller = 75,
		WeightedThoracicCrunchesOnFoamRoller = 76,
		TricepsCrunch = 77,
		WeightedBicycleCrunch = 78,
		WeightedCrunch = 79,
		WeightedSwissBallCrunch = 80,
		ToesToBar = 81,
		WeightedToesToBar = 82,
		Crunch = 83,
		StraightLegCrunchWithBall = 84,
	}
}
crate::key_value_enum! {
	pub enum CurlExerciseName { 
		AlternatingDumbbellBicepsCurl = 0,
		AlternatingDumbbellBicepsCurlOnSwissBall = 1,
		AlternatingInclineDumbbellBicepsCurl = 2,
		BarbellBicepsCurl = 3,
		BarbellReverseWristCurl = 4,
		BarbellWristCurl = 5,
		BehindTheBackBarbellReverseWristCurl = 6,
		BehindTheBackOneArmCableCurl = 7,
		CableBicepsCurl = 8,
		CableHammerCurl = 9,
		CheatingBarbellBicepsCurl = 10,
		CloseGripEzBarBicepsCurl = 11,
		CrossBodyDumbbellHammerCurl = 12,
		DeadHangBicepsCurl = 13,
		DeclineHammerCurl = 14,
		DumbbellBicepsCurlWithStaticHold = 15,
		DumbbellHammerCurl = 16,
		DumbbellReverseWristCurl = 17,
		DumbbellWristCurl = 18,
		EzBarPreacherCurl = 19,
		ForwardBendBicepsCurl = 20,
		HammerCurlToPress = 21,
		InclineDumbbellBicepsCurl = 22,
		InclineOffsetThumbDumbbellCurl = 23,
		KettlebellBicepsCurl = 24,
		LyingConcentrationCableCurl = 25,
		OneArmPreacherCurl = 26,
		PlatePinchCurl = 27,
		PreacherCurlWithCable = 28,
		ReverseEzBarCurl = 29,
		ReverseGripWristCurl = 30,
		ReverseGripBarbellBicepsCurl = 31,
		SeatedAlternatingDumbbellBicepsCurl = 32,
		SeatedDumbbellBicepsCurl = 33,
		SeatedReverseDumbbellCurl = 34,
		SplitStanceOffsetPinkyDumbbellCurl = 35,
		StandingAlternatingDumbbellCurls = 36,
		StandingDumbbellBicepsCurl = 37,
		StandingEzBarBicepsCurl = 38,
		StaticCurl = 39,
		SwissBallDumbbellOverheadTricepsExtension = 40,
		SwissBallEzBarPreacherCurl = 41,
		TwistingStandingDumbbellBicepsCurl = 42,
		WideGripEzBarBicepsCurl = 43,
	}
}
crate::key_value_enum! {
	pub enum DeadliftExerciseName { 
		BarbellDeadlift = 0,
		BarbellStraightLegDeadlift = 1,
		DumbbellDeadlift = 2,
		DumbbellSingleLegDeadliftToRow = 3,
		DumbbellStraightLegDeadlift = 4,
		KettlebellFloorToShelf = 5,
		OneArmOneLegDeadlift = 6,
		RackPull = 7,
		RotationalDumbbellStraightLegDeadlift = 8,
		SingleArmDeadlift = 9,
		SingleLegBarbellDeadlift = 10,
		SingleLegBarbellStraightLegDeadlift = 11,
		SingleLegDeadliftWithBarbell = 12,
		SingleLegRdlCircuit = 13,
		SingleLegRomanianDeadliftWithDumbbell = 14,
		SumoDeadlift = 15,
		SumoDeadliftHighPull = 16,
		TrapBarDeadlift = 17,
		WideGripBarbellDeadlift = 18,
	}
}
crate::key_value_enum! {
	pub enum FlyeExerciseName { 
		CableCrossover = 0,
		DeclineDumbbellFlye = 1,
		DumbbellFlye = 2,
		InclineDumbbellFlye = 3,
		KettlebellFlye = 4,
		KneelingRearFlye = 5,
		SingleArmStandingCableReverseFlye = 6,
		SwissBallDumbbellFlye = 7,
		ArmRotations = 8,
		HugATree = 9,
	}
}
crate::key_value_enum! {
	pub enum HipRaiseExerciseName { 
		BarbellHipThrustOnFloor = 0,
		BarbellHipThrustWithBench = 1,
		BentKneeSwissBallReverseHipRaise = 2,
		WeightedBentKneeSwissBallReverseHipRaise = 3,
		BridgeWithLegExtension = 4,
		WeightedBridgeWithLegExtension = 5,
		ClamBridge = 6,
		FrontKickTabletop = 7,
		WeightedFrontKickTabletop = 8,
		HipExtensionAndCross = 9,
		WeightedHipExtensionAndCross = 10,
		HipRaise = 11,
		WeightedHipRaise = 12,
		HipRaiseWithFeetOnSwissBall = 13,
		WeightedHipRaiseWithFeetOnSwissBall = 14,
		HipRaiseWithHeadOnBosuBall = 15,
		WeightedHipRaiseWithHeadOnBosuBall = 16,
		HipRaiseWithHeadOnSwissBall = 17,
		WeightedHipRaiseWithHeadOnSwissBall = 18,
		HipRaiseWithKneeSqueeze = 19,
		WeightedHipRaiseWithKneeSqueeze = 20,
		InclineRearLegExtension = 21,
		WeightedInclineRearLegExtension = 22,
		KettlebellSwing = 23,
		MarchingHipRaise = 24,
		WeightedMarchingHipRaise = 25,
		MarchingHipRaiseWithFeetOnASwissBall = 26,
		WeightedMarchingHipRaiseWithFeetOnASwissBall = 27,
		ReverseHipRaise = 28,
		WeightedReverseHipRaise = 29,
		SingleLegHipRaise = 30,
		WeightedSingleLegHipRaise = 31,
		SingleLegHipRaiseWithFootOnBench = 32,
		WeightedSingleLegHipRaiseWithFootOnBench = 33,
		SingleLegHipRaiseWithFootOnBosuBall = 34,
		WeightedSingleLegHipRaiseWithFootOnBosuBall = 35,
		SingleLegHipRaiseWithFootOnFoamRoller = 36,
		WeightedSingleLegHipRaiseWithFootOnFoamRoller = 37,
		SingleLegHipRaiseWithFootOnMedicineBall = 38,
		WeightedSingleLegHipRaiseWithFootOnMedicineBall = 39,
		SingleLegHipRaiseWithHeadOnBosuBall = 40,
		WeightedSingleLegHipRaiseWithHeadOnBosuBall = 41,
		WeightedClamBridge = 42,
		SingleLegSwissBallHipRaiseAndLegCurl = 43,
		Clams = 44,
		InnerThighCircles = 45,
		InnerThighSideLift = 46,
		LegCircles = 47,
		LegLift = 48,
		LegLiftInExternalRotation = 49,
	}
}
crate::key_value_enum! {
	pub enum HipStabilityExerciseName { 
		BandSideLyingLegRaise = 0,
		DeadBug = 1,
		WeightedDeadBug = 2,
		ExternalHipRaise = 3,
		WeightedExternalHipRaise = 4,
		FireHydrantKicks = 5,
		WeightedFireHydrantKicks = 6,
		HipCircles = 7,
		WeightedHipCircles = 8,
		InnerThighLift = 9,
		WeightedInnerThighLift = 10,
		LateralWalksWithBandAtAnkles = 11,
		PretzelSideKick = 12,
		WeightedPretzelSideKick = 13,
		ProneHipInternalRotation = 14,
		WeightedProneHipInternalRotation = 15,
		Quadruped = 16,
		QuadrupedHipExtension = 17,
		WeightedQuadrupedHipExtension = 18,
		QuadrupedWithLegLift = 19,
		WeightedQuadrupedWithLegLift = 20,
		SideLyingLegRaise = 21,
		WeightedSideLyingLegRaise = 22,
		SlidingHipAdduction = 23,
		WeightedSlidingHipAdduction = 24,
		StandingAdduction = 25,
		WeightedStandingAdduction = 26,
		StandingCableHipAbduction = 27,
		StandingHipAbduction = 28,
		WeightedStandingHipAbduction = 29,
		StandingRearLegRaise = 30,
		WeightedStandingRearLegRaise = 31,
		SupineHipInternalRotation = 32,
		WeightedSupineHipInternalRotation = 33,
	}
}
crate::key_value_enum! {
	pub enum HipSwingExerciseName { 
		SingleArmKettlebellSwing = 0,
		SingleArmDumbbellSwing = 1,
		StepOutSwing = 2,
	}
}
crate::key_value_enum! {
	pub enum HyperextensionExerciseName { 
		BackExtensionWithOppositeArmAndLegReach = 0,
		WeightedBackExtensionWithOppositeArmAndLegReach = 1,
		BaseRotations = 2,
		WeightedBaseRotations = 3,
		BentKneeReverseHyperextension = 4,
		WeightedBentKneeReverseHyperextension = 5,
		HollowHoldAndRoll = 6,
		WeightedHollowHoldAndRoll = 7,
		Kicks = 8,
		WeightedKicks = 9,
		KneeRaises = 10,
		WeightedKneeRaises = 11,
		KneelingSuperman = 12,
		WeightedKneelingSuperman = 13,
		LatPullDownWithRow = 14,
		MedicineBallDeadliftToReach = 15,
		OneArmOneLegRow = 16,
		OneArmRowWithBand = 17,
		OverheadLungeWithMedicineBall = 18,
		PlankKneeTucks = 19,
		WeightedPlankKneeTucks = 20,
		SideStep = 21,
		WeightedSideStep = 22,
		SingleLegBackExtension = 23,
		WeightedSingleLegBackExtension = 24,
		SpineExtension = 25,
		WeightedSpineExtension = 26,
		StaticBackExtension = 27,
		WeightedStaticBackExtension = 28,
		SupermanFromFloor = 29,
		WeightedSupermanFromFloor = 30,
		SwissBallBackExtension = 31,
		WeightedSwissBallBackExtension = 32,
		SwissBallHyperextension = 33,
		WeightedSwissBallHyperextension = 34,
		SwissBallOppositeArmAndLegLift = 35,
		WeightedSwissBallOppositeArmAndLegLift = 36,
		SupermanOnSwissBall = 37,
		Cobra = 38,
		SupineFloorBarre = 39,
	}
}
crate::key_value_enum! {
	pub enum LateralRaiseExerciseName { 
		FourfiveDegreeCableExternalRotation = 0,
		AlternatingLateralRaiseWithStaticHold = 1,
		BarMuscleUp = 2,
		BentOverLateralRaise = 3,
		CableDiagonalRaise = 4,
		CableFrontRaise = 5,
		CalorieRow = 6,
		ComboShoulderRaise = 7,
		DumbbellDiagonalRaise = 8,
		DumbbellVRaise = 9,
		FrontRaise = 10,
		LeaningDumbbellLateralRaise = 11,
		LyingDumbbellRaise = 12,
		MuscleUp = 13,
		OneArmCableLateralRaise = 14,
		OverhandGripRearLateralRaise = 15,
		PlateRaises = 16,
		RingDip = 17,
		WeightedRingDip = 18,
		RingMuscleUp = 19,
		WeightedRingMuscleUp = 20,
		RopeClimb = 21,
		WeightedRopeClimb = 22,
		Scaption = 23,
		SeatedLateralRaise = 24,
		SeatedRearLateralRaise = 25,
		SideLyingLateralRaise = 26,
		StandingLift = 27,
		SuspendedRow = 28,
		UnderhandGripRearLateralRaise = 29,
		WallSlide = 30,
		WeightedWallSlide = 31,
		ArmCircles = 32,
		ShavingTheHead = 33,
	}
}
crate::key_value_enum! {
	pub enum LegCurlExerciseName { 
		LegCurl = 0,
		WeightedLegCurl = 1,
		GoodMorning = 2,
		SeatedBarbellGoodMorning = 3,
		SingleLegBarbellGoodMorning = 4,
		SingleLegSlidingLegCurl = 5,
		SlidingLegCurl = 6,
		SplitBarbellGoodMorning = 7,
		SplitStanceExtension = 8,
		StaggeredStanceGoodMorning = 9,
		SwissBallHipRaiseAndLegCurl = 10,
		ZercherGoodMorning = 11,
	}
}
crate::key_value_enum! {
	pub enum LegRaiseExerciseName { 
		HangingKneeRaise = 0,
		HangingLegRaise = 1,
		WeightedHangingLegRaise = 2,
		HangingSingleLegRaise = 3,
		WeightedHangingSingleLegRaise = 4,
		KettlebellLegRaises = 5,
		LegLoweringDrill = 6,
		WeightedLegLoweringDrill = 7,
		LyingStraightLegRaise = 8,
		WeightedLyingStraightLegRaise = 9,
		MedicineBallLegDrops = 10,
		QuadrupedLegRaise = 11,
		WeightedQuadrupedLegRaise = 12,
		ReverseLegRaise = 13,
		WeightedReverseLegRaise = 14,
		ReverseLegRaiseOnSwissBall = 15,
		WeightedReverseLegRaiseOnSwissBall = 16,
		SingleLegLoweringDrill = 17,
		WeightedSingleLegLoweringDrill = 18,
		WeightedHangingKneeRaise = 19,
		LateralStepover = 20,
		WeightedLateralStepover = 21,
	}
}
crate::key_value_enum! {
	pub enum LungeExerciseName { 
		OverheadLunge = 0,
		LungeMatrix = 1,
		WeightedLungeMatrix = 2,
		AlternatingBarbellForwardLunge = 3,
		AlternatingDumbbellLungeWithReach = 4,
		BackFootElevatedDumbbellSplitSquat = 5,
		BarbellBoxLunge = 6,
		BarbellBulgarianSplitSquat = 7,
		BarbellCrossoverLunge = 8,
		BarbellFrontSplitSquat = 9,
		BarbellLunge = 10,
		BarbellReverseLunge = 11,
		BarbellSideLunge = 12,
		BarbellSplitSquat = 13,
		CoreControlRearLunge = 14,
		DiagonalLunge = 15,
		DropLunge = 16,
		DumbbellBoxLunge = 17,
		DumbbellBulgarianSplitSquat = 18,
		DumbbellCrossoverLunge = 19,
		DumbbellDiagonalLunge = 20,
		DumbbellLunge = 21,
		DumbbellLungeAndRotation = 22,
		DumbbellOverheadBulgarianSplitSquat = 23,
		DumbbellReverseLungeToHighKneeAndPress = 24,
		DumbbellSideLunge = 25,
		ElevatedFrontFootBarbellSplitSquat = 26,
		FrontFootElevatedDumbbellSplitSquat = 27,
		GunslingerLunge = 28,
		LawnmowerLunge = 29,
		LowLungeWithIsometricAdduction = 30,
		LowSideToSideLunge = 31,
		Lunge = 32,
		WeightedLunge = 33,
		LungeWithArmReach = 34,
		LungeWithDiagonalReach = 35,
		LungeWithSideBend = 36,
		OffsetDumbbellLunge = 37,
		OffsetDumbbellReverseLunge = 38,
		OverheadBulgarianSplitSquat = 39,
		OverheadDumbbellReverseLunge = 40,
		OverheadDumbbellSplitSquat = 41,
		OverheadLungeWithRotation = 42,
		ReverseBarbellBoxLunge = 43,
		ReverseBoxLunge = 44,
		ReverseDumbbellBoxLunge = 45,
		ReverseDumbbellCrossoverLunge = 46,
		ReverseDumbbellDiagonalLunge = 47,
		ReverseLungeWithReachBack = 48,
		WeightedReverseLungeWithReachBack = 49,
		ReverseLungeWithTwistAndOverheadReach = 50,
		WeightedReverseLungeWithTwistAndOverheadReach = 51,
		ReverseSlidingBoxLunge = 52,
		WeightedReverseSlidingBoxLunge = 53,
		ReverseSlidingLunge = 54,
		WeightedReverseSlidingLunge = 55,
		RunnersLungeToBalance = 56,
		WeightedRunnersLungeToBalance = 57,
		ShiftingSideLunge = 58,
		SideAndCrossoverLunge = 59,
		WeightedSideAndCrossoverLunge = 60,
		SideLunge = 61,
		WeightedSideLunge = 62,
		SideLungeAndPress = 63,
		SideLungeJumpOff = 64,
		SideLungeSweep = 65,
		WeightedSideLungeSweep = 66,
		SideLungeToCrossoverTap = 67,
		WeightedSideLungeToCrossoverTap = 68,
		SideToSideLungeChops = 69,
		WeightedSideToSideLungeChops = 70,
		SiffJumpLunge = 71,
		WeightedSiffJumpLunge = 72,
		SingleArmReverseLungeAndPress = 73,
		SlidingLateralLunge = 74,
		WeightedSlidingLateralLunge = 75,
		WalkingBarbellLunge = 76,
		WalkingDumbbellLunge = 77,
		WalkingLunge = 78,
		WeightedWalkingLunge = 79,
		WideGripOverheadBarbellSplitSquat = 80,
	}
}
crate::key_value_enum! {
	pub enum OlympicLiftExerciseName { 
		BarbellHangPowerClean = 0,
		BarbellHangSquatClean = 1,
		BarbellPowerClean = 2,
		BarbellPowerSnatch = 3,
		BarbellSquatClean = 4,
		CleanAndJerk = 5,
		BarbellHangPowerSnatch = 6,
		BarbellHangPull = 7,
		BarbellHighPull = 8,
		BarbellSnatch = 9,
		BarbellSplitJerk = 10,
		Clean = 11,
		DumbbellClean = 12,
		DumbbellHangPull = 13,
		OneHandDumbbellSplitSnatch = 14,
		PushJerk = 15,
		SingleArmDumbbellSnatch = 16,
		SingleArmHangSnatch = 17,
		SingleArmKettlebellSnatch = 18,
		SplitJerk = 19,
		SquatCleanAndJerk = 20,
	}
}
crate::key_value_enum! {
	pub enum PlankExerciseName { 
		FourfiveDegreePlank = 0,
		WeightedFourfiveDegreePlank = 1,
		Nine0DegreeStaticHold = 2,
		WeightedNine0DegreeStaticHold = 3,
		BearCrawl = 4,
		WeightedBearCrawl = 5,
		CrossBodyMountainClimber = 6,
		WeightedCrossBodyMountainClimber = 7,
		ElbowPlankPikeJacks = 8,
		WeightedElbowPlankPikeJacks = 9,
		ElevatedFeetPlank = 10,
		WeightedElevatedFeetPlank = 11,
		ElevatorAbs = 12,
		WeightedElevatorAbs = 13,
		ExtendedPlank = 14,
		WeightedExtendedPlank = 15,
		FullPlankPasseTwist = 16,
		WeightedFullPlankPasseTwist = 17,
		InchingElbowPlank = 18,
		WeightedInchingElbowPlank = 19,
		InchwormToSidePlank = 20,
		WeightedInchwormToSidePlank = 21,
		KneelingPlank = 22,
		WeightedKneelingPlank = 23,
		KneelingSidePlankWithLegLift = 24,
		WeightedKneelingSidePlankWithLegLift = 25,
		LateralRoll = 26,
		WeightedLateralRoll = 27,
		LyingReversePlank = 28,
		WeightedLyingReversePlank = 29,
		MedicineBallMountainClimber = 30,
		WeightedMedicineBallMountainClimber = 31,
		ModifiedMountainClimberAndExtension = 32,
		WeightedModifiedMountainClimberAndExtension = 33,
		MountainClimber = 34,
		WeightedMountainClimber = 35,
		MountainClimberOnSlidingDiscs = 36,
		WeightedMountainClimberOnSlidingDiscs = 37,
		MountainClimberWithFeetOnBosuBall = 38,
		WeightedMountainClimberWithFeetOnBosuBall = 39,
		MountainClimberWithHandsOnBench = 40,
		MountainClimberWithHandsOnSwissBall = 41,
		WeightedMountainClimberWithHandsOnSwissBall = 42,
		Plank = 43,
		PlankJacksWithFeetOnSlidingDiscs = 44,
		WeightedPlankJacksWithFeetOnSlidingDiscs = 45,
		PlankKneeTwist = 46,
		WeightedPlankKneeTwist = 47,
		PlankPikeJumps = 48,
		WeightedPlankPikeJumps = 49,
		PlankPikes = 50,
		WeightedPlankPikes = 51,
		PlankToStandUp = 52,
		WeightedPlankToStandUp = 53,
		PlankWithArmRaise = 54,
		WeightedPlankWithArmRaise = 55,
		PlankWithKneeToElbow = 56,
		WeightedPlankWithKneeToElbow = 57,
		PlankWithObliqueCrunch = 58,
		WeightedPlankWithObliqueCrunch = 59,
		PlyometricSidePlank = 60,
		WeightedPlyometricSidePlank = 61,
		RollingSidePlank = 62,
		WeightedRollingSidePlank = 63,
		SideKickPlank = 64,
		WeightedSideKickPlank = 65,
		SidePlank = 66,
		WeightedSidePlank = 67,
		SidePlankAndRow = 68,
		WeightedSidePlankAndRow = 69,
		SidePlankLift = 70,
		WeightedSidePlankLift = 71,
		SidePlankWithElbowOnBosuBall = 72,
		WeightedSidePlankWithElbowOnBosuBall = 73,
		SidePlankWithFeetOnBench = 74,
		WeightedSidePlankWithFeetOnBench = 75,
		SidePlankWithKneeCircle = 76,
		WeightedSidePlankWithKneeCircle = 77,
		SidePlankWithKneeTuck = 78,
		WeightedSidePlankWithKneeTuck = 79,
		SidePlankWithLegLift = 80,
		WeightedSidePlankWithLegLift = 81,
		SidePlankWithReachUnder = 82,
		WeightedSidePlankWithReachUnder = 83,
		SingleLegElevatedFeetPlank = 84,
		WeightedSingleLegElevatedFeetPlank = 85,
		SingleLegFlexAndExtend = 86,
		WeightedSingleLegFlexAndExtend = 87,
		SingleLegSidePlank = 88,
		WeightedSingleLegSidePlank = 89,
		SpidermanPlank = 90,
		WeightedSpidermanPlank = 91,
		StraightArmPlank = 92,
		WeightedStraightArmPlank = 93,
		StraightArmPlankWithShoulderTouch = 94,
		WeightedStraightArmPlankWithShoulderTouch = 95,
		SwissBallPlank = 96,
		WeightedSwissBallPlank = 97,
		SwissBallPlankLegLift = 98,
		WeightedSwissBallPlankLegLift = 99,
		SwissBallPlankLegLiftAndHold = 100,
		SwissBallPlankWithFeetOnBench = 101,
		WeightedSwissBallPlankWithFeetOnBench = 102,
		SwissBallProneJackknife = 103,
		WeightedSwissBallProneJackknife = 104,
		SwissBallSidePlank = 105,
		WeightedSwissBallSidePlank = 106,
		ThreeWayPlank = 107,
		WeightedThreeWayPlank = 108,
		TowelPlankAndKneeIn = 109,
		WeightedTowelPlankAndKneeIn = 110,
		TStabilization = 111,
		WeightedTStabilization = 112,
		TurkishGetUpToSidePlank = 113,
		WeightedTurkishGetUpToSidePlank = 114,
		TwoPointPlank = 115,
		WeightedTwoPointPlank = 116,
		WeightedPlank = 117,
		WideStancePlankWithDiagonalArmLift = 118,
		WeightedWideStancePlankWithDiagonalArmLift = 119,
		WideStancePlankWithDiagonalLegLift = 120,
		WeightedWideStancePlankWithDiagonalLegLift = 121,
		WideStancePlankWithLegLift = 122,
		WeightedWideStancePlankWithLegLift = 123,
		WideStancePlankWithOppositeArmAndLegLift = 124,
		WeightedMountainClimberWithHandsOnBench = 125,
		WeightedSwissBallPlankLegLiftAndHold = 126,
		WeightedWideStancePlankWithOppositeArmAndLegLift = 127,
		PlankWithFeetOnSwissBall = 128,
		SidePlankToPlankWithReachUnder = 129,
		BridgeWithGluteLowerLift = 130,
		BridgeOneLegBridge = 131,
		PlankWithArmVariations = 132,
		PlankWithLegLift = 133,
		ReversePlankWithLegPull = 134,
	}
}
crate::key_value_enum! {
	pub enum PlyoExerciseName { 
		AlternatingJumpLunge = 0,
		WeightedAlternatingJumpLunge = 1,
		BarbellJumpSquat = 2,
		BodyWeightJumpSquat = 3,
		WeightedJumpSquat = 4,
		CrossKneeStrike = 5,
		WeightedCrossKneeStrike = 6,
		DepthJump = 7,
		WeightedDepthJump = 8,
		DumbbellJumpSquat = 9,
		DumbbellSplitJump = 10,
		FrontKneeStrike = 11,
		WeightedFrontKneeStrike = 12,
		HighBoxJump = 13,
		WeightedHighBoxJump = 14,
		IsometricExplosiveBodyWeightJumpSquat = 15,
		WeightedIsometricExplosiveJumpSquat = 16,
		LateralLeapAndHop = 17,
		WeightedLateralLeapAndHop = 18,
		LateralPlyoSquats = 19,
		WeightedLateralPlyoSquats = 20,
		LateralSlide = 21,
		WeightedLateralSlide = 22,
		MedicineBallOverheadThrows = 23,
		MedicineBallSideThrow = 24,
		MedicineBallSlam = 25,
		SideToSideMedicineBallThrows = 26,
		SideToSideShuffleJump = 27,
		WeightedSideToSideShuffleJump = 28,
		SquatJumpOntoBox = 29,
		WeightedSquatJumpOntoBox = 30,
		SquatJumpsInAndOut = 31,
		WeightedSquatJumpsInAndOut = 32,
	}
}
crate::key_value_enum! {
	pub enum PullUpExerciseName { 
		BandedPullUps = 0,
		Three0DegreeLatPulldown = 1,
		BandAssistedChinUp = 2,
		CloseGripChinUp = 3,
		WeightedCloseGripChinUp = 4,
		CloseGripLatPulldown = 5,
		CrossoverChinUp = 6,
		WeightedCrossoverChinUp = 7,
		EzBarPullover = 8,
		HangingHurdle = 9,
		WeightedHangingHurdle = 10,
		KneelingLatPulldown = 11,
		KneelingUnderhandGripLatPulldown = 12,
		LatPulldown = 13,
		MixedGripChinUp = 14,
		WeightedMixedGripChinUp = 15,
		MixedGripPullUp = 16,
		WeightedMixedGripPullUp = 17,
		ReverseGripPulldown = 18,
		StandingCablePullover = 19,
		StraightArmPulldown = 20,
		SwissBallEzBarPullover = 21,
		TowelPullUp = 22,
		WeightedTowelPullUp = 23,
		WeightedPullUp = 24,
		WideGripLatPulldown = 25,
		WideGripPullUp = 26,
		WeightedWideGripPullUp = 27,
		BurpeePullUp = 28,
		WeightedBurpeePullUp = 29,
		JumpingPullUps = 30,
		WeightedJumpingPullUps = 31,
		KippingPullUp = 32,
		WeightedKippingPullUp = 33,
		LPullUp = 34,
		WeightedLPullUp = 35,
		SuspendedChinUp = 36,
		WeightedSuspendedChinUp = 37,
		PullUp = 38,
	}
}
crate::key_value_enum! {
	pub enum PushUpExerciseName { 
		ChestPressWithBand = 0,
		AlternatingStaggeredPushUp = 1,
		WeightedAlternatingStaggeredPushUp = 2,
		AlternatingHandsMedicineBallPushUp = 3,
		WeightedAlternatingHandsMedicineBallPushUp = 4,
		BosuBallPushUp = 5,
		WeightedBosuBallPushUp = 6,
		ClappingPushUp = 7,
		WeightedClappingPushUp = 8,
		CloseGripMedicineBallPushUp = 9,
		WeightedCloseGripMedicineBallPushUp = 10,
		CloseHandsPushUp = 11,
		WeightedCloseHandsPushUp = 12,
		DeclinePushUp = 13,
		WeightedDeclinePushUp = 14,
		DiamondPushUp = 15,
		WeightedDiamondPushUp = 16,
		ExplosiveCrossoverPushUp = 17,
		WeightedExplosiveCrossoverPushUp = 18,
		ExplosivePushUp = 19,
		WeightedExplosivePushUp = 20,
		FeetElevatedSideToSidePushUp = 21,
		WeightedFeetElevatedSideToSidePushUp = 22,
		HandReleasePushUp = 23,
		WeightedHandReleasePushUp = 24,
		HandstandPushUp = 25,
		WeightedHandstandPushUp = 26,
		InclinePushUp = 27,
		WeightedInclinePushUp = 28,
		IsometricExplosivePushUp = 29,
		WeightedIsometricExplosivePushUp = 30,
		JudoPushUp = 31,
		WeightedJudoPushUp = 32,
		KneelingPushUp = 33,
		WeightedKneelingPushUp = 34,
		MedicineBallChestPass = 35,
		MedicineBallPushUp = 36,
		WeightedMedicineBallPushUp = 37,
		OneArmPushUp = 38,
		WeightedOneArmPushUp = 39,
		WeightedPushUp = 40,
		PushUpAndRow = 41,
		WeightedPushUpAndRow = 42,
		PushUpPlus = 43,
		WeightedPushUpPlus = 44,
		PushUpWithFeetOnSwissBall = 45,
		WeightedPushUpWithFeetOnSwissBall = 46,
		PushUpWithOneHandOnMedicineBall = 47,
		WeightedPushUpWithOneHandOnMedicineBall = 48,
		ShoulderPushUp = 49,
		WeightedShoulderPushUp = 50,
		SingleArmMedicineBallPushUp = 51,
		WeightedSingleArmMedicineBallPushUp = 52,
		SpidermanPushUp = 53,
		WeightedSpidermanPushUp = 54,
		StackedFeetPushUp = 55,
		WeightedStackedFeetPushUp = 56,
		StaggeredHandsPushUp = 57,
		WeightedStaggeredHandsPushUp = 58,
		SuspendedPushUp = 59,
		WeightedSuspendedPushUp = 60,
		SwissBallPushUp = 61,
		WeightedSwissBallPushUp = 62,
		SwissBallPushUpPlus = 63,
		WeightedSwissBallPushUpPlus = 64,
		TPushUp = 65,
		WeightedTPushUp = 66,
		TripleStopPushUp = 67,
		WeightedTripleStopPushUp = 68,
		WideHandsPushUp = 69,
		WeightedWideHandsPushUp = 70,
		ParalletteHandstandPushUp = 71,
		WeightedParalletteHandstandPushUp = 72,
		RingHandstandPushUp = 73,
		WeightedRingHandstandPushUp = 74,
		RingPushUp = 75,
		WeightedRingPushUp = 76,
		PushUp = 77,
		PilatesPushup = 78,
	}
}
crate::key_value_enum! {
	pub enum RowExerciseName { 
		BarbellStraightLegDeadliftToRow = 0,
		CableRowStanding = 1,
		DumbbellRow = 2,
		ElevatedFeetInvertedRow = 3,
		WeightedElevatedFeetInvertedRow = 4,
		FacePull = 5,
		FacePullWithExternalRotation = 6,
		InvertedRowWithFeetOnSwissBall = 7,
		WeightedInvertedRowWithFeetOnSwissBall = 8,
		KettlebellRow = 9,
		ModifiedInvertedRow = 10,
		WeightedModifiedInvertedRow = 11,
		NeutralGripAlternatingDumbbellRow = 12,
		OneArmBentOverRow = 13,
		OneLeggedDumbbellRow = 14,
		RenegadeRow = 15,
		ReverseGripBarbellRow = 16,
		RopeHandleCableRow = 17,
		SeatedCableRow = 18,
		SeatedDumbbellRow = 19,
		SingleArmCableRow = 20,
		SingleArmCableRowAndRotation = 21,
		SingleArmInvertedRow = 22,
		WeightedSingleArmInvertedRow = 23,
		SingleArmNeutralGripDumbbellRow = 24,
		SingleArmNeutralGripDumbbellRowAndRotation = 25,
		SuspendedInvertedRow = 26,
		WeightedSuspendedInvertedRow = 27,
		TBarRow = 28,
		TowelGripInvertedRow = 29,
		WeightedTowelGripInvertedRow = 30,
		UnderhandGripCableRow = 31,
		VGripCableRow = 32,
		WideGripSeatedCableRow = 33,
	}
}
crate::key_value_enum! {
	pub enum ShoulderPressExerciseName { 
		AlternatingDumbbellShoulderPress = 0,
		ArnoldPress = 1,
		BarbellFrontSquatToPushPress = 2,
		BarbellPushPress = 3,
		BarbellShoulderPress = 4,
		DeadCurlPress = 5,
		DumbbellAlternatingShoulderPressAndTwist = 6,
		DumbbellHammerCurlToLungeToPress = 7,
		DumbbellPushPress = 8,
		FloorInvertedShoulderPress = 9,
		WeightedFloorInvertedShoulderPress = 10,
		InvertedShoulderPress = 11,
		WeightedInvertedShoulderPress = 12,
		OneArmPushPress = 13,
		OverheadBarbellPress = 14,
		OverheadDumbbellPress = 15,
		SeatedBarbellShoulderPress = 16,
		SeatedDumbbellShoulderPress = 17,
		SingleArmDumbbellShoulderPress = 18,
		SingleArmStepUpAndPress = 19,
		SmithMachineOverheadPress = 20,
		SplitStanceHammerCurlToPress = 21,
		SwissBallDumbbellShoulderPress = 22,
		WeightPlateFrontRaise = 23,
	}
}
crate::key_value_enum! {
	pub enum ShoulderStabilityExerciseName { 
		Nine0DegreeCableExternalRotation = 0,
		BandExternalRotation = 1,
		BandInternalRotation = 2,
		BentArmLateralRaiseAndExternalRotation = 3,
		CableExternalRotation = 4,
		DumbbellFacePullWithExternalRotation = 5,
		FloorIRaise = 6,
		WeightedFloorIRaise = 7,
		FloorTRaise = 8,
		WeightedFloorTRaise = 9,
		FloorYRaise = 10,
		WeightedFloorYRaise = 11,
		InclineIRaise = 12,
		WeightedInclineIRaise = 13,
		InclineLRaise = 14,
		WeightedInclineLRaise = 15,
		InclineTRaise = 16,
		WeightedInclineTRaise = 17,
		InclineWRaise = 18,
		WeightedInclineWRaise = 19,
		InclineYRaise = 20,
		WeightedInclineYRaise = 21,
		LyingExternalRotation = 22,
		SeatedDumbbellExternalRotation = 23,
		StandingLRaise = 24,
		SwissBallIRaise = 25,
		WeightedSwissBallIRaise = 26,
		SwissBallTRaise = 27,
		WeightedSwissBallTRaise = 28,
		SwissBallWRaise = 29,
		WeightedSwissBallWRaise = 30,
		SwissBallYRaise = 31,
		WeightedSwissBallYRaise = 32,
	}
}
crate::key_value_enum! {
	pub enum ShrugExerciseName { 
		BarbellJumpShrug = 0,
		BarbellShrug = 1,
		BarbellUprightRow = 2,
		BehindTheBackSmithMachineShrug = 3,
		DumbbellJumpShrug = 4,
		DumbbellShrug = 5,
		DumbbellUprightRow = 6,
		InclineDumbbellShrug = 7,
		OverheadBarbellShrug = 8,
		OverheadDumbbellShrug = 9,
		ScaptionAndShrug = 10,
		ScapularRetraction = 11,
		SerratusChairShrug = 12,
		WeightedSerratusChairShrug = 13,
		SerratusShrug = 14,
		WeightedSerratusShrug = 15,
		WideGripJumpShrug = 16,
	}
}
crate::key_value_enum! {
	pub enum SitUpExerciseName { 
		AlternatingSitUp = 0,
		WeightedAlternatingSitUp = 1,
		BentKneeVUp = 2,
		WeightedBentKneeVUp = 3,
		ButterflySitUp = 4,
		WeightedButterflySitup = 5,
		CrossPunchRollUp = 6,
		WeightedCrossPunchRollUp = 7,
		CrossedArmsSitUp = 8,
		WeightedCrossedArmsSitUp = 9,
		GetUpSitUp = 10,
		WeightedGetUpSitUp = 11,
		HoveringSitUp = 12,
		WeightedHoveringSitUp = 13,
		KettlebellSitUp = 14,
		MedicineBallAlternatingVUp = 15,
		MedicineBallSitUp = 16,
		MedicineBallVUp = 17,
		ModifiedSitUp = 18,
		NegativeSitUp = 19,
		OneArmFullSitUp = 20,
		RecliningCircle = 21,
		WeightedRecliningCircle = 22,
		ReverseCurlUp = 23,
		WeightedReverseCurlUp = 24,
		SingleLegSwissBallJackknife = 25,
		WeightedSingleLegSwissBallJackknife = 26,
		TheTeaser = 27,
		TheTeaserWeighted = 28,
		ThreePartRollDown = 29,
		WeightedThreePartRollDown = 30,
		VUp = 31,
		WeightedVUp = 32,
		WeightedRussianTwistOnSwissBall = 33,
		WeightedSitUp = 34,
		XAbs = 35,
		WeightedXAbs = 36,
		SitUp = 37,
	}
}
crate::key_value_enum! {
	pub enum SquatExerciseName { 
		LegPress = 0,
		BackSquatWithBodyBar = 1,
		BackSquats = 2,
		WeightedBackSquats = 3,
		BalancingSquat = 4,
		WeightedBalancingSquat = 5,
		BarbellBackSquat = 6,
		BarbellBoxSquat = 7,
		BarbellFrontSquat = 8,
		BarbellHackSquat = 9,
		BarbellHangSquatSnatch = 10,
		BarbellLateralStepUp = 11,
		BarbellQuarterSquat = 12,
		BarbellSiffSquat = 13,
		BarbellSquatSnatch = 14,
		BarbellSquatWithHeelsRaised = 15,
		BarbellStepover = 16,
		BarbellStepUp = 17,
		BenchSquatWithRotationalChop = 18,
		WeightedBenchSquatWithRotationalChop = 19,
		BodyWeightWallSquat = 20,
		WeightedWallSquat = 21,
		BoxStepSquat = 22,
		WeightedBoxStepSquat = 23,
		BracedSquat = 24,
		CrossedArmBarbellFrontSquat = 25,
		CrossoverDumbbellStepUp = 26,
		DumbbellFrontSquat = 27,
		DumbbellSplitSquat = 28,
		DumbbellSquat = 29,
		DumbbellSquatClean = 30,
		DumbbellStepover = 31,
		DumbbellStepUp = 32,
		ElevatedSingleLegSquat = 33,
		WeightedElevatedSingleLegSquat = 34,
		FigureFourSquats = 35,
		WeightedFigureFourSquats = 36,
		GobletSquat = 37,
		KettlebellSquat = 38,
		KettlebellSwingOverhead = 39,
		KettlebellSwingWithFlipToSquat = 40,
		LateralDumbbellStepUp = 41,
		OneLeggedSquat = 42,
		OverheadDumbbellSquat = 43,
		OverheadSquat = 44,
		PartialSingleLegSquat = 45,
		WeightedPartialSingleLegSquat = 46,
		PistolSquat = 47,
		WeightedPistolSquat = 48,
		PlieSlides = 49,
		WeightedPlieSlides = 50,
		PlieSquat = 51,
		WeightedPlieSquat = 52,
		PrisonerSquat = 53,
		WeightedPrisonerSquat = 54,
		SingleLegBenchGetUp = 55,
		WeightedSingleLegBenchGetUp = 56,
		SingleLegBenchSquat = 57,
		WeightedSingleLegBenchSquat = 58,
		SingleLegSquatOnSwissBall = 59,
		WeightedSingleLegSquatOnSwissBall = 60,
		Squat = 61,
		WeightedSquat = 62,
		SquatsWithBand = 63,
		StaggeredSquat = 64,
		WeightedStaggeredSquat = 65,
		StepUp = 66,
		WeightedStepUp = 67,
		SuitcaseSquats = 68,
		SumoSquat = 69,
		SumoSquatSlideIn = 70,
		WeightedSumoSquatSlideIn = 71,
		SumoSquatToHighPull = 72,
		SumoSquatToStand = 73,
		WeightedSumoSquatToStand = 74,
		SumoSquatWithRotation = 75,
		WeightedSumoSquatWithRotation = 76,
		SwissBallBodyWeightWallSquat = 77,
		WeightedSwissBallWallSquat = 78,
		Thrusters = 79,
		UnevenSquat = 80,
		WeightedUnevenSquat = 81,
		WaistSlimmingSquat = 82,
		WallBall = 83,
		WideStanceBarbellSquat = 84,
		WideStanceGobletSquat = 85,
		ZercherSquat = 86,
		KbsOverhead = 87,
		SquatAndSideKick = 88,
		SquatJumpsInNOut = 89,
		PilatesPlieSquatsParallelTurnedOutFlatAndHeels = 90,
		ReleveStraightLegAndKneeBentWithOneLegVariation = 91,
	}
}
crate::key_value_enum! {
	pub enum TotalBodyExerciseName { 
		Burpee = 0,
		WeightedBurpee = 1,
		BurpeeBoxJump = 2,
		WeightedBurpeeBoxJump = 3,
		HighPullBurpee = 4,
		ManMakers = 5,
		OneArmBurpee = 6,
		SquatThrusts = 7,
		WeightedSquatThrusts = 8,
		SquatPlankPushUp = 9,
		WeightedSquatPlankPushUp = 10,
		StandingTRotationBalance = 11,
		WeightedStandingTRotationBalance = 12,
	}
}
crate::key_value_enum! {
	pub enum TricepsExtensionExerciseName { 
		BenchDip = 0,
		WeightedBenchDip = 1,
		BodyWeightDip = 2,
		CableKickback = 3,
		CableLyingTricepsExtension = 4,
		CableOverheadTricepsExtension = 5,
		DumbbellKickback = 6,
		DumbbellLyingTricepsExtension = 7,
		EzBarOverheadTricepsExtension = 8,
		InclineDip = 9,
		WeightedInclineDip = 10,
		InclineEzBarLyingTricepsExtension = 11,
		LyingDumbbellPulloverToExtension = 12,
		LyingEzBarTricepsExtension = 13,
		LyingTricepsExtensionToCloseGripBenchPress = 14,
		OverheadDumbbellTricepsExtension = 15,
		RecliningTricepsPress = 16,
		ReverseGripPressdown = 17,
		ReverseGripTricepsPressdown = 18,
		RopePressdown = 19,
		SeatedBarbellOverheadTricepsExtension = 20,
		SeatedDumbbellOverheadTricepsExtension = 21,
		SeatedEzBarOverheadTricepsExtension = 22,
		SeatedSingleArmOverheadDumbbellExtension = 23,
		SingleArmDumbbellOverheadTricepsExtension = 24,
		SingleDumbbellSeatedOverheadTricepsExtension = 25,
		SingleLegBenchDipAndKick = 26,
		WeightedSingleLegBenchDipAndKick = 27,
		SingleLegDip = 28,
		WeightedSingleLegDip = 29,
		StaticLyingTricepsExtension = 30,
		SuspendedDip = 31,
		WeightedSuspendedDip = 32,
		SwissBallDumbbellLyingTricepsExtension = 33,
		SwissBallEzBarLyingTricepsExtension = 34,
		SwissBallEzBarOverheadTricepsExtension = 35,
		TabletopDip = 36,
		WeightedTabletopDip = 37,
		TricepsExtensionOnFloor = 38,
		TricepsPressdown = 39,
		WeightedDip = 40,
	}
}
crate::key_value_enum! {
	pub enum WarmUpExerciseName { 
		QuadrupedRocking = 0,
		NeckTilts = 1,
		AnkleCircles = 2,
		AnkleDorsiflexionWithBand = 3,
		AnkleInternalRotation = 4,
		ArmCircles = 5,
		BentOverReachToSky = 6,
		CatCamel = 7,
		ElbowToFootLunge = 8,
		ForwardAndBackwardLegSwings = 9,
		Groiners = 10,
		InvertedHamstringStretch = 11,
		LateralDuckUnder = 12,
		NeckRotations = 13,
		OppositeArmAndLegBalance = 14,
		ReachRollAndLift = 15,
		Scorpion = 16,
		ShoulderCircles = 17,
		SideToSideLegSwings = 18,
		SleeperStretch = 19,
		SlideOut = 20,
		SwissBallHipCrossover = 21,
		SwissBallReachRollAndLift = 22,
		SwissBallWindshieldWipers = 23,
		ThoracicRotation = 24,
		WalkingHighKicks = 25,
		WalkingHighKnees = 26,
		WalkingKneeHugs = 27,
		WalkingLegCradles = 28,
		Walkout = 29,
		WalkoutFromPushUpPosition = 30,
	}
}
crate::key_value_enum! {
	pub enum RunExerciseName { 
		Run = 0,
		Walk = 1,
		Jog = 2,
		Sprint = 3,
	}
}
crate::key_value_enum! {
	pub enum WaterType { 
		Fresh = 0,
		Salt = 1,
		Enonethreethreeonenine = 2,
		Custom = 3,
	}
}
crate::key_value_enum! {
	pub enum TissueModelType { 
		ZhlOnesixc = 0,
	}
}
crate::key_value_enum! {
	pub enum DiveGasStatus { 
		Disabled = 0,
		Enabled = 1,
		BackupOnly = 2,
	}
}
crate::key_value_enum! {
	pub enum DiveAlert { 
		NdlReached = 0,
		GasSwitchPrompted = 1,
		NearSurface = 2,
		ApproachingNdl = 3,
		PotwoWarn = 4,
		PotwoCritHigh = 5,
		PotwoCritLow = 6,
		TimeAlert = 7,
		DepthAlert = 8,
		DecoCeilingBroken = 9,
		DecoComplete = 10,
		SafetyStopBroken = 11,
		SafetyStopComplete = 12,
		CnsWarning = 13,
		CnsCritical = 14,
		OtuWarning = 15,
		OtuCritical = 16,
		AscentCritical = 17,
		AlertDismissedByKey = 18,
		AlertDismissedByTimeout = 19,
		BatteryLow = 20,
		BatteryCritical = 21,
		SafetyStopStarted = 22,
		ApproachingFirstDecoStop = 23,
		SetpointSwitchAutoLow = 24,
		SetpointSwitchAutoHigh = 25,
		SetpointSwitchManualLow = 26,
		SetpointSwitchManualHigh = 27,
		AutoSetpointSwitchIgnored = 28,
		SwitchedToOpenCircuit = 29,
		SwitchedToClosedCircuit = 30,
		TankBatteryLow = 32,
		PotwoCcrDilLow = 33,
		DecoStopCleared = 34,
		ApneaNeutralBuoyancy = 35,
		ApneaTargetDepth = 36,
		ApneaSurface = 37,
		ApneaHighSpeed = 38,
		ApneaLowSpeed = 39,
	}
}
crate::key_value_enum! {
	pub enum DiveAlarmType { 
		Depth = 0,
		Time = 1,
		Speed = 2,
	}
}
crate::key_value_enum! {
	pub enum DiveBacklightMode { 
		AtDepth = 0,
		AlwaysOn = 1,
	}
}
crate::key_value_enum! {
	pub enum SleepLevel { 
		Unmeasurable = 0,
		Awake = 1,
		Light = 2,
		Deep = 3,
		Rem = 4,
	}
}
crate::key_value_enum! {
	pub enum SpotwoMeasurementType { 
		OffWrist = 0,
		SpotCheck = 1,
		ContinuousCheck = 2,
		Periodic = 3,
	}
}
crate::key_value_enum! {
	pub enum CcrSetpointSwitchMode { 
		Manual = 0,
		Automatic = 1,
	}
}
crate::key_value_enum! {
	pub enum DiveGasMode { 
		OpenCircuit = 0,
		ClosedCircuitDiluent = 1,
	}
}
crate::key_value_enum! {
	pub enum ProjectileType { 
		Arrow = 0,
		RifleCartridge = 1,
		PistolCartridge = 2,
		Shotshell = 3,
		AirRiflePellet = 4,
		Other = 5,
	}
}
crate::key_value_enum! {
	pub enum FaveroProduct { 
		AssiomaUno = 10,
		AssiomaDuo = 12,
	}
}
crate::key_value_enum! {
	pub enum SplitType { 
		AscentSplit = 1,
		DescentSplit = 2,
		IntervalActive = 3,
		IntervalRest = 4,
		IntervalWarmup = 5,
		IntervalCooldown = 6,
		IntervalRecovery = 7,
		IntervalOther = 8,
		ClimbActive = 9,
		ClimbRest = 10,
		SurfActive = 11,
		RunActive = 12,
		RunRest = 13,
		WorkoutRound = 14,
		RwdRun = 17,
		RwdWalk = 18,
		WindsurfActive = 21,
		RwdStand = 22,
		Transition = 23,
		SkiLiftSplit = 28,
		SkiRunSplit = 29,
	}
}
crate::key_value_enum! {
	pub enum ClimbProEvent { 
		Approach = 0,
		Start = 1,
		Complete = 2,
	}
}
crate::key_value_enum! {
	pub enum GasConsumptionRateType { 
		PressureSac = 0,
		VolumeSac = 1,
		Rmv = 2,
	}
}
crate::key_value_enum! {
	pub enum TapSensitivity { 
		High = 0,
		Medium = 1,
		Low = 2,
	}
}
crate::key_value_enum! {
	pub enum RadarThreatLevelType { 
		ThreatUnknown = 0,
		ThreatNone = 1,
		ThreatApproaching = 2,
		ThreatApproachingFast = 3,
	}
}
crate::key_value_enum! {
	pub enum MaxMetSpeedSource { 
		OnboardGps = 0,
		ConnectedGps = 1,
		Cadence = 2,
	}
}
crate::key_value_enum! {
	pub enum MaxMetHeartRateSource { 
		Whr = 0,
		Hrm = 1,
	}
}
crate::key_value_enum! {
	pub enum HrvStatus { 
		None = 0,
		Poor = 1,
		Low = 2,
		Unbalanced = 3,
		Balanced = 4,
	}
}
