on: workflow_dispatch

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-gnu
            archive: zip
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            archive: tar.gz
          - os: macos-latest
            target: aarch64-apple-darwin
            archive: zip
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: Latest rustup
        run: rustup update
      - name: Install toolchain
        run: rustup target add ${{ matrix.target }}
      - name: Build
        run: cargo build --release
