name: Release
on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      target_tag:
        required: true
        description: "tag to add binaries to"

jobs:
  release:
    name: Create binaries ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-gnu
            suffix: windows_x86_64
            file-suffix: .exe
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            suffix: linux_x86_64
          - os: macos-latest
            target: aarch64-apple-darwin
            suffix: mac-aarch64
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: Latest rustup
        run: rustup update
      - name: Install toolchain
        run: rustup target add ${{ matrix.target }}
      - name: Build
        run: cargo build --release
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: rusty-but-fit-${{ matrix.suffix }}
          path: target/release/rusty-but-fit${{ matrix.file-suffix }}
      - name: download from latest release
        uses: actions/download-artifact@v4
      - name: attach to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ inputs.target_tag }} rusty-but-fit-${{ matrix.suffix }}